'use client'

import { useEffect, useState } from 'react'
import { ArrowLeft, BrainCircuit, RefreshCw, Target } from 'lucide-react'
import { Button } from '@/components/ui/button'

type Action = { conversation_id: string; action: string; probability: number; revenue: number; approved_sales: number; inbound_count: number; pending_payment_events: number; reason: string }
const labels: Record<string,string> = { payment_follow_up: 'Intervir no pagamento', upsell_or_post_sale: 'Avançar no pós-venda / upsell', sales_follow_up: 'Conduzir follow-up comercial', recovery_follow_up: 'Ativar recuperação', qualification: 'Qualificar cliente' }

export default function NextBestActionPage() {
 const [id,setId]=useState(''); const [data,setData]=useState<Action|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState('')
 const load=async()=>{setLoading(true);setError('');try{const r=await fetch(`/api/crm/next-best-action?conversation=${encodeURIComponent(id)}`,{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Falha ao calcular próxima ação.');setData(j)}catch(e){setError(e instanceof Error?e.message:'Falha ao carregar.')}finally{setLoading(false)}}
 useEffect(()=>{const q=new URLSearchParams(window.location.search).get('conversation')?.trim()||'';setId(q)},[]);useEffect(()=>{if(id)void load()},[id])
 return <main className="min-h-screen bg-[#070A09] p-5 text-white lg:p-8"><div className="mx-auto max-w-4xl"><a href="/dashboard/crm" className="mb-8 inline-flex min-h-10 items-center gap-2 rounded-xl px-3 text-xs font-bold text-slate-500 transition hover:bg-white/[.04] hover:text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1DB854]/50"><ArrowLeft size={15}/> Voltar ao Multi-CRM</a><div className="rounded-[28px] border border-white/10 bg-[#0B0F0D] p-6 lg:p-8"><div className="flex items-center gap-3 text-[#1DB854]"><BrainCircuit size={20}/><span className="text-[10px] font-black uppercase tracking-[.22em]">REVENUE OS / NEXT BEST ACTION</span></div><h1 className="mt-3 text-3xl font-black">Próxima ação recomendada</h1><p className="mt-2 text-sm text-slate-500">Recomendação determinística baseada no histórico real desta conversa, pagamentos e sinais comerciais.</p>{error&&<div role="alert" className="mt-6 rounded-2xl border border-rose-500/20 bg-rose-500/10 p-4 text-sm text-rose-200">{error}</div>}{loading?<div className="mt-8 h-48 animate-pulse rounded-3xl bg-white/[.03]"/>:data&&<><section className="mt-8 rounded-3xl border border-[#1DB854]/20 bg-[#0D1812] p-6"><div className="flex items-start justify-between gap-4"><div><div className="text-xs font-bold uppercase tracking-wider text-slate-500">Ação prioritária</div><div className="mt-2 text-2xl font-black">{labels[data.action]||data.action}</div><p className="mt-2 text-sm text-slate-400">{data.reason}</p></div><Target className="text-[#1DB854]"/></div><div className="mt-6 text-3xl font-black">{Math.round(data.probability*100)}% <span className="text-xs font-bold text-slate-500">confiança operacional</span></div></section><div className="mt-4 grid gap-3 sm:grid-cols-4">{[['Receita',`R$ ${Number(data.revenue||0).toFixed(2)}`],['Vendas aprovadas',data.approved_sales],['Inbound',data.inbound_count],['Pagamentos pendentes',data.pending_payment_events]].map(([k,v])=><article key={String(k)} className="rounded-2xl border border-white/10 bg-white/[.025] p-4"><div className="text-[9px] font-black uppercase tracking-wider text-slate-600">{k}</div><div className="mt-2 text-lg font-black">{v}</div></article>)}</div></>}<Button type="button" variant="outline" size="sm" className="mt-6" onClick={()=>void load()} disabled={loading||!id}><RefreshCw size={14} className={loading?'animate-spin':''}/> Recalcular</Button></div></div></main>
}
