const WEBHOOK_API=`${SUPABASE_URL}/functions/v1/webhook-integrations`;
async function webhookApi(path='',options={}){const s=await sb.auth.getSession();const token=s.data.session?.access_token;if(!token)throw new Error('Sessão expirada. Entre novamente.');const r=await fetch(WEBHOOK_API+path,{...options,headers:{'Content-Type':'application/json','Authorization':`Bearer ${token}`,...(options.headers||{})}});let data={};try{data=await r.json()}catch{}if(!r.ok)throw new Error(data.error||data.message||`Erro ${r.status}`);return data}
async function integrations(v){
  const [ir,fr,evr,dr]=await Promise.all([webhookApi(),sb.from('funnels').select('id,nome,name'),sb.from('integration_events').select('id,event_type,status,created_at,integration_id').order('created_at',{ascending:false}).limit(12),sb.from('webhook_deliveries').select('id,event_type,status,signature_valid,created_at,integration_id').order('created_at',{ascending:false}).limit(12)]);
  const rows=ir.integrations||[];const funnels=fr.data||[];const events=evr.data||[];const deliveries=dr.data||[];const fn=id=>{const x=funnels.find(f=>String(f.id)===String(id));return x?.nome||x?.name||'Funil não encontrado'};
  v.innerHTML=`<div class="toolbar"><div><h2>Integrações</h2><p>Webhooks, eventos e comunicação segura com seus funis.</p></div><button class="primary" onclick="newWebhookIntegration()">+ Nova integração</button></div>
  <div class="cards"><div class="card metric"><span>Integrações</span><strong>${rows.length}</strong><small>configuradas</small></div><div class="card metric"><span>Ativas</span><strong>${rows.filter(x=>x.status==='active').length}</strong><small>recebendo eventos</small></div><div class="card metric"><span>Eventos</span><strong>${rows.reduce((a,x)=>a+Number(x.event_count||0),0)}</strong><small>recebidos</small></div><div class="card metric"><span>Assinatura</span><strong>HMAC</strong><small>validação ativa</small></div></div>
  <div class="card tableWrap"><div class="sectionHead"><div><h3>Conexões</h3><small>Segredos nunca aparecem na listagem.</small></div></div><table><thead><tr><th>Integração</th><th>Funil</th><th>Provedor</th><th>Status</th><th>Eventos</th><th>Último evento</th><th></th></tr></thead><tbody>${rows.length?rows.map(x=>`<tr><td><b>${esc(x.name||'Webhook')}</b><small style="display:block;color:#777">${esc(x.secret_prefix||'')}</small></td><td>${esc(fn(x.funnel_id))}</td><td>${esc(x.provider||'custom')}</td><td>${badge(x.status)}</td><td>${Number(x.event_count||0)}</td><td>${x.last_event_at?new Date(x.last_event_at).toLocaleString('pt-BR'):'—'}</td><td><button class="secondary" onclick="webhookDetails('${x.id}')">Gerenciar</button></td></tr>`).join(''):'<tr><td colspan="7" class="empty">Nenhuma integração criada.</td></tr>'}</tbody></table></div>
  <div class="dashboardGrid"><section class="card"><div class="sectionHead"><div><h3>Eventos recebidos</h3><small>Pipeline de integração</small></div></div>${events.length?events.map(e=>`<div class="activity"><span class="dot ${e.status==='processed'?'ok':''}"></span><div><b>${esc(e.event_type||'event')}</b><small>${esc(e.status||'received')} · ${new Date(e.created_at).toLocaleString('pt-BR')}</small></div>${badge(e.status)}</div>`).join(''):'<div class="empty">Nenhum evento recebido.</div>'}</section><section class="card"><div class="sectionHead"><div><h3>Entregas de webhook</h3><small>Assinatura e processamento</small></div></div>${deliveries.length?deliveries.map(d=>`<div class="activity"><span class="dot ${d.signature_valid?'ok':''}"></span><div><b>${esc(d.event_type||'webhook')}</b><small>assinatura: ${d.signature_valid?'válida':'inválida'} · ${new Date(d.created_at).toLocaleString('pt-BR')}</small></div>${badge(d.status)}</div>`).join(''):'<div class="empty">Nenhuma entrega registrada.</div>'}</section></div>`;
}
function newWebhookIntegration(){
  sb.from('funnels').select('id,nome,name').order('created_at',{ascending:false}).then(r=>{const fs=r.data||[];modal('Nova integração Webhook',`<form id="webhookForm"><div class="field"><label>Nome da integração</label><input id="wiName" required placeholder="Meu checkout"></div><div class="field"><label>Funil</label><select id="wiFunnel" required>${fs.length?fs.map(f=>`<option value="${f.id}">${esc(f.nome||f.name||f.id)}</option>`).join(''):'<option value="">Crie um funil primeiro</option>'}</select></div><div class="field"><label>Provedor</label><select id="wiProvider"><option value="custom">Custom / API</option><option value="checkout">Checkout</option><option value="gateway">Gateway</option><option value="funnel">Funnel</option><option value="wordpress">WordPress</option></select></div><div class="notice">O ALTHEA vai gerar o endpoint e um segredo HMAC. O segredo será exibido apenas uma vez.</div><br><button class="primary" ${fs.length?'':'disabled'}>Criar integração</button></form>`);webhookForm.onsubmit=async e=>{e.preventDefault();try{const d=await webhookApi('',{method:'POST',body:JSON.stringify({name:wiName.value.trim(),funnel_id:wiFunnel.value,provider:wiProvider.value})});closeModal();showWebhookSecret(d);await integrations(document.getElementById('view'))}catch(err){alert(err.message)}}})
}
function showWebhookSecret(d){modal('Integração criada',`<div class="notice"><b>Guarde estas credenciais agora.</b><br>O segredo bruto não será exibido novamente.</div><div class="field"><label>Endpoint</label><input id="createdEndpoint" readonly value="${esc(d.endpoint||'')}"></div><div class="field"><label>Secret</label><input id="createdSecret" readonly value="${esc(d.secret||'')}"></div><div style="display:flex;gap:8px"><button class="secondary" onclick="navigator.clipboard.writeText(createdEndpoint.value)">Copiar endpoint</button><button class="primary" onclick="navigator.clipboard.writeText(createdSecret.value)">Copiar secret</button></div>`)}
async function webhookDetails(id){try{const d=await webhookApi();const x=(d.integrations||[]).find(i=>i.id===id);if(!x)throw Error('Integração não encontrada');modal('Gerenciar integração',`<div class="field"><label>Nome</label><input id="editWiName" value="${esc(x.name||'')}"></div><div class="field"><label>Status</label><select id="editWiStatus"><option value="active" ${x.status==='active'?'selected':''}>Ativa</option><option value="disabled" ${x.status==='disabled'?'selected':''}>Desativada</option></select></div><div class="field"><label>Provedor</label><input id="editWiProvider" value="${esc(x.provider||'custom')}"></div><div class="field"><label>Endpoint</label><input readonly value="${esc(x.endpoint||'')}"></div><p class="muted">${Number(x.event_count||0)} eventos · último uso: ${x.last_used_at?new Date(x.last_used_at).toLocaleString('pt-BR'):'nunca'}</p><div style="display:flex;gap:8px;flex-wrap:wrap"><button class="primary" onclick="saveWebhook('${id}')">Salvar</button><button class="secondary" onclick="rotateWebhook('${id}')">Rotacionar segredo</button><button class="danger" onclick="disableWebhook('${id}')">Desativar</button></div>`)}catch(e){alert(e.message)}}
async function saveWebhook(id){try{await webhookApi('/'+id,{method:'PATCH',body:JSON.stringify({name:editWiName.value.trim(),status:editWiStatus.value,provider:editWiProvider.value.trim()})});closeModal();go('integrations')}catch(e){alert(e.message)}}
async function rotateWebhook(id){if(!confirm('Rotacionar o segredo? O segredo atual deixará de funcionar.'))return;try{const d=await webhookApi('/'+id+'/rotate',{method:'POST'});showWebhookSecret(d)}catch(e){alert(e.message)}}
async function disableWebhook(id){if(!confirm('Desativar esta integração?'))return;try{await webhookApi('/'+id,{method:'PATCH',body:JSON.stringify({status:'disabled'})});closeModal();go('integrations')}catch(e){alert(e.message)}}