import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
import { validateFEB } from "../_shared/iara-feb-validator.ts";

type Failure = "technical" | "timeout" | "unavailable" | "declined" | "fraud" | "pending" | "validation" | "unknown";
type Gateway = { id: string; user_id: string; provider: string; display_name: string; environment: "sandbox" | "production"; status: string; capabilities: Record<string, unknown>; circuit_id: string; credential_id: string | null };
type AdapterResult = { ok: boolean; failure: Failure | null; reason: string; payload: Record<string, unknown>; latencyMs: number };
type Candidate = { gateway: Gateway; routeId: string | null; fallbackEnabled: boolean; source: "policy" | "legacy"; policyNode?: string };
const cors = { "Access-Control-Allow-Origin": "*", "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type, x-idempotency-key, idempotency-key, x-althea-feb-ticket-signature, x-althea-internal-secret", "Access-Control-Allow-Methods": "POST,OPTIONS" };
const TIMEOUT = 2800, BUDGET = 7200, SAFETY = 250, MAX_GATEWAYS = 8, MAX_RETRIES = 2, MAX_GRAPH_DEPTH = 16;
const rec = (v: unknown): v is Record<string, unknown> => typeof v === "object" && v !== null && !Array.isArray(v);
const json = (v: unknown, s = 200) => new Response(JSON.stringify(v), { status: s, headers: { ...cors, "Content-Type": "application/json" } });
const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));
const retryable = (f: Failure | null) => f === "technical" || f === "timeout" || f === "unavailable";
const providerOf = (g: Gateway) => String(g.provider).trim().toLowerCase();
const str = (v: unknown) => typeof v === "string" ? v.trim() : "";
function classify(code: number, p: unknown): Failure { const x = rec(p) ? String(p.failure_class ?? p.failure_code ?? p.error_code ?? p.error ?? "").toLowerCase() : ""; if (x.includes("fraud") || x.includes("risk")) return "fraud"; if (x.includes("pending") || x.includes("processing")) return "pending"; if (x.includes("declin") || x.includes("insufficient") || x.includes("invalid_card")) return "declined"; if (code === 408 || code === 504) return "timeout"; if (code === 429 || code >= 500) return "unavailable"; if (code >= 400) return "declined"; return "technical"; }
function statusOf(p: Record<string, unknown>) { const s = String(p.status ?? p.payment_status ?? "").toLowerCase(); if (p.approved === true || ["approved", "succeeded", "success", "paid", "received", "confirmed", "authorized", "captured"].includes(s)) return "approved"; if (["pending", "processing", "in_process", "in_review"].includes(s)) return "pending"; if (["declined", "failed", "rejected", "canceled", "cancelled"].includes(s)) return "declined"; return "error"; }
async function authUser(req: Request, url: string, key: string) { const a = req.headers.get("Authorization"); if (!a) return null; const c = createClient(url, key, { global: { headers: { Authorization: a } } }); const r = await c.auth.getUser(); return r.error ? null : r.data.user; }
async function sha256Hex(value: string) { const bytes = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(value)); return Array.from(new Uint8Array(bytes)).map((x) => x.toString(16).padStart(2, "0")).join(""); }
function numberValue(v: unknown): number | null { const n = typeof v === "number" ? v : typeof v === "string" && v.trim() !== "" ? Number(v) : NaN; return Number.isFinite(n) ? n : null; }
function fieldValue(ctx: Record<string, unknown>, field: string): unknown { const normalized = field.toLowerCase(); const aliases: Record<string, string[]> = { card_brand: ["card_brand", "cardBrand"], country: ["country", "billing_country", "billingCountry"], currency: ["currency"], payment_method: ["payment_method", "paymentMethod"], amount: ["amount"], risk_score: ["risk_score", "riskScore"], provider: ["provider"], environment: ["environment"] }; const keys = aliases[normalized] ?? [field]; for (const k of keys) if (ctx[k] !== undefined) return ctx[k]; const metadata = rec(ctx.metadata) ? ctx.metadata : {}; for (const k of keys) if (metadata[k] !== undefined) return metadata[k]; const customer = rec(ctx.customer) ? ctx.customer : {}; for (const k of keys) if (customer[k] !== undefined) return customer[k]; return undefined; }
function compare(actual: unknown, op: string, expected: unknown): boolean { const a = typeof actual === "string" ? actual.toLowerCase() : actual; const e = typeof expected === "string" ? expected.toLowerCase() : expected; switch (op) { case "eq": case "equals": case "==": return a === e; case "neq": case "not_equals": case "!=": return a !== e; case "in": return Array.isArray(e) && e.some((x) => String(x).toLowerCase() === String(a).toLowerCase()); case "not_in": return Array.isArray(e) && !e.some((x) => String(x).toLowerCase() === String(a).toLowerCase()); case "gt": case ">": return numberValue(a) !== null && numberValue(e) !== null && Number(a) > Number(e); case "gte": case ">=": return numberValue(a) !== null && numberValue(e) !== null && Number(a) >= Number(e); case "lt": case "<": return numberValue(a) !== null && numberValue(e) !== null && Number(a) < Number(e); case "lte": case "<=": return numberValue(a) !== null && numberValue(e) !== null && Number(a) <= Number(e); case "contains": return String(a).toLowerCase().includes(String(e).toLowerCase()); default: return false; } }
function evaluateCondition(condition: unknown, ctx: Record<string, unknown>): boolean { if (typeof condition === "boolean") return condition; if (typeof condition === "string") { const m = condition.match(/^([a-zA-Z_][\w]*)\s*(==|!=|>=|<=|>|<)\s*(.+)$/); if (!m) return false; const raw = m[3].trim().replace(/^['\"]|['\"]$/g, ""); const expected = /^\d+(\.\d+)?$/.test(raw) ? Number(raw) : raw; return compare(fieldValue(ctx, m[1]), m[2], expected); } if (!rec(condition)) return false; if (Array.isArray(condition.all)) return condition.all.every((x) => evaluateCondition(x, ctx)); if (Array.isArray(condition.any)) return condition.any.some((x) => evaluateCondition(x, ctx)); const field = str(condition.field ?? condition.key); const op = str(condition.operator ?? condition.op ?? "eq").toLowerCase(); if (field) return compare(fieldValue(ctx, field), op, condition.value ?? condition.expected); return false; }
function nodeType(node: Record<string, unknown>): "direct" | "split" | "conditional" | null { const t = str(node.type ?? node.node_type).toLowerCase(); return t === "direct" || t === "split" || t === "conditional" ? t : null; }
function childArray(node: Record<string, unknown>): Record<string, unknown>[] { const raw = Array.isArray(node.children) ? node.children : Array.isArray(node.gateways) ? node.gateways : Array.isArray(node.targets) ? node.targets : []; return raw.filter(rec); }
function targetId(node: Record<string, unknown>): string { return str(node.gateway_id ?? node.gatewayId ?? node.id); }
function branch(node: Record<string, unknown>, truth: boolean): Record<string, unknown> | null { const keys = truth ? ["if_true", "then", "true", "yes", "on_true"] : ["if_false", "else", "false", "no", "on_false"]; for (const k of keys) { const v = node[k]; if (rec(v)) return v; } return null; }
function validateGraph(root: unknown): { ok: true } | { ok: false; reason: string } { const seen = new Set<string>(); const walk = (node: unknown, depth: number): { ok: true } | { ok: false; reason: string } => { if (!rec(node)) return { ok: false, reason: "routing_graph_node_must_be_object" }; if (depth > MAX_GRAPH_DEPTH) return { ok: false, reason: "routing_graph_max_depth_exceeded" }; const type = nodeType(node); if (!type) return { ok: false, reason: "routing_graph_invalid_node_type" }; const nodeKey = str(node.id) || JSON.stringify(node); if (nodeKey && seen.has(nodeKey)) return { ok: false, reason: "routing_graph_cycle_detected" }; if (nodeKey) seen.add(nodeKey); if (type === "direct") { if (!targetId(node)) return { ok: false, reason: "routing_graph_direct_gateway_required" }; } else if (type === "split") { const targets = childArray(node); if (!targets.length) return { ok: false, reason: "routing_graph_split_targets_required" }; let total = 0; for (const t of targets) { if (!targetId(t)) return { ok: false, reason: "routing_graph_split_gateway_required" }; const w = numberValue(t.weight); if (w === null || w <= 0) return { ok: false, reason: "routing_graph_split_weight_invalid" }; total += w; const child = rec(t.node) ? t.node : rec(t.child) ? t.child : null; if (child) { const r = walk(child, depth + 1); if (!r.ok) return r; } } if (Math.abs(total - 100) > 0.0001) return { ok: false, reason: "routing_graph_split_weights_must_total_100" }; } else { if (!node.condition || (!branch(node, true) && !branch(node, false))) return { ok: false, reason: "routing_graph_conditional_branches_required" }; for (const b of [branch(node, true), branch(node, false)]) if (b) { const r = walk(b, depth + 1); if (!r.ok) return r; } } if (nodeKey) seen.delete(nodeKey); return { ok: true }; }; return walk(root, 0); }
async function deterministicOrder(targets: Array<{ id: string; weight: number }>, key: string) { const h = await sha256Hex(key); const bucket = parseInt(h.slice(0, 12), 16) / 0xffffffffffff; let cursor = bucket * 100; let primary = targets[targets.length - 1]; let cumulative = 0; for (const t of targets) { cumulative += t.weight; if (cursor < cumulative) { primary = t; break; } } const rest = targets.filter((x) => x.id !== primary.id); const scored = await Promise.all(rest.map(async (x) => ({ x, score: (await sha256Hex(`${key}:${x.id}`)).slice(0, 16) }))); scored.sort((a, b) => a.score.localeCompare(b.score)); return [primary, ...scored.map((x) => x.x)]; }
async function resolvePolicyCandidates(graph: Record<string, unknown>, ctx: Record<string, unknown>, stableKey: string): Promise<{ ids: string[]; trace: Record<string, unknown>[] }> { const trace: Record<string, unknown>[] = []; let node: Record<string, unknown> | null = graph; for (let depth = 0; node && depth <= MAX_GRAPH_DEPTH; depth++) { const type = nodeType(node); if (!type) throw new Error("routing_graph_invalid_node_type"); const nodeId = str(node.id) || `depth_${depth}`; if (type === "direct") { const id = targetId(node); trace.push({ node_id: nodeId, type, selected_gateway_id: id }); return { ids: id ? [id] : [], trace }; } if (type === "conditional") { const matched = evaluateCondition(node.condition, ctx); trace.push({ node_id: nodeId, type, matched }); node = branch(node, matched); continue; } const targets = childArray(node).map((x) => ({ id: targetId(x), weight: numberValue(x.weight) ?? 0 })).filter((x) => x.id && x.weight > 0); if (!targets.length) throw new Error("routing_graph_split_targets_required"); const ordered = await deterministicOrder(targets, `${stableKey}:policy:${nodeId}`); trace.push({ node_id: nodeId, type, selected_gateway_id: ordered[0].id, weights: targets }); return { ids: ordered.map((x) => x.id), trace }; } throw new Error("routing_graph_max_depth_exceeded"); }
async function callAdapter(g: Gateway, payload: Record<string, unknown>, key: string, credential: Record<string, unknown> | null, internal: string, timeoutMs: number): Promise<AdapterResult> { const p = providerOf(g), env = `GATEWAY_ADAPTER_URL_${p.replace(/[^a-z0-9]/gi, "_").toUpperCase()}`, base = Deno.env.get("GATEWAY_ADAPTER_BASE_URL")?.replace(/\/$/, ""), configured = Deno.env.get(env) ?? (base ? `${base}/adapters/${encodeURIComponent(p)}` : `${Deno.env.get("SUPABASE_URL")}/functions/v1/gateway-provider-adapter`); if (!configured) return { ok: false, failure: "unavailable", reason: "adapter_url_not_configured", payload: {}, latencyMs: 0 }; let u: string; try { const x = new URL(configured); if (x.protocol !== "https:") throw new Error("adapter_https_required"); u = x.toString(); } catch (e) { return { ok: false, failure: "validation", reason: e instanceof Error ? e.message : "invalid_adapter_url", payload: {}, latencyMs: 0 }; } const maxAttempts = p === "asaas" ? 1 : MAX_RETRIES; let last: AdapterResult = { ok: false, failure: "technical", reason: "adapter_request_failed", payload: {}, latencyMs: 0 }; for (let i = 1; i <= maxAttempts; i++) { const started = Date.now(), c = new AbortController(), t = setTimeout(() => c.abort(), Math.max(250, Math.min(TIMEOUT, timeoutMs))); try { const r = await fetch(u, { method: "POST", signal: c.signal, headers: { "Content-Type": "application/json", "X-Althea-Internal-Secret": internal, "X-Althea-Gateway-Id": g.id, "X-Althea-Idempotency-Key": key }, body: JSON.stringify({ ...payload, provider: p, environment: g.environment, gateway_id: g.id, idempotency_key: key, credential }) }); const raw = await r.json().catch(() => ({})); const body = rec(raw) ? raw : {}; const latencyMs = Date.now() - started; if (!r.ok) last = { ok: false, failure: classify(r.status, body), reason: String(body.error ?? `adapter_http_${r.status}`), payload: body, latencyMs }; else { const s = statusOf(body); if (s === "approved") return { ok: true, failure: null, reason: "approved", payload: body, latencyMs }; if (s === "pending") return { ok: false, failure: "pending", reason: "gateway_pending", payload: body, latencyMs }; if (s === "declined") return { ok: false, failure: "declined", reason: String(body.error ?? "gateway_declined"), payload: body, latencyMs }; last = { ok: false, failure: classify(r.status, body), reason: String(body.error ?? "gateway_error"), payload: body, latencyMs }; } } catch (e) { const to = e instanceof DOMException && e.name === "AbortError"; last = { ok: false, failure: to ? "timeout" : "technical", reason: to ? "adapter_timeout" : e instanceof Error ? e.message : "adapter_request_failed", payload: {}, latencyMs: Date.now() - started }; } finally { clearTimeout(t); } if (!retryable(last.failure) || i === maxAttempts) break; await sleep(100 * 2 ** (i - 1)); } return last; }
async function resolveCredential(db: ReturnType<typeof createClient>, gatewayId: string) { const r = await db.rpc("resolve_gateway_credential_for_gateway", { p_gateway_id: gatewayId }); if (r.error) throw new Error(`gateway_credential_resolution_failed:${r.error.message}`); return rec(r.data) ? r.data : null; }
async function circuit(db: ReturnType<typeof createClient>, userId: string, g: Gateway) { const r = await db.rpc("acquire_gateway_circuit", { p_user_id: userId, p_gateway_id: g.circuit_id, p_gateway_name: g.provider, p_failure_threshold: 5, p_cooldown_seconds: 60, p_probe_lease_seconds: 10 }); if (r.error) throw new Error(`gateway_circuit_acquire_failed:${r.error.message}`); const x = Array.isArray(r.data) ? r.data[0] : r.data; return rec(x) ? x : { allowed: false }; }
async function circuitResult(db: ReturnType<typeof createClient>, userId: string, g: Gateway, f: Failure | null) { if (retryable(f)) await db.rpc("record_gateway_circuit_failure", { p_user_id: userId, p_gateway_id: g.circuit_id, p_gateway_name: g.provider, p_failure_class: f, p_failure_threshold: 5 }).catch(() => undefined); else await db.rpc("record_gateway_circuit_success", { p_user_id: userId, p_gateway_id: g.circuit_id, p_gateway_name: g.provider }).catch(() => undefined); }
async function health(db: ReturnType<typeof createClient>, g: Gateway, success: boolean, latency: number) { await db.rpc("record_gateway_health", { p_gateway_id: g.circuit_id, p_gateway_name: g.provider, p_success: success, p_latency_ms: Math.max(0, Math.round(latency)) }).catch(() => undefined); }

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: cors });
  if (req.method !== "POST") return json({ error: "method_not_allowed" }, 405);
  const url = Deno.env.get("SUPABASE_URL"), anon = Deno.env.get("SUPABASE_ANON_KEY") ?? Deno.env.get("SUPABASE_PUBLISHABLE_KEY"), service = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"), internal = Deno.env.get("ALTHEA_INTERNAL_SECRET");
  if (!url || !anon || !service || !internal) return json({ error: "server_configuration_error" }, 500);
  if (req.headers.get("x-althea-internal-secret") !== internal) return json({ ok: false, code: "EXECUTION_UNAVAILABLE", retryable: false }, 403);
  const user = await authUser(req, url, anon); if (!user) return json({ error: "unauthorized" }, 401);
  const db = createClient(url, service, { auth: { persistSession: false } }); let b: Record<string, unknown>;
  try { const x: unknown = await req.json(); if (!rec(x)) return json({ error: "invalid_json" }, 400); b = x; } catch { return json({ error: "invalid_json" }, 400); }
  const fid = str(b.funnel_id), op = str(b.operation || "create_payment").toLowerCase(), amount = Number(b.amount ?? 0), currency = str(b.currency || "BRL").toUpperCase(), productId = b.product_id ? String(b.product_id) : null, originalId = str(b.original_transaction_id ?? b.transaction_id), key = str(b.idempotency_key ?? req.headers.get("x-idempotency-key") ?? req.headers.get("idempotency-key")), metadata = rec(b.metadata) ? b.metadata : {}, customer = rec(b.customer) ? b.customer : {}, environment = str(b.environment ?? metadata.environment ?? "production").toLowerCase() === "sandbox" ? "sandbox" : "production";
  const tenantId = str(b.tenant_id);
  const action = op === "refund" ? "refund" : op === "capture" ? "capture" : op === "void" ? "void" : "purchase";
  if (!tenantId || tenantId !== user.id) return json({ ok: false, code: "TICKET_IDENTITY_MISMATCH", retryable: false }, 403);
  const feb = await validateFEB({ request: req, body: b, userId: user.id, tenantId, action });
  if (!feb.ok) return json({ ok: false, code: feb.code, retryable: feb.code === "TICKET_INVALID" ? false : false }, feb.status);
  const membership = await db.from("organization_members").select("organization_id").eq("user_id", user.id).eq("organization_id", tenantId).maybeSingle();
  if (membership.error && membership.error.code !== "PGRST116") return json({ ok: false, code: "EXECUTION_UNAVAILABLE", retryable: false }, 503);
  if (op === "refund" && !originalId) return json({ error: "original_transaction_id_required" }, 422);
  if (!fid || !Number.isFinite(amount) || amount <= 0 || !/^[A-Z]{3}$/.test(currency) || !key) return json({ error: "funnel_id_amount_currency_and_idempotency_key_required" }, 400);
  if (key.length > 200) return json({ error: "idempotency_key_too_long" }, 400);
  if (["card_data", "pan", "card_number", "cardNumber", "cvv", "cvc"].some((k) => b[k] !== undefined)) return json({ error: "raw_card_data_forbidden" }, 400);
  if (feb.claims.idempotencyKey !== key || feb.claims.executionId !== feb.claims.executionId) return json({ ok: false, code: "TICKET_COMMAND_MISMATCH", retryable: false }, 403);
  const digest = await sha256Hex(JSON.stringify({ fid, op, amount, currency, productId, originalId, metadata, customer, environment }));
  const reservation = await db.rpc("reserve_idempotency_key", { p_user_id: user.id, p_scope: `gateway-orchestrator:${fid}:${op}:${originalId || "new"}`, p_idempotency_key: key, p_request_digest: digest, p_ttl: "24 hours" });
  if (reservation.error) return json({ error: "idempotency_reservation_failed" }, 500); const lease = Array.isArray(reservation.data) ? reservation.data[0] : reservation.data; if (!rec(lease)) return json({ error: "idempotency_invalid_response" }, 500);
  if (lease.acquired !== true) { if (lease.response_payload) return json(lease.response_payload, Number(lease.response_code ?? 200)); return json({ error: "request_in_progress" }, 409); }
  const leaseId = String(lease.id ?? ""), leaseToken = lease.lease_token ? String(lease.lease_token) : null; let done = false;
  const consumed = await db.from("feb_consumed_tickets").insert({ jti: feb.claims.jti, execution_id: feb.claims.executionId, tenant_id: feb.claims.tenantId, user_id: feb.claims.userId, tool_key: feb.claims.toolKey, tool_version: feb.claims.toolVersion, gateway_id: feb.claims.gatewayId, action: feb.claims.action, idempotency_key: feb.claims.idempotencyKey, request_fingerprint: feb.claims.requestFingerprint, issuer: feb.claims.iss, audience: Array.isArray(feb.claims.aud) ? feb.claims.aud.join(" ") : feb.claims.aud, kid: feb.claims.kid, issued_at: new Date(Number(feb.claims.iat) * 1000).toISOString(), expires_at: new Date(Number(feb.claims.exp) * 1000).toISOString() });
  if (consumed.error) { await db.rpc("complete_idempotency_key", { p_id: leaseId, p_status: "failed", p_response_code: consumed.error.code === "23505" ? 409 : 500, p_response_payload: { ok: false, code: consumed.error.code === "23505" ? "TICKET_REPLAYED" : "EXECUTION_UNAVAILABLE", retryable: false }, p_resource_type: null, p_resource_id: null, p_lease_token: leaseToken }).catch(() => undefined); return json({ ok: false, code: consumed.error.code === "23505" ? "TICKET_REPLAYED" : "EXECUTION_UNAVAILABLE", retryable: false }, consumed.error.code === "23505" ? 409 : 503); }
  const finish = async (status: string, code: number, payload: unknown, type: string | null = null, id: string | null = null) => { if (!done && leaseId) { const r = await db.rpc("complete_idempotency_key", { p_id: leaseId, p_status: status, p_response_code: code, p_response_payload: payload, p_resource_type: type, p_resource_id: id, p_lease_token: leaseToken }); if (!r.error) done = true; } return json(payload, code); };
  try {
    if (op === "refund") {
      const q = await db.from("gateway_transactions").select("id,user_id,funnel_id,product_id,gateway_id,external_id,amount,currency,status,metadata,customer").eq("id", originalId).eq("user_id", user.id).maybeSingle(); if (q.error || !q.data) return finish("failed", 404, { error: "original_transaction_not_found" }); const tx = q.data;
      if (String(tx.funnel_id) !== fid) return finish("failed", 422, { error: "transaction_funnel_mismatch" }); if (String(tx.status) !== "approved") return finish("failed", 409, { error: "transaction_not_refundable", status: tx.status }); if (!tx.external_id) return finish("failed", 409, { error: "original_external_id_missing" });
      if (String(feb.claims.gatewayId) !== String(tx.gateway_id)) return finish("failed", 403, { ok: false, code: "TICKET_COMMAND_MISMATCH", retryable: false });
      const gq = await db.from("gateways").select("id,user_id,provider,display_name,environment,status,capabilities,circuit_id,credential_id").eq("id", tx.gateway_id).eq("user_id", user.id).maybeSingle(); if (gq.error || !gq.data) return finish("failed", 409, { error: "gateway_not_found" }); const g = gq.data as Gateway;
      const refundAmount = b.refund_amount === undefined ? Number(tx.amount) : Number(b.refund_amount); if (!Number.isFinite(refundAmount) || refundAmount <= 0 || refundAmount > Number(tx.amount)) return finish("failed", 422, { error: "invalid_refund_amount" });
      const old = await db.from("gateway_refunds").select("*").eq("user_id", user.id).eq("idempotency_key", key).maybeSingle(); if (old.data) return finish("completed", 200, { refund: old.data }, "gateway_refund", String(old.data.id));
      const sandbox = g.environment === "sandbox", credential = sandbox ? null : await resolveCredential(db, g.id); if (!sandbox && !credential) return finish("failed", 409, { error: "gateway_credential_not_bound" }); if (!sandbox && (await circuit(db, user.id, g)).allowed !== true) return finish("failed", 503, { error: "gateway_circuit_open" });
      const ledger = await db.from("gateway_refunds").insert({ user_id: user.id, transaction_id: tx.id, gateway_id: g.id, idempotency_key: key, amount: refundAmount, currency: tx.currency, status: "pending", metadata: { source: "gateway-orchestrator" } }).select().single(); if (ledger.error || !ledger.data) return finish("failed", 500, { error: "refund_ledger_create_failed" });
      const result = sandbox ? { ok: true, failure: null as Failure | null, reason: "sandbox_refund_approved", payload: { id: `sbx_refund_${tx.external_id}`, status: "approved" }, latencyMs: 1 } : await callAdapter(g, { operation: "refund", amount: refundAmount, currency: tx.currency, original_transaction_id: tx.id, original_external_id: tx.external_id, customer: tx.customer ?? {}, metadata, execution_id: feb.claims.executionId }, feb.claims.executionId, credential, internal, TIMEOUT);
      await health(db, g, result.failure === null || result.failure === "declined" || result.failure === "pending", result.latencyMs); if (!sandbox) await circuitResult(db, user.id, g, result.failure);
      const externalRefundId = result.payload.id ? String(result.payload.id) : result.payload.refund_id ? String(result.payload.refund_id) : null;
      if (!result.ok) { await db.from("gateway_refunds").update({ status: result.failure === "pending" ? "pending" : "failed", failure_code: result.failure, failure_message: result.reason, updated_at: new Date().toISOString() }).eq("id", ledger.data.id); return finish(result.failure === "pending" ? "completed" : "failed", result.failure === "pending" ? 202 : result.failure === "declined" ? 402 : 503, { error: "refund_failed", failure_class: result.failure, reason: result.reason, refund_id: ledger.data.id }, "gateway_refund", ledger.data.id); }
      const tr = await db.rpc("transition_gateway_transaction_status", { p_transaction_id: tx.id, p_user_id: user.id, p_next_status: refundAmount === Number(tx.amount) ? "refunded" : "approved", p_failure_code: null, p_external_id: String(tx.external_id) }); if (tr.error) return finish("failed", 500, { error: "refund_state_transition_failed" });
      await db.from("gateway_refunds").update({ status: "approved", external_refund_id: externalRefundId, completed_at: new Date().toISOString(), updated_at: new Date().toISOString() }).eq("id", ledger.data.id); if (refundAmount === Number(tx.amount)) await db.from("sales").update({ status: "refunded" }).eq("user_id", user.id).eq("transaction_id", tx.id);
      return finish("completed", 200, { refund: { ...ledger.data, status: "approved", external_refund_id: externalRefundId }, transaction: tr.data, sandbox }, "gateway_refund", ledger.data.id);
    }
    const f = await db.from("funnels").select("id").eq("id", fid).eq("user_id", user.id).is("deleted_at", null).maybeSingle(); if (!f.data) return finish("failed", 404, { error: "funnel_not_found" });
    const legacy = await db.from("gateway_routes").select("id,gateway_id,priority,enabled,fallback_enabled,conditions").eq("user_id", user.id).eq("funnel_id", fid).eq("enabled", true).order("priority", { ascending: true }); if (legacy.error) return finish("failed", 500, { error: "route_lookup_failed" });
    const legacyIds = (legacy.data ?? []).map((r) => String(r.gateway_id));
    const policyQ = await db.rpc("get_active_gateway_routing_policy", { p_user_id: user.id, p_funnel_id: fid }); if (policyQ.error) return finish("failed", 500, { error: "routing_policy_lookup_failed" });
    const policy = Array.isArray(policyQ.data) ? policyQ.data[0] : policyQ.data; let policyIds: string[] = []; let policyTrace: Record<string, unknown>[] = []; let policyMeta: Record<string, unknown> | null = null;
    if (rec(policy) && rec(policy.routing_graph)) { const validation = validateGraph(policy.routing_graph); if (!validation.ok) return finish("failed", 409, { error: "routing_policy_invalid", reason: validation.reason }); const decision = await resolvePolicyCandidates(policy.routing_graph, { amount, currency, funnel_id: fid, product_id: productId, customer, metadata, environment }, key); policyIds = decision.ids; policyTrace = decision.trace; policyMeta = { policy_id: String(policy.policy_id), policy_version: Number(policy.policy_version), decision_trace: policyTrace }; }
    const ids = Array.from(new Set([...policyIds, ...legacyIds])).slice(0, MAX_GATEWAYS); if (!ids.length) return finish("failed", 409, { error: "no_active_gateway_route" });
    const gq = await db.from("gateways").select("id,user_id,provider,display_name,environment,status,capabilities,circuit_id,credential_id").eq("user_id", user.id).in("id", ids); if (gq.error) return finish("failed", 500, { error: "gateway_lookup_failed" }); const gm = new Map((gq.data ?? []).map((g) => [String(g.id), g as Gateway]));
    const legacyMap = new Map((legacy.data ?? []).map((r) => [String(r.gateway_id), r])); const candidates: Candidate[] = ids.map((id) => { const gateway = gm.get(id); const route = legacyMap.get(id); return gateway ? { gateway, routeId: route ? String(route.id) : null, fallbackEnabled: route ? route.fallback_enabled !== false : true, source: policyIds.includes(id) ? "policy" : "legacy" } : null; }).filter((x): x is Candidate => x !== null).filter((x) => x.gateway.status !== "disabled" && x.gateway.environment === environment).slice(0, MAX_GATEWAYS);
    if (!candidates.length) return finish("failed", 409, { error: "no_eligible_gateway" });
    if (!candidates.some((candidate) => String(candidate.gateway.id) === String(feb.claims.gatewayId))) return finish("failed", 403, { ok: false, code: "TICKET_COMMAND_MISMATCH", retryable: false });
    const deadline = Date.now() + BUDGET, attempts: Record<string, unknown>[] = []; let finalTx: Record<string, unknown> | null = null; let lastFailure: Failure = "unknown";
    for (const candidate of candidates.filter((x) => String(x.gateway.id) === String(feb.claims.gatewayId))) {
      if (Date.now() + SAFETY >= deadline) { lastFailure = "timeout"; break; }
      const g = candidate.gateway; const sandbox = g.environment === "sandbox";
      if (!sandbox && (await circuit(db, user.id, g)).allowed !== true) { attempts.push({ gateway_id: g.id, provider: g.provider, source: candidate.source, outcome: "circuit_open", failure_class: "unavailable" }); lastFailure = "unavailable"; continue; }
      const credential = sandbox ? null : await resolveCredential(db, g.id); if (!sandbox && !credential) { attempts.push({ gateway_id: g.id, provider: g.provider, source: candidate.source, outcome: "credential_missing", failure_class: "unavailable" }); lastFailure = "unavailable"; continue; }
      const scenario = str(metadata.simulate_failure).toLowerCase(); let result: AdapterResult;
      if (sandbox) { result = scenario === "technical" ? { ok: false, failure: "technical", reason: "simulated_technical_failure", payload: {}, latencyMs: 1 } : scenario === "timeout" ? { ok: false, failure: "timeout", reason: "simulated_timeout", payload: {}, latencyMs: TIMEOUT } : scenario === "card_decline" ? { ok: false, failure: "declined", reason: "simulated_card_decline", payload: { status: "declined" }, latencyMs: 1 } : scenario === "pending" ? { ok: false, failure: "pending", reason: "sandbox_pending", payload: { status: "pending", id: `sbx_${crypto.randomUUID()}` }, latencyMs: 1 } : { ok: true, failure: null, reason: "sandbox_approved", payload: { status: "approved", id: `sbx_${crypto.randomUUID()}` }, latencyMs: 1 }; } else { result = await callAdapter(g, { operation: "create_payment", amount, currency, product_id: productId, funnel_id: fid, customer, payment_token: b.payment_token ?? b.vault_token ?? null, metadata, execution_id: feb.claims.executionId }, feb.claims.executionId, credential, internal, Math.min(TIMEOUT, Math.max(250, deadline - Date.now() - SAFETY))); }
      await health(db, g, result.failure === null || result.failure === "declined" || result.failure === "pending", result.latencyMs); if (!sandbox) await circuitResult(db, user.id, g, result.failure);
      const ext = result.payload.id ? String(result.payload.id) : result.payload.transaction_id ? String(result.payload.transaction_id) : null; const attemptOrder = attempts.length + 1; attempts.push({ gateway_id: g.id, provider: g.provider, source: candidate.source, outcome: result.ok ? "approved" : "failed", failure_class: result.failure ?? null, reason: result.reason, external_transaction_id: ext, latency_ms: result.latencyMs, policy: policyMeta });
      const created = await db.from("gateway_transactions").insert({ user_id: user.id, funnel_id: fid, product_id: productId, gateway_id: g.id, external_id: ext ?? feb.claims.executionId, idempotency_key: key, amount, currency, status: result.failure === "timeout" || result.failure === "technical" ? "pending" : result.ok ? "created" : "created", customer, metadata: { ...metadata, provider: g.provider, environment: g.environment, execution_id: feb.claims.executionId }, attempt_count: attemptOrder, routing_metadata: { source: candidate.source, route_id: candidate.routeId, ...policyMeta, attempts } }).select().single(); if (created.error || !created.data) return finish("failed", 500, { error: "transaction_create_failed" });
      await db.from("gateway_payment_attempts").insert({ user_id: user.id, sale_id: null, product_id: productId, gateway_id: g.id, gateway_name: g.provider, routing_rule_id: candidate.routeId, idempotency_key: feb.claims.executionId, attempt_order: attemptOrder, status: result.failure === "timeout" || result.failure === "technical" ? "unknown" : result.ok ? "approved" : result.failure === "declined" ? "declined" : result.failure === "pending" ? "pending" : "error", failure_class: result.failure ?? null, external_transaction_id: ext, error_message: result.ok ? null : result.reason, transaction_id: created.data.id, completed_at: result.ok || result.failure === "declined" ? new Date().toISOString() : null });
      if (result.failure === "timeout" || result.failure === "technical") { await db.from("gateway_recovery_queue").insert({ user_id: user.id, attempt_id: (await db.from("gateway_payment_attempts").select("id").eq("user_id", user.id).eq("transaction_id", created.data.id).eq("idempotency_key", feb.claims.executionId).order("created_at", { ascending: false }).limit(1).maybeSingle()).data?.id, transaction_id: created.data.id, gateway_id: g.id, provider: g.provider, idempotency_key: feb.claims.executionId, failure_class: result.failure, external_transaction_id: ext ?? feb.claims.executionId, status: "queued", next_retry_at: new Date(Date.now() + 90000).toISOString() }); return finish("failed", 202, { ok: false, code: "UNKNOWN_EXTERNAL_EFFECT", executionId: feb.claims.executionId, retryable: false, transactionId: created.data.id }, "gateway_transaction", String(created.data.id)); }
      const next = result.failure === "pending" ? "pending" : result.ok ? "approved" : "failed"; const tr = await db.rpc("transition_gateway_transaction_status", { p_transaction_id: created.data.id, p_user_id: user.id, p_next_status: next, p_failure_code: result.failure, p_external_id: ext }); if (tr.error) return finish("failed", 500, { error: "transaction_state_transition_failed" }, "gateway_transaction", String(created.data.id)); finalTx = tr.data as Record<string, unknown>; break;
    }
    await db.from("transaction_routing_logs").insert({ user_id: user.id, amount, currency, card_brand: String(metadata.card_brand ?? "unknown"), gateways_attempted: attempts, final_gateway: finalTx?.gateway_id ? String(finalTx.gateway_id) : null, status: finalTx ? String(finalTx.status) : "failed", failure_class: finalTx ? null : lastFailure, created_at: new Date().toISOString(), completed_at: new Date().toISOString(), idempotency_key: key });
    if (!finalTx) { const code = lastFailure === "declined" || lastFailure === "fraud" ? 402 : lastFailure === "timeout" ? 504 : 503; return finish("failed", code, { error: "payment_failed", failure_class: lastFailure, attempts, fallback_used: false, routing_policy: policyMeta }); }
    return finish("completed", 200, { transaction: finalTx, attempts, fallback_used: false, routing_policy: policyMeta, sandbox: gm.get(String(finalTx.gateway_id))?.environment === "sandbox" }, "gateway_transaction", String(finalTx.id));
  } catch (e) { return finish("failed", 500, { error: "orchestrator_unhandled_error", detail: e instanceof Error ? e.message : "unknown_error" }); }
  finally { if (!done && leaseId) await db.rpc("complete_idempotency_key", { p_id: leaseId, p_status: "failed", p_response_code: 500, p_response_payload: { error: "idempotency_aborted" }, p_resource_type: null, p_resource_id: null, p_lease_token: leaseToken }).catch(() => undefined); }
});
