export const FEB_ALGORITHM='RS256' as const
export const FEB_AUDIENCE='althea-pay-gateway-orchestrator' as const
export const FEB_ISSUER='althea-pay-iara-execution-kernel' as const
export type FebAction='purchase'|'capture'|'refund'|'void'
export type FebRiskClass='low'|'medium'|'high'|'critical'
export interface IaraFEBTicketClaims{jti:string;execution_id:string;tenant_id:string;user_id:string;tool_key:string;tool_version:number;risk_class:FebRiskClass;gateway_id:string;action:FebAction;request_fingerprint:string;iat:number;exp:number;aud:typeof FEB_AUDIENCE;iss:typeof FEB_ISSUER;kid:string}
export interface FebVerificationPolicy{clockSkewSeconds:number;maxTicketAgeSeconds:number;maxFreshnessSeconds:number;lastSuccessfulSyncEpochSeconds:number}
export interface FebVerificationContext{tenantId:string;userId:string;gatewayId:string;action:FebAction;toolKey:string;toolVersion:number;input:Record<string,unknown>}
export function canonicalize(value:unknown):string{if(value===null||typeof value!=='object')return JSON.stringify(value);if(Array.isArray(value))return`[${value.map(canonicalize).join(',')}]`;const o=value as Record<string,unknown>;return`{${Object.keys(o).sort().map(k=>`${JSON.stringify(k)}:${canonicalize(o[k])}`).join(',')}}`}
export async function sha256Hex(value:string):Promise<string>{const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return Array.from(new Uint8Array(d)).map(b=>b.toString(16).padStart(2,'0')).join('')}
export async function computeRequestFingerprint(input:FebVerificationContext):Promise<string>{return sha256Hex(canonicalize({tenant_id:input.tenantId,user_id:input.userId,tool_key:input.toolKey,tool_version:input.toolVersion,gateway_id:input.gatewayId,action:input.action,input:input.input}))}
function b64d(v:string):Uint8Array{const n=v.replace(/-/g,'+').replace(/_/g,'/')+'='.repeat((4-v.length%4)%4);const b=atob(n);return Uint8Array.from(b,c=>c.charCodeAt(0))}
export function parseJwt(token:string){const p=token.split('.');if(p.length!==3)throw new Error('TICKET_INVALID');return{header:JSON.parse(new TextDecoder().decode(b64d(p[0]))) as Record<string,unknown>,claims:JSON.parse(new TextDecoder().decode(b64d(p[1]))) as Record<string,unknown>,signingInput:`${p[0]}.${p[1]}`,signature:b64d(p[2])}}
export async function verifySignature(token:string,jwk:JsonWebKey):Promise<void>{const p=parseJwt(token);if(p.header.alg!==FEB_ALGORITHM)throw new Error('TICKET_INVALID');const key=await crypto.subtle.importKey('jwk',jwk,{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['verify']);if(!(await crypto.subtle.verify({name:'RSASSA-PKCS1-v1_5'},key,p.signature,new TextEncoder().encode(p.signingInput))))throw new Error('TICKET_INVALID')}
export function decodeClaims(token:string):IaraFEBTicketClaims{const {claims}=parseJwt(token);for(const k of ['jti','execution_id','tenant_id','user_id','tool_key','tool_version','risk_class','gateway_id','action','request_fingerprint','iat','exp','aud','iss','kid'])if(claims[k]===undefined||claims[k]===null)throw new Error('TICKET_INVALID');if(claims.aud!==FEB_AUDIENCE||claims.iss!==FEB_ISSUER)throw new Error('TICKET_INVALID');return claims as unknown as IaraFEBTicketClaims}
export async function verifyTemporalAndCommand(token:string,context:FebVerificationContext,now:number,policy:FebVerificationPolicy):Promise<IaraFEBTicketClaims>{const c=decodeClaims(token);if(c.iat>now+policy.clockSkewSeconds)throw new Error('TICKET_INVALID');const expiry=Math.min(c.exp,c.iat+policy.maxTicketAgeSeconds);if(now>=expiry||now-c.iat>policy.maxTicketAgeSeconds)throw new Error('TICKET_EXPIRED');if(now-policy.lastSuccessfulSyncEpochSeconds>policy.maxFreshnessSeconds)throw new Error('EXECUTION_UNAVAILABLE');if(c.tenant_id!==context.tenantId||c.user_id!==context.userId)throw new Error('TICKET_IDENTITY_MISMATCH');if(c.gateway_id!==context.gatewayId||c.action!==context.action||c.tool_version!==context.toolVersion||c.tool_key!==context.toolKey)throw new Error('TICKET_COMMAND_MISMATCH');if(await computeRequestFingerprint(context)!==c.request_fingerprint)throw new Error('TICKET_COMMAND_MISMATCH');return c}
