import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
const json=(b:unknown,s=200)=>Response.json(b,{status:s,headers:{"Content-Type":"application/json"}});
Deno.serve(async req=>{
 if(req.method!=="POST")return json({error:"method_not_allowed"},405);const internal=Deno.env.get("ALTHEA_INTERNAL_SECRET")||"";if(!internal||req.headers.get("x-internal-secret")!==internal)return json({error:"unauthorized"},401);const url=Deno.env.get("SUPABASE_URL"),service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!url||!service)return json({error:"server_configuration_error"},500);const db=createClient(url,service);let b:any={};try{b=await req.json()}catch{}
 const start=b.period_start?new Date(b.period_start).toISOString():new Date(Date.now()-86400000).toISOString(),end=b.period_end?new Date(b.period_end).toISOString():new Date().toISOString();const {data:gateways,error}=await db.from("gateways").select("id,name,provider,environment,env,user_id");if(error)return json({error:"gateway_lookup_failed",detail:error.message},500);let processed=0,updated=0,failed=0;const runs=[];
 for(const g of gateways??[]){const provider=String(g.provider??g.name??"unknown").toLowerCase(),key=provider.replace(/[^a-z0-9]/gi,"_").toUpperCase(),endpoint=Deno.env.get(`GATEWAY_RECONCILIATION_URL_${key}`)??(Deno.env.get("GATEWAY_RECONCILIATION_BASE_URL")?.replace(/\/$/,"")+`/reconciliation/${encodeURIComponent(provider)}`);if(!endpoint){failed++;continue}const {data:run,error:re}=await db.from("reconciliation_runs").insert({user_id:g.user_id,gateway_id:g.id,period_start:start,period_end:end,status:"running",source_type:"gateway_api",source_reference:provider,started_at:new Date().toISOString()}).select().single();if(re){failed++;continue}runs.push(run.id);
  try{const r=await fetch(endpoint,{method:"POST",headers:{"content-type":"application/json","x-althea-gateway-id":g.id,"x-althea-user-id":g.user_id,"x-period-start":start,"x-period-end":end},body:JSON.stringify({gateway_id:g.id,user_id:g.user_id,period_start:start,period_end:end})});if(!r.ok)throw new Error(`gateway_http_${r.status}`);const payload:any=await r.json();const rows=Array.isArray(payload?.transactions)?payload.transactions:Array.isArray(payload)?payload:[];let matched=0,mismatch=0,grossExpected=0,grossReported=0;
   for(const row of rows){processed++;const external=String(row.external_transaction_id??row.transaction_id??row.external_id??""),reported=Number(row.amount??row.gross??0),remoteStatus=String(row.status??"").toLowerCase();let q=db.from("gateway_transactions").select("id,amount,external_id,status").eq("user_id",g.user_id).eq("gateway_id",g.id).limit(1);if(external)q=q.eq("external_id",external);const {data:tx,error:tErr}=await q.maybeSingle();if(tErr)throw tErr;if(tx){const expected=Number(tx.amount);grossExpected+=expected;grossReported+=reported;const diff=Math.round((expected-reported)*100)/100,st=Math.abs(diff)<0.01?"matched":"amount_mismatch";if(st==="matched")matched++;else mismatch++;await db.from("reconciliation_items").insert({user_id:g.user_id,run_id:run.id,transaction_id:tx.id,external_transaction_id:external||tx.external_id,status:st,expected_amount:expected,reported_amount:reported,discrepancy_amount:diff,mismatch_reason:st==="matched"?null:"amount_difference",gateway_payload:row});
     if(["chargeback","charged_back","refunded","refund","reversed"].includes(remoteStatus)){const ns=remoteStatus==="chargeback"||remoteStatus==="charged_back"?"chargeback":"refunded";const {error:transitionError}=await db.rpc("transition_gateway_transaction_status",{p_transaction_id:tx.id,p_user_id:g.user_id,p_new_status:ns,p_error_message:null,p_external_status:remoteStatus});if(transitionError)throw transitionError;await db.from("sales").update({status:ns,data:row}).eq("user_id",g.user_id).eq("transaction_id",tx.id);updated++}
     else if(["paid","approved","completed","success"].includes(remoteStatus)&&tx.status!=="approved"){const {error:transitionError}=await db.rpc("transition_gateway_transaction_status",{p_transaction_id:tx.id,p_user_id:g.user_id,p_new_status:"approved",p_error_message:null,p_external_status:remoteStatus});if(transitionError)throw transitionError;updated++}
   }else{mismatch++;await db.from("reconciliation_items").insert({user_id:g.user_id,run_id:run.id,external_transaction_id:external||null,status:"missing_internal",reported_amount:reported,discrepancy_amount:reported,mismatch_reason:"transaction_not_found",gateway_payload:row})}}
   await db.from("reconciliation_runs").update({status:"completed",matched_count:matched,mismatch_count:mismatch,gross_expected:grossExpected,gross_reported:grossReported,discrepancy_amount:Math.round((grossExpected-grossReported)*100)/100,completed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",run.id)
  }catch(e){failed++;await db.from("reconciliation_runs").update({status:"failed",error_message:e instanceof Error?e.message:String(e),completed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",run.id)}}return json({ok:true,period_start:start,period_end:end,gateways_scanned:(gateways??[]).length,runs,transactions_processed:processed,records_updated:updated,failed_gateways:failed});
});