import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
const supabaseUrl=Deno.env.get("SUPABASE_URL")!;const serviceRoleKey=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;const db=createClient(supabaseUrl,serviceRoleKey);
const json=(x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{"content-type":"application/json"}});
type Outbox={id:string;user_id:string;conversation_id:string|null;channel_account_id:string|null;channel:string;body:string;status:string;attempts:number;max_attempts:number;metadata:Record<string,unknown>|null};
type Account={id:string;user_id:string;channel:string;provider:string;external_account_id:string|null;status:string;credentials_ref:string|null;metadata:Record<string,unknown>|null};
type Identity={external_user_id:string|null;phone_e164:string|null;email:string|null;display_name:string|null;metadata:Record<string,unknown>|null};
type ProviderHttpError=Error&{statusCode:number};
function credentials(a:Account){if(!a.credentials_ref)return{};const raw=Deno.env.get(a.credentials_ref);if(!raw)throw Error("provider_credentials_not_configured");try{return JSON.parse(raw)}catch{return{access_token:raw}}}
function meta(a:Account,k:string,f?:unknown){return(a.metadata??{})[k]??f}
function backoff(n:number){return Math.min(3600,Math.max(10,2**Math.min(n,10)*5))}
function providerHttpError(statusCode:number):ProviderHttpError{const e=new Error(`provider_http_${statusCode}`) as ProviderHttpError;e.statusCode=statusCode;return e}
function isRetryableProviderStatus(statusCode:number){return statusCode===408||statusCode===409||statusCode===425||statusCode===429||statusCode>=500}
function isValidExternalId(value:unknown):value is string{return typeof value==="string"&&value.trim().length>0}
async function responseJson(r:Response){const text=await r.text();let d:any={};try{d=text?JSON.parse(text):{}}catch{d={}}if(!r.ok)throw providerHttpError(r.status);return d}
async function sendMeta(a:Account,i:Identity,b:string){const c=credentials(a),token=c.access_token||c.token;if(!token)throw Error("meta_access_token_missing");const base=`https://graph.facebook.com/${String(meta(a,"graph_version","v23.0"))}`;if(a.channel==="whatsapp"){const id=String(meta(a,"phone_number_id",a.external_account_id||"")),to=i.phone_e164||i.external_user_id;if(!id||!to)throw Error("whatsapp_destination_missing");const r=await fetch(`${base}/${id}/messages`,{method:"POST",headers:{authorization:`Bearer ${token}`,"content-type":"application/json"},body:JSON.stringify({messaging_product:"whatsapp",recipient_type:"individual",to,type:"text",text:{preview_url:false,body:b}})});const d=await responseJson(r);return String(d.messages?.[0]?.id||d.message_id||"")}const page=String(meta(a,"page_id",a.external_account_id||"")),to=i.external_user_id;if(!page||!to)throw Error(`${a.channel}_destination_missing`);const r=await fetch(`${base}/${page}/messages`,{method:"POST",headers:{authorization:`Bearer ${token}`,"content-type":"application/json"},body:JSON.stringify({recipient:{id:to},message:{text:b}})});const d=await responseJson(r);return String(d.message_id||d.id||"")}
async function sendResend(a:Account,i:Identity,b:string){const c=credentials(a),token=c.api_key||c.access_token||c.token,from=String(meta(a,"from_email",c.from||"")),to=i.email;if(!token||!from||!to)throw Error("email_configuration_missing");const r=await fetch("https://api.resend.com/emails",{method:"POST",headers:{authorization:`Bearer ${token}`,"content-type":"application/json"},body:JSON.stringify({from,to:[to],subject:String(meta(a,"subject","Mensagem da Althea Pay")),text:b})});const d=await responseJson(r);return String(d.id||"")}
async function sendTwilio(a:Account,i:Identity,b:string){const c=credentials(a),sid=String(c.account_sid||a.external_account_id||""),auth=String(c.auth_token||""),from=String(meta(a,"from_number",c.from||"")),to=i.phone_e164;if(!sid||!auth||!from||!to)throw Error("twilio_configuration_missing");const r=await fetch(`https://api.twilio.com/2010-04-01/Accounts/${sid}/Messages.json`,{method:"POST",headers:{authorization:`Basic ${btoa(`${sid}:${auth}`)},"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({To:to,From:from,Body:b})});const d=await responseJson(r);return String(d.sid||"")}
async function deliver(row:Outbox,a:Account|null,i:Identity|null){if(row.channel==="funnel_chat"){if(!row.conversation_id)throw Error("conversation_id_required");const{data,error}=await db.from("crm_messages").insert({conversation_id:row.conversation_id,user_id:row.user_id,direction:"outbound",channel:"funnel_chat",body:row.body,metadata:{...(row.metadata??{}),outbox_id:row.id,dispatcher:"crm-channel-outbox-dispatcher"}}).select("id").single();if(error)throw error;return String(data.id)}if(!a||a.status!=="active")throw Error("channel_account_not_active");if(!i)throw Error("channel_identity_not_found");const p=a.provider.toLowerCase();if(["meta_whatsapp","whatsapp_cloud","meta_instagram","instagram","meta_messenger","messenger"].includes(p))return sendMeta(a,i,row.body);if(["resend","email_resend"].includes(p))return sendResend(a,i,row.body);if(["twilio","sms_twilio"].includes(p))return sendTwilio(a,i,row.body);throw Error(`unsupported_channel_provider:${a.provider}`)}
Deno.serve(async req=>{if(req.method!=="POST")return json({error:"method_not_allowed"},405);const internal=Deno.env.get("ALTHEA_INTERNAL_SECRET")||"";if(!internal||req.headers.get("x-internal-secret")!==internal)return json({error:"unauthorized"},401);try{const body=await req.json().catch(()=>({}));const limit=Math.max(1,Math.min(Number(body.limit||25),100));await db.rpc("crm_requeue_stale_channel_outbox",{p_age_minutes:15});const{data:rows,error}=await db.rpc("crm_claim_channel_outbox_worker",{p_limit:limit});if(error)throw error;const results:any[]=[];for(const row of(rows||[])as Outbox[]){try{let a:Account|null=null,i:Identity|null=null;if(row.channel_account_id){const r=await db.from("crm_channel_accounts").select("id,user_id,channel,provider,external_account_id,status,credentials_ref,metadata").eq("id",row.channel_account_id).eq("user_id",row.user_id).maybeSingle();if(r.error)throw r.error;a=r.data as Account|null}if(row.conversation_id&&row.channel!=="funnel_chat"){const r=await db.from("crm_channel_identities").select("external_user_id,phone_e164,email,display_name,metadata").eq("conversation_id",row.conversation_id).eq("user_id",row.user_id).eq("channel",row.channel).order("updated_at",{ascending:false}).limit(1).maybeSingle();if(r.error)throw r.error;i=r.data as Identity|null}
const externalId=await deliver(row,a,i);
if(row.channel!=="funnel_chat"&&!isValidExternalId(externalId))throw Error("missing_provider_external_id");
const now=new Date().toISOString();await db.from("crm_channel_message_outbox").update({status:"sent",external_message_id:isValidExternalId(externalId)?externalId:null,sent_at:now,updated_at:now,last_error:null}).eq("id",row.id);if(row.channel!=="funnel_chat"&&row.conversation_id)await db.from("crm_messages").insert({conversation_id:row.conversation_id,user_id:row.user_id,direction:"outbound",channel:row.channel,body:row.body,metadata:{...(row.metadata??{}),outbox_id:row.id,external_message_id:externalId,provider:a?.provider??null}});results.push({id:row.id,status:"sent",external_message_id:isValidExternalId(externalId)?externalId:null})
}catch(e){const message=e instanceof Error?e.message:String(e);const statusCode=typeof e==="object"&&e!==null&&"statusCode" in e?Number((e as{statusCode?:unknown}).statusCode):0;const retryable=statusCode>0?isRetryableProviderStatus(statusCode):!(["provider_credentials_not_configured","channel_account_not_active","channel_identity_not_found","missing_provider_external_id","meta_access_token_missing","whatsapp_destination_missing","instagram_destination_missing","messenger_destination_missing","email_configuration_missing","twilio_configuration_missing","conversation_id_required"].includes(message)||message.startsWith("unsupported_channel_provider:"));const terminal=!retryable||row.attempts+1>=row.max_attempts;const nextAttempt=row.attempts+1;const safeError=statusCode>0?`provider_http_${statusCode}`:message;await db.from("crm_channel_message_outbox").update({status:terminal?"dead_letter":"queued",next_attempt_at:terminal?null:new Date(Date.now()+backoff(nextAttempt)*1000).toISOString(),failed_at:new Date().toISOString(),last_error:safeError,updated_at:new Date().toISOString()}).eq("id",row.id);results.push({id:row.id,status:terminal?"dead_letter":"retry_scheduled",error:safeError,error_classification:terminal?"DLQ":"RETRY"})}}return json({ok:true,claimed:(rows||[]).length,results})}catch(e){return json({ok:false,error:e instanceof Error?e.message:String(e)},500)}});
