import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

const url = Deno.env.get("SUPABASE_URL")!;
const serviceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const db = createClient(url, serviceKey);
const json = (x: unknown, status=200) => new Response(JSON.stringify(x), {status, headers:{"content-type":"application/json"}});
type Account={id:string;user_id:string;channel:string;provider:string;external_account_id:string|null;status:string;credentials_ref:string|null;metadata:Record<string,unknown>};
function creds(a:Account){if(!a.credentials_ref)return {};const raw=Deno.env.get(a.credentials_ref);if(!raw)throw new Error("provider_credentials_not_configured");try{return JSON.parse(raw)}catch{return {access_token:raw}}}
function meta(a:Account,k:string){return (a.metadata??{})[k]}
async function hmacHex(secret:string,body:string){const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);const sig=await crypto.subtle.sign("HMAC",key,new TextEncoder().encode(body));return [...new Uint8Array(sig)].map(b=>b.toString(16).padStart(2,"0")).join("")}
function safeEqual(a:string,b:string){if(a.length!==b.length)return false;let x=0;for(let i=0;i<a.length;i++)x|=a.charCodeAt(i)^b.charCodeAt(i);return x===0}
async function accountFor(channel:string,externalId:string,phoneId?:string){let q=db.from("crm_channel_accounts").select("id,user_id,channel,provider,external_account_id,status,credentials_ref,metadata").eq("channel",channel).eq("status","active");if(phoneId)q=q.eq("metadata->>phone_number_id",phoneId);else q=q.eq("external_account_id",externalId);const {data,error}=await q.limit(1).maybeSingle();if(error)throw error;return data as Account|null}
async function ingest(a:Account,externalUser:string,body:string,externalMessageId:string,phone?:string,email?:string,name?:string,metadata:Record<string,unknown>={}){return db.rpc("crm_ingest_channel_message",{p_user_id:a.user_id,p_channel:a.channel,p_channel_account_id:a.id,p_external_user_id:externalUser,p_body:body,p_external_message_id:externalMessageId,p_phone_e164:phone??null,p_email:email??null,p_display_name:name??null,p_metadata:{...metadata,provider:a.provider}})}
async function verifyMeta(body:string,a:Account|null,signature:string|null){if(!a||!signature)return false;const c=creds(a);const secret=String(c.app_secret||c.client_secret||meta(a,"app_secret")||"");if(!secret)return false;const expected="sha256="+(await hmacHex(secret,body));return safeEqual(expected,signature)}
Deno.serve(async req=>{try{if(req.method==="GET"){const u=new URL(req.url);const mode=u.searchParams.get("hub.mode");const token=u.searchParams.get("hub.verify_token");const challenge=u.searchParams.get("hub.challenge");if(mode!=="subscribe"||!token||!challenge)return json({error:"invalid_verification"},403);const verify=Deno.env.get("META_WEBHOOK_VERIFY_TOKEN")||"";if(!verify||token!==verify)return json({error:"invalid_verify_token"},403);return new Response(challenge,{status:200,headers:{"content-type":"text/plain"}})}if(req.method!=="POST")return json({error:"method_not_allowed"},405);const raw=await req.text();const payload=JSON.parse(raw);const signature=req.headers.get("x-hub-signature-256");const object=String(payload.object||"");const channel=object==="whatsapp_business_account"?"whatsapp":object==="instagram"?"instagram":object==="page"?"messenger":"";if(!channel)return json({ok:true,ignored:true,reason:"unsupported_object"});const results:any[]=[];for(const entry of(payload.entry||[])){const externalAccountId=String(entry.id||"");let account=await accountFor(channel,externalAccountId);if(channel==="whatsapp"){for(const change of(entry.changes||[])){const value=change.value||{};const phoneId=String(value.metadata?.phone_number_id||"");if(phoneId)account=await accountFor(channel,externalAccountId,phoneId)||account;if(!account)continue;if(!(await verifyMeta(raw,account,signature)))return json({error:"invalid_signature"},401);for(const m of(value.messages||[])){const text=String(m.text?.body||m.button?.text||m.interactive?.button_reply?.title||"");if(!text)continue;const contact=(value.contacts||[]).find((c:any)=>String(c.wa_id||"")===String(m.from||""));const r=await ingest(account,String(m.from),text,String(m.id),undefined,undefined,contact?.profile?.name,{provider_event:"meta_whatsapp",message_type:m.type,phone_number_id:phoneId});if(r.error)throw r.error;results.push(r.data)}}}else{if(!account)continue;if(!(await verifyMeta(raw,account,signature)))return json({error:"invalid_signature"},401);for(const event of(entry.messaging||[])){const text=String(event.message?.text||"");const mid=String(event.message?.mid||"");const sender=String(event.sender?.id||"");if(!text||!mid||!sender)continue;const r=await ingest(account,sender,text,mid,undefined,undefined,undefined,{provider_event:`meta_${channel}`});if(r.error)throw r.error;results.push(r.data)}}}return json({ok:true,processed:results.length,results})}catch(e){return json({ok:false,error:e instanceof Error?e.message:String(e)},500)}});
