import { randomUUID } from 'node:crypto'
import { Pool, type PoolClient } from 'pg'
import { EventEmitter } from 'node:events'

export enum MemoryEventType {
  CONTEXT_MUTATION = 'CONTEXT_MUTATION',
  CHAT_APPEND = 'CHAT_APPEND',
  CRM_TOOL_SNAPSHOT = 'CRM_TOOL_SNAPSHOT',
}

export type JsonPrimitive = string | number | boolean | null
type JsonValue = JsonPrimitive | JsonValue[] | { [key: string]: JsonValue }
export interface MemoryJournalEntry<TPayload extends JsonValue = JsonValue> { id:string;tenantId:string;userId:string;productId:string|null;sessionId:string|null;conversationId:string|null;executionId:string|null;idempotencyKey:string|null;type:MemoryEventType;entityType:string|null;entityId:string|null;payload:TPayload;metadata:Record<string,JsonValue>;sequenceId:number;timestamp:string }
export interface BrainSnapshot { lastActiveProductId:string|null;conversationMessages:Array<{role:'user'|'iara';text:string}>;injectedCrmHooksCount:number }
interface AppendJournalInput<TPayload extends JsonValue>{tenantId:string;userId:string;productId?:string|null;sessionId?:string|null;conversationId?:string|null;executionId?:string|null;idempotencyKey?:string|null;type:MemoryEventType;entityType?:string|null;entityId?:string|null;payload:TPayload;metadata?:Record<string,JsonValue>}
interface JournalRow{id:string;tenant_id:string;user_id:string;product_id:string|null;session_id:string|null;conversation_id:string|null;execution_id:string|null;idempotency_key:string|null;event_type:MemoryEventType;entity_type:string|null;entity_id:string|null;payload:JsonValue;metadata:Record<string,JsonValue>;sequence_id:string;created_at:Date|string}
interface SnapshotRow{sequence_id:string;state:BrainSnapshot}
const MAX_RETRY_ATTEMPTS=5
const LOCK_TTL_SECONDS=15
const LOCK_WAIT_TIMEOUT_MS=8_000
const LOCK_POLL_BASE_MS=20
const SNAPSHOT_VERSION=1
const sleep=(ms:number)=>new Promise<void>(resolve=>setTimeout(resolve,ms))
const isJsonObject=(value:unknown):value is Record<string,JsonValue>=>typeof value==='object'&&value!==null&&!Array.isArray(value)
const isTransientUniqueViolation=(error:unknown)=>{if(!isJsonObject(error))return false;return error.code==='23505'&&error.constraint==='iara_memory_journal_tenant_sequence_unique'}
const isIdempotencyViolation=(error:unknown)=>{if(!isJsonObject(error))return false;return error.code==='23505'&&error.constraint==='iara_memory_journal_idempotency_unique'}
export class AltheaPersistentMemoryEngine{
 private readonly pg:Pool;private readonly eventEmitter:EventEmitter;private readonly redisUrl:string;private readonly redisToken:string
 constructor(eventEmitter=new EventEmitter()){const databaseUrl=process.env.DATABASE_URL;const redisUrl=process.env.ALTHEA_REDIS_REST_URL;const redisToken=process.env.ALTHEA_REDIS_REST_TOKEN;if(!databaseUrl)throw new Error('DATABASE_URL não configurada para o motor de memória persistente da IARA.');if(!redisUrl||!redisToken)throw new Error('ALTHEA_REDIS_REST_URL e ALTHEA_REDIS_REST_TOKEN são obrigatórios para o lock distribuído da IARA.');this.pg=new Pool({connectionString:databaseUrl,max:10,idleTimeoutMillis:30_000,connectionTimeoutMillis:5_000,maxUses:5_000});this.eventEmitter=eventEmitter;this.redisUrl=redisUrl.replace(/\/$/,'');this.redisToken=redisToken}
 private async redisCommand<T>(command:string[]):Promise<T|null>{const response=await fetch(this.redisUrl,{method:'POST',headers:{Authorization:`Bearer ${this.redisToken}`,'Content-Type':'application/json'},body:JSON.stringify(command),cache:'no-store'});if(!response.ok)throw new Error(`Redis REST respondeu HTTP ${response.status}.`);const body=await response.json() as {result?:T;error?:string};if(body.error)throw new Error(`Redis: ${body.error}`);return body.result??null}
 private async acquireLock(tenantId:string){const key=`lock:iara:memory:${tenantId}`;const token=randomUUID();const deadline=Date.now()+LOCK_WAIT_TIMEOUT_MS;while(Date.now()<deadline){const result=await this.redisCommand<string|null>(['SET',key,token,'NX','EX',String(LOCK_TTL_SECONDS)]);if(result==='OK')return{key,token};await sleep(LOCK_POLL_BASE_MS)}throw new Error('LOCK_TIMEOUT: não foi possível adquirir o lock distribuído da memória da IARA.')}
 private async releaseLock(lock:{key:string;token:string}){await this.redisCommand<number>(['EVAL',"if redis.call('GET', KEYS[1]) == ARGV[1] then return redis.call('DEL', KEYS[1]) else return 0 end",'1',lock.key,lock.token])}
 private rowToEntry(row:JournalRow):MemoryJournalEntry{return{id:row.id,tenantId:row.tenant_id,userId:row.user_id,productId:row.product_id,sessionId:row.session_id,conversationId:row.conversation_id,executionId:row.execution_id,idempotencyKey:row.idempotency_key,type:row.event_type,entityType:row.entity_type,entityId:row.entity_id,payload:row.payload,metadata:row.metadata,sequenceId:Number(row.sequence_id),timestamp:new Date(row.created_at).toISOString()}}
 private async findByIdempotency(client:PoolClient,tenantId:string,idempotencyKey:string){const result=await client.query<JournalRow>(`SELECT id, tenant_id, user_id, product_id, session_id, conversation_id, execution_id, idempotency_key, event_type, entity_type, entity_id, payload, metadata, sequence_id, created_at FROM public.iara_memory_journal WHERE tenant_id = $1 AND idempotency_key = $2 LIMIT 1`,[tenantId,idempotencyKey]);return result.rows[0]?this.rowToEntry(result.rows[0]):null}
 public async appendJournal<TPayload extends JsonValue>(input:AppendJournalInput<TPayload>,attempt=0):Promise<MemoryJournalEntry<TPayload>>{const lock=await this.acquireLock(input.tenantId);let client:PoolClient|null=null;try{client=await this.pg.connect();await client.query('BEGIN');await client.query('SELECT pg_advisory_xact_lock(hashtextextended($1, 0))',[input.tenantId]);if(input.idempotencyKey){const existing=await this.findByIdempotency(client,input.tenantId,input.idempotencyKey);if(existing){await client.query('COMMIT');return existing as MemoryJournalEntry<TPayload>}}const sequenceResult=await client.query<{next_sequence:string}>(`SELECT COALESCE(MAX(sequence_id), 0) + 1 AS next_sequence FROM public.iara_memory_journal WHERE tenant_id = $1`,[input.tenantId]);const sequenceId=Number(sequenceResult.rows[0]?.next_sequence??1);const id=randomUUID();const inserted=await client.query<JournalRow>(`INSERT INTO public.iara_memory_journal (id, tenant_id, user_id, product_id, session_id, conversation_id, execution_id, idempotency_key, event_type, entity_type, entity_id, payload, metadata, sequence_id) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12::jsonb,$13::jsonb,$14) RETURNING id, tenant_id, user_id, product_id, session_id, conversation_id, execution_id, idempotency_key, event_type, entity_type, entity_id, payload, metadata, sequence_id, created_at`,[id,input.tenantId,input.userId,input.productId??null,input.sessionId??null,input.conversationId??null,input.executionId??null,input.idempotencyKey??null,input.type,input.entityType??null,input.entityId??null,JSON.stringify(input.payload),JSON.stringify(input.metadata??{}),sequenceId]);await client.query('COMMIT');const entry=this.rowToEntry(inserted.rows[0]) as MemoryJournalEntry<TPayload>;this.eventEmitter.emit('ia_journal_committed',entry);return entry}catch(error:unknown){if(client){try{await client.query('ROLLBACK')}catch{}}if(isIdempotencyViolation(error)&&input.idempotencyKey){const existingClient=await this.pg.connect();try{const existing=await this.findByIdempotency(existingClient,input.tenantId,input.idempotencyKey);if(existing)return existing as MemoryJournalEntry<TPayload>}finally{existingClient.release()}}if(isTransientUniqueViolation(error)&&attempt<MAX_RETRY_ATTEMPTS){const retryDelay=Math.min(80*2**attempt,2_000);await sleep(retryDelay);return this.appendJournal(input,attempt+1)}const message=error instanceof Error?error.message:'Falha desconhecida de persistência.';console.error(`[IARA_MEMORY_PERSISTENCE] ${message}`);throw error}finally{client?.release();await this.releaseLock(lock)}}
 public async reconstructBrainState(tenantId:string):Promise<BrainSnapshot>{const fallback:BrainSnapshot={lastActiveProductId:null,conversationMessages:[],injectedCrmHooksCount:0};const client=await this.pg.connect();try{const snapshotResult=await client.query<SnapshotRow>(`SELECT sequence_id, state FROM public.iara_memory_snapshots WHERE tenant_id = $1 ORDER BY sequence_id DESC LIMIT 1`,[tenantId]);const snapshot=snapshotResult.rows[0];const state:BrainSnapshot=snapshot?.state??fallback;const afterSequence=snapshot?Number(snapshot.sequence_id):0;const journal=await client.query<JournalRow>(`SELECT id, tenant_id, user_id, product_id, session_id, conversation_id, execution_id, idempotency_key, event_type, entity_type, entity_id, payload, metadata, sequence_id, created_at FROM public.iara_memory_journal WHERE tenant_id = $1 AND sequence_id > $2 ORDER BY sequence_id ASC`,[tenantId,afterSequence]);for(const row of journal.rows){const payload=row.payload;if(row.event_type===MemoryEventType.CONTEXT_MUTATION&&row.product_id)state.lastActiveProductId=row.product_id;if(row.event_type===MemoryEventType.CHAT_APPEND&&isJsonObject(payload)){const role=payload.role;const text=payload.text;if((role==='user'||role==='iara')&&typeof text==='string'&&text.trim())state.conversationMessages.push({role,text})}if(row.event_type===MemoryEventType.CRM_TOOL_SNAPSHOT&&isJsonObject(payload)&&payload.status==='SUCCESS')state.injectedCrmHooksCount+=1}return state}catch(error){console.error('[IARA_MEMORY_REPLAY] Falha ao reconstruir estado persistido:',error);return fallback}finally{client.release()}}
 public async createSnapshot(tenantId:string,state:BrainSnapshot):Promise<void>{const client=await this.pg.connect();try{await client.query('BEGIN');await client.query('SELECT pg_advisory_xact_lock(hashtextextended($1, 0))',[tenantId]);const latest=await client.query<{sequence_id:string}>(`SELECT COALESCE(MAX(sequence_id), 0) AS sequence_id FROM public.iara_memory_journal WHERE tenant_id = $1`,[tenantId]);const sequenceId=Number(latest.rows[0]?.sequence_id??0);if(sequenceId>0)await client.query(`INSERT INTO public.iara_memory_snapshots (tenant_id, sequence_id, state, state_version) VALUES ($1,$2,$3::jsonb,$4) ON CONFLICT (tenant_id, sequence_id) DO UPDATE SET state = EXCLUDED.state, state_version = EXCLUDED.state_version`,[tenantId,sequenceId,JSON.stringify(state),SNAPSHOT_VERSION]);await client.query('COMMIT')}catch(error){try{await client.query('ROLLBACK')}catch{}throw error}finally{client.release()}}
 public async close():Promise<void>{await this.pg.end()}
}
