'use client'

import { useCallback, useEffect, useMemo, useState } from 'react'
import { BarChart3, CalendarDays, ChevronLeft, ChevronRight, CreditCard, GitBranch, LayoutDashboard, Network, RefreshCw, Settings, X } from 'lucide-react'
import { createSupabaseBrowserClient } from '@/lib/supabase/client'

type Range={start:string;end:string}
type Sale={id:string;amount:number|string|null;currency?:string|null;status?:string|null;data?:any;source?:string|null;medium?:string|null;campaign?:string|null;gateway_id?:string|null;external_id?:string|null;transaction_id?:string|null;occurred_at?:string|null;created_at?:string|null}
type Gateway={id:string;data?:any}
type Dispute={id:string;amount?:number|string|null;status?:string|null;created_at?:string|null}
type Health={gateway_id?:string|null;gateway_name?:string|null;is_healthy?:boolean|null;latency_ms?:number|null;circuit_state?:string|null;checked_at?:string|null}
const TZ='America/Sao_Paulo',pad=(n:number)=>String(n).padStart(2,'0'),parse=(v:string)=>{const[y,m,d]=v.split('-').map(Number);return new Date(y,m-1,d)},iso=(d:Date)=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`,add=(v:string,n:number)=>{const d=parse(v);d.setDate(d.getDate()+n);return iso(d)},todayISO=()=>new Intl.DateTimeFormat('en-CA',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()),money=(v:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v)||0),obj=(v:any)=>v&&typeof v==='object'&&!Array.isArray(v)?v:{},status=(v:any)=>String(v??'').toLowerCase(),approved=(v:any)=>['approved','completed','paid','success','succeeded'].includes(status(v)),pending=(v:any)=>['pending','processing','created'].includes(status(v)),failed=(v:any)=>['failed','declined','cancelled','canceled','error'].includes(status(v)),refunded=(v:any)=>status(v)==='refunded',chargeback=(v:any)=>['chargeback','lost'].includes(status(v)),amountOf=(s:Sale)=>Number(s.amount??obj(s.data).amount??0)||0,dateOf=(s:Sale)=>(s.occurred_at||s.created_at||'').slice(0,10),fmt=(v:string)=>parse(v).toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit',year:'2-digit'}),methodOf=(s:Sale)=>status(obj(s.data).payment_method??obj(s.data).paymentMethod??obj(s.data).method??obj(s.data).payment?.method??'outros').replace(/[- ]/g,'_'),feeOf=(s:Sale)=>{const d=obj(s.data),v=d.fee_amount??d.feeAmount??d.fee??d.fees;return v===undefined||v===null||v===''?null:Math.max(0,Number(v)||0)}
function calendar(m:Date){const f=new Date(m.getFullYear(),m.getMonth(),1),s=new Date(f);s.setDate(f.getDate()-f.getDay());return Array.from({length:42},(_,i)=>{const d=new Date(s);d.setDate(s.getDate()+i);return{value:iso(d),day:d.getDate(),current:d.getMonth()===m.getMonth()}})}

export default function DashboardControl(){
 const db=useMemo(()=>createSupabaseBrowserClient() as any,[]),today=todayISO(),minDate=add(today,-89)
 const[r,setR]=useState<Range>({start:today,end:today}),[draft,setDraft]=useState<Range>({start:today,end:today}),[month,setMonth]=useState(parse(today)),[menu,setMenu]=useState(false),[cal,setCal]=useState(false),[uid,setUid]=useState(''),[sales,setSales]=useState<Sale[]>([]),[disputes,setDisputes]=useState<Dispute[]>([]),[gateways,setGateways]=useState<Gateway[]>([]),[health,setHealth]=useState<Health[]>([]),[clients,setClients]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[sync,setSync]=useState<Date|null>(null)
 const load=useCallback(async()=>{const{data:{user}}=await db.auth.getUser();if(!user){setUid('');setLoading(false);return}setUid(user.id);setLoading(true);setError(null);try{const since=add(today,-89),[s,d,g,h,c]=await Promise.all([db.from('sales').select('id,amount,currency,status,data,source,medium,campaign,gateway_id,external_id,transaction_id,occurred_at,created_at').eq('user_id',user.id).gte('created_at',`${since}T00:00:00-03:00`).order('created_at',{ascending:false}).limit(5000),db.from('disputes').select('id,amount,status,created_at').eq('user_id',user.id).gte('created_at',`${since}T00:00:00-03:00`).limit(2000),db.from('gateways').select('id,data').eq('user_id',user.id),db.from('gateway_health_snapshots').select('gateway_id,gateway_name,is_healthy,latency_ms,circuit_state,checked_at').eq('user_id',user.id).order('checked_at',{ascending:false}).limit(500),db.from('clients').select('id',{count:'exact',head:true}).eq('user_id',user.id)]);if(s.error||d.error||g.error||h.error||c.error)throw s.error||d.error||g.error||h.error||c.error;setSales(s.data||[]);setDisputes(d.data||[]);setGateways(g.data||[]);const latest=new Map<string,Health>();(h.data||[]).forEach((x:any)=>{const k=String(x.gateway_id||x.gateway_name||'');if(k&&!latest.has(k))latest.set(k,x)});setHealth([...latest.values()]);setClients(c.count||0);setSync(new Date())}catch(e){console.error('[ALTHEA-DASHBOARD]',e);setError('Não foi possível sincronizar o Dashboard.');}finally{setLoading(false)}},[db,today])
 useEffect(()=>{void load()},[load]);useEffect(()=>{if(!uid)return;const ch=db.channel(`dashboard-${uid}`).on('postgres_changes',{event:'*',schema:'public',table:'sales',filter:`user_id=eq.${uid}`},()=>void load()).on('postgres_changes',{event:'*',schema:'public',table:'disputes',filter:`user_id=eq.${uid}`},()=>void load()).on('postgres_changes',{event:'*',schema:'public',table:'gateways',filter:`user_id=eq.${uid}`},()=>void load()).on('postgres_changes',{event:'*',schema:'public',table:'gateway_health_snapshots',filter:`user_id=eq.${uid}`},()=>void load()).subscribe();return()=>{void db.removeChannel(ch)}},[db,uid,load])
 const ps=useMemo(()=>sales.filter(s=>{const d=dateOf(s);return d>=r.start&&d<=r.end}),[sales,r]),pd=useMemo(()=>disputes.filter(d=>{const x=(d.created_at||'').slice(0,10);return x>=r.start&&x<=r.end}),[disputes,r])
 const st=useMemo(()=>{const good=ps.filter(s=>approved(s.status)),gross=good.reduce((n,s)=>n+amountOf(s),0),fees=good.map(feeOf).filter((v):v is number=>v!==null).reduce((n,v)=>n+v,0),refund=ps.filter(s=>refunded(s.status)).reduce((n,s)=>n+amountOf(s),0),cb=pd.filter(d=>chargeback(d.status)),cbv=cb.reduce((n,d)=>n+Number(d.amount||0),0);return{gross,fees,refund,cb:cb.length,cbv,approved:good.length,pending:ps.filter(s=>pending(s.status)).length,failed:ps.filter(s=>failed(s.status)).length,total:ps.length,net:gross-fees-refund-cbv,approval:ps.length?good.length/ps.length*100:0,ticket:good.length?gross/good.length:0,feesKnown:good.some(s=>feeOf(s)!==null)}},[ps,pd])
 const series=useMemo(()=>{const m=new Map<string,number>();ps.filter(s=>approved(s.status)).forEach(s=>{const d=dateOf(s);m.set(d,(m.get(d)||0)+amountOf(s))});const a:{date:string;value:number}[]=[];for(let d=r.start;d<=r.end;d=add(d,1))a.push({date:d,value:m.get(d)||0});return a},[ps,r]),max=Math.max(1,...series.map(x=>x.value)),points=series.map((x,i)=>`${series.length===1?150:8+i*284/(series.length-1)},${110-(x.value/max)*100}`).join(' ')
 const methods=useMemo(()=>{const total=st.gross,keys:[string,string][]=[['pix','Pix'],['credit_card','Cartão'],['boleto','Boleto'],['debit_card','Débito'],['outros','Outros']];return keys.map(([k,l])=>{const v=ps.filter(s=>approved(s.status)&&methodOf(s)===k).reduce((n,s)=>n+amountOf(s),0);return{l,v,p:total?v/total*100:0}}).filter(x=>x.v>0)},[ps,st.gross]),recent=ps.slice(0,5),rows=gateways.map(g=>{const d=obj(g.data),h=health.find(x=>String(x.gateway_id||'')===String(g.id))||health.find(x=>status(x.gateway_name)===status(d.name||d.provider||g.id));return{id:g.id,name:String(d.name||d.provider||g.id),healthy:h?.is_healthy??null,lat:h?.latency_ms??null}}),days=Math.floor((parse(r.end).getTime()-parse(r.start).getTime())/86400000)+1,go=(p:string)=>window.dispatchEvent(new CustomEvent('althea-mobile-page',{detail:p}))
 const preset=(p:string)=>{const x=p==='today'?{start:today,end:today}:p==='yesterday'?{start:add(today,-1),end:add(today,-1)}:{start:add(today,-Number(p)+1),end:today};setR(x);setDraft(x);setMenu(false)}
 return <section className="althea-mobile-dashboard" aria-label="Dashboard mobile">
  <header className="amd-header"><div className="amd-brand"><img src="/althea-logo.png" alt="Althea Pay"/></div><button className="amd-icon-button" type="button" aria-label="Sincronizar agora" onClick={()=>void load()}><RefreshCw size={18}/></button></header>
  <div className="amd-heading"><span className="amd-eyebrow">CONTROL PLANE</span><h1>Dashboard</h1><p>Visão geral do seu negócio</p></div>
  <div className="amd-period-wrap"><button className="amd-period" type="button" onClick={()=>setMenu(!menu)}><span className="amd-period-copy"><CalendarDays size={14}/><span>{r.start===r.end?fmt(r.start):`${fmt(r.start)} — ${fmt(r.end)}`}</span></span><span>⌄</span></button>{menu&&<div className="amd-period-menu"><button type="button" onClick={()=>preset('today')}>Hoje</button><button type="button" onClick={()=>preset('yesterday')}>Ontem</button><button type="button" onClick={()=>preset('7')}>Últimos 7 dias</button><button type="button" onClick={()=>preset('30')}>Últimos 30 dias</button><button type="button" onClick={()=>preset('90')}>Últimos 90 dias</button><button type="button" className="amd-period-custom" onClick={()=>{setDraft(r);setMonth(parse(r.start));setMenu(false);setCal(true)}}>Personalizado <span>›</span></button></div>}</div>
  <div className="amd-filter-caption"><span>{days} {days===1?'dia selecionado':'dias selecionados'}</span><button type="button" onClick={()=>preset('today')}>Hoje</button></div>
  {error&&<div className="amd-card amd-error-card"><strong>Sincronização interrompida</strong><p>{error}</p><button className="amd-secondary-button" type="button" onClick={()=>void load()}>Tentar novamente</button></div>}
  <div className="amd-kpis">{[['Receita Bruta',money(st.gross),'Volume aprovado'],['Faturamento Líquido',money(st.net),st.feesKnown?'Após taxas, reembolsos e chargebacks':'Taxas reais ainda não registradas'],['Taxas Acumuladas',money(st.fees),st.feesKnown?'Taxas registradas':'Nenhuma taxa registrada'],['Taxa de Aprovação',`${st.approval.toFixed(1)}%`,`${st.approved} aprovadas de ${st.total}`],['Ticket Médio',money(st.ticket),'Vendas aprovadas'],['Reembolsos',money(st.refund),'Valor reembolsado'],['Chargebacks',String(st.cb),money(st.cbv)],['Pagamentos Pendentes',String(st.pending),'Aguardando conclusão']].map(([l,v,n])=><article className={`amd-card amd-kpi ${loading?'amd-loading':''}`} key={l}><span>{l}</span>{loading?<div className="amd-skeleton-line"/>:<strong>{v}</strong>}<small>{n}</small></article>)}</div>
  <article className="amd-card amd-chart-card"><div className="amd-card-heading"><div><span className="amd-label">Receita ao longo do tempo</span><strong>{money(st.gross)}</strong></div><BarChart3 size={17}/></div>{series.some(x=>x.value>0)?<><svg className="amd-chart" viewBox="0 0 300 120" preserveAspectRatio="none" aria-label="Gráfico de receita"><path className="amd-chart-grid" d="M8 30H292 M8 60H292 M8 90H292"/><polyline className="amd-chart-line" points={points} fill="none"/></svg><div className="amd-chart-axis"><span>{fmt(r.start)}</span><span>{fmt(r.end)}</span></div></>:<div className="amd-chart-state"><BarChart3 size={20}/><span>Sem receita aprovada no período selecionado.</span></div>}</article>
  <article className="amd-card amd-revenue-card"><div className="amd-section-title"><span>Fontes de Receita</span><small>Distribuição por método</small></div>{methods.length?<div className="amd-source-layout"><div className="amd-donut" style={{background:`conic-gradient(#1DB854 0 ${methods[0].p}%,#26352E ${methods[0].p}% 100%)`}}><span>{Math.round(methods[0].p)}%</span><small>{methods[0].l}</small></div><div className="amd-source-list">{methods.map(m=><div key={m.l}><i/><span>{m.l}</span><b>{m.p.toFixed(1)}%</b></div>)}</div></div>:<p className="amd-data-note">A distribuição aparecerá quando houver transações aprovadas reais.</p>}</article>
  <article className="amd-card amd-empty-card"><div className="amd-section-title"><span>Transações Recentes</span><small>Últimas vendas do período</small></div>{recent.length?<div className="amd-recent-list">{recent.map(s=><button className="amd-recent-row" type="button" key={s.id} onClick={()=>go('vendas')}><span><b>{String(obj(s.data).customer?.name||obj(s.data).customer?.email||s.external_id||s.transaction_id||s.id).slice(0,24)}</b><small>{fmt(dateOf(s))} · {s.gateway_id||'Gateway não identificado'}</small></span><strong>{money(amountOf(s))}</strong></button>)}</div>:<div className="amd-empty-state"><div className="amd-empty-icon"><CreditCard size={21}/></div><strong>Nenhuma transação encontrada</strong><p>As transações do período selecionado aparecerão aqui quando houver dados reais.</p><button className="amd-secondary-button" type="button" onClick={()=>go('vendas')}>Ir para Vendas</button></div>}</article>
  <article className="amd-card amd-gateway-card"><div className="amd-section-title"><span>Status dos Gateways</span><small>Saúde da infraestrutura</small></div>{rows.length?<div className="amd-gateway-list">{rows.map(g=><div className="amd-gateway-row" key={g.id}><span><b>{g.name}</b><small>{g.lat!==null?`${g.lat} ms`:'Saúde ainda não medida'}</small></span><i className={g.healthy===true?'healthy':g.healthy===false?'down':'unknown'}/></div>)}</div>:<div className="amd-gateway-empty"><Network size={18}/><strong>Nenhum gateway conectado</strong><p>Conecte um gateway para acompanhar disponibilidade e processamento.</p><button className="amd-secondary-button" type="button" onClick={()=>go('gateways')}>Configurar gateway</button></div>}</article>
  <article className="amd-card amd-summary-card"><div className="amd-section-title"><span>Operação</span><small>Visão complementar</small></div><div className="amd-summary-grid"><div><b>{clients}</b><span>Clientes</span></div><div><b>{st.failed}</b><span>Falhas</span></div><div><b>{loading?'—':sync?sync.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'}):'—'}</b><span>Última sincronização</span></div></div></article>
  <nav className="amd-bottom-nav" aria-label="Navegação principal">{[[LayoutDashboard,'Dashboard','dashboard'],[CreditCard,'Vendas','vendas'],[GitBranch,'Funis','funis'],[Network,'Gateway','gateways'],[Settings,'Configuração','configuracoes']].map(([I,l,p])=><button type="button" key={String(p)} className={p==='dashboard'?'active':''} onClick={()=>go(String(p))}><I size={18}/><span>{String(l)}</span></button>)}</nav>
  {cal&&<div className="amd-calendar-overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setCal(false)}}><div className="amd-calendar-sheet"><div className="amd-calendar-head"><div><span className="amd-eyebrow">PERÍODO</span><strong>Selecionar datas</strong><small>Disponível nos últimos 90 dias</small></div><button type="button" onClick={()=>setCal(false)} aria-label="Fechar"><X size={18}/></button></div><div className="amd-calendar-range"><div><span>De</span><b>{fmt(draft.start)}</b></div><div><span>Até</span><b>{fmt(draft.end)}</b></div></div><div className="amd-calendar-nav"><button type="button" disabled={month<=parse(minDate)} onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}><ChevronLeft size={17}/></button><strong>{month.toLocaleDateString('pt-BR',{month:'long',year:'numeric'})}</strong><button type="button" disabled={month>=parse(today)} onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}><ChevronRight size={17}/></button></div><div className="amd-weekdays">{['D','S','T','Q','Q','S','S'].map((x,i)=><span key={i}>{x}</span>)}</div><div className="amd-calendar-grid">{calendar(month).map(d=>{const dis=d.value<minDate||d.value>today,sel=d.value>=draft.start&&d.value<=draft.end,edge=d.value===draft.start||d.value===draft.end;return <button type="button" disabled={dis} key={d.value} className={`${d.current?'':'outside'} ${sel?'selected':''} ${edge?'edge':''}`} onClick={()=>{if(draft.start===draft.end||d.value<draft.start)setDraft({start:d.value,end:d.value});else setDraft({start:draft.start,end:d.value})}}>{d.day}</button>})}</div><div className="amd-calendar-footer"><button className="amd-calendar-clear" type="button" onClick={()=>setDraft({start:today,end:today})}>Hoje</button><button className="amd-calendar-apply" type="button" onClick={()=>{if(draft.start<=draft.end){setR(draft);setCal(false)}}}>Aplicar período</button></div></div></div>}
 </section>
}