'use client'

import {useEffect,useMemo,useState} from 'react'
import {CalendarDays,ChevronLeft,ChevronRight,X} from 'lucide-react'
import {createSupabaseBrowserClient} from '@/lib/supabase/client'

type Sale={id:string;amount:number;status:string;created_at:string;customer?:any}
const paid=(s:string)=>['approved','paid','completed','success','succeeded'].includes((s||'').toLowerCase())
const money=(n:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(n)||0)
const pad=(n:number)=>String(n).padStart(2,'0')
const iso=(d:Date)=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`
const br=(d:Date)=>`${pad(d.getDate())}/${pad(d.getMonth()+1)}/${d.getFullYear()}`
const startDay=(d:Date)=>new Date(d.getFullYear(),d.getMonth(),d.getDate(),0,0,0,0)
const endDay=(d:Date)=>new Date(d.getFullYear(),d.getMonth(),d.getDate(),23,59,59,999)

export default function DashboardPeriodController(){
 const db=useMemo(()=>createSupabaseBrowserClient(),[])
 const [open,setOpen]=useState(false),[from,setFrom]=useState<Date>(),[to,setTo]=useState<Date>(),[cursor,setCursor]=useState(()=>new Date()),[sales,setSales]=useState<Sale[]>([]),[loading,setLoading]=useState(false)
 const label=from&&to?`${br(from)} – ${br(to)}`:from?`${br(from)} – …`:'Período: últimos 30 dias'
 async function loadSales(){const{data:{user}}=await db.auth.getUser();if(!user)return;const q=await db.from('sales').select('id,amount,status,created_at,occurred_at,data').eq('user_id',user.id).order('created_at',{ascending:false}).limit(5000);setSales((q.data||[]).map((x:any)=>{const d=x.data&&typeof x.data==='object'&&!Array.isArray(x.data)?x.data:{};return{id:String(x.id),amount:Number(x.amount??d.amount??0),status:String(x.status??d.status??''),created_at:String(x.occurred_at||x.created_at),customer:d.customer||{}}}))}
 useEffect(()=>{void loadSales()},[])
 const days=useMemo(()=>{const y=cursor.getFullYear(),m=cursor.getMonth(),first=new Date(y,m,1),last=new Date(y,m+1,0),out:Date[]=[];for(let i=0;i<first.getDay();i++)out.push(new Date(y,m,1-(first.getDay()-i)));for(let d=1;d<=last.getDate();d++)out.push(new Date(y,m,d));while(out.length<42)out.push(new Date(y,m+1,out.length-(first.getDay()+last.getDate())+1));return out},[cursor])
 const visible=useMemo(()=>{if(!from||!to)return sales;const a=startDay(from),b=endDay(to);return sales.filter(s=>{const d=new Date(s.created_at);return d>=a&&d<=b})},[sales,from,to])
 function apply(){if(!from)return;const end=to||from;const a=startDay(from),b=endDay(end);if(a>b)return;setTo(end);setOpen(false);syncDashboard(a,b);document.dispatchEvent(new CustomEvent('althea:dashboard-period',{detail:{from:iso(a),to:iso(end)}}))}
 function syncDashboard(a?:Date,b?:Date){const f=a&&b?sales.filter(s=>{const d=new Date(s.created_at);return d>=a&&d<=b}):visible;const approved=f.filter(s=>paid(s.status));const gross=f.reduce((n,s)=>n+s.amount,0),rev=approved.reduce((n,s)=>n+s.amount,0),fees=f.reduce((n,s)=>n+Number(s.customer?.fee||0),0),avg=approved.length?rev/approved.length:0,approval=f.length?approved.length/f.length*100:0,refunds=f.filter(s=>s.status==='refunded').length,chargebacks=f.filter(s=>s.status==='chargeback').length,risk=f.filter(s=>['failed','chargeback'].includes(s.status)).length;const values=[money(gross),money(rev-fees),money(fees),money(avg),`${approval.toFixed(1)}%`,String(refunds),String(chargebacks),String(risk)];document.querySelectorAll('.wl-metric-grid .wl-metric b').forEach((el,i)=>{if(values[i]!==undefined)el.textContent=values[i]});const body=document.querySelector('.wl-table tbody');if(body){body.innerHTML='';f.slice(0,20).forEach(s=>{const tr=document.createElement('tr');const c=s.customer||{};const cells=[s.id.slice(0,12),c.name||c.email||'Cliente','—','—',money(s.amount),paid(s.status)?'Aprovado':s.status||'Pendente'];cells.forEach((v,j)=>{const td=document.createElement('td');td.textContent=v;if(j===5)td.className=paid(s.status)?'wl-period-ok':'wl-period-bad';tr.appendChild(td)});body.appendChild(tr)})}}
 useEffect(()=>{const mo=new MutationObserver(()=>{if(from&&to&&document.querySelector('.wl-periods'))syncDashboard(startDay(from),endDay(to))});mo.observe(document.body,{childList:true,subtree:true});return()=>mo.disconnect()},[from,to,sales])
 function preset(name:string){const n=startDay(new Date());let a=new Date(n),b=new Date(n);if(name==='Hoje'){}else if(name==='Ontem'){a.setDate(a.getDate()-1);b=new Date(a)}else if(name==='Últimos 7 dias'){a.setDate(a.getDate()-6)}else if(name==='Últimos 30 dias'){a.setDate(a.getDate()-29)}else if(name==='Este mês'){a=new Date(n.getFullYear(),n.getMonth(),1)}else if(name==='Mês anterior'){a=new Date(n.getFullYear(),n.getMonth()-1,1);b=new Date(n.getFullYear(),n.getMonth(),0)}setFrom(a);setTo(b);setCursor(a);setOpen(true)}
 function pick(d:Date){if(!from||to){setFrom(d);setTo(undefined)}else if(d<from){setFrom(d);setTo(from)}else setTo(d)}
 return <><div className="wl-period-control"><button className="wl-period-trigger" onClick={()=>setOpen(v=>!v)}><CalendarDays size={16}/><span>{label}</span><ChevronRight size={15}/></button></div>{open&&<div className="wl-period-overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><section className="wl-period-popover"><header><div><small>PERÍODO DO DASHBOARD</small><h2>{from&&to?`${br(from)} – ${br(to)}`:'Selecione um dia ou intervalo'}</h2></div><button onClick={()=>setOpen(false)}><X/></button></header><div className="wl-period-presets">{['Hoje','Ontem','Últimos 7 dias','Últimos 30 dias','Este mês','Mês anterior'].map(x=><button key={x} onClick={()=>preset(x)}>{x}</button>)}</div><div className="wl-calendar-head"><button onClick={()=>setCursor(new Date(cursor.getFullYear(),cursor.getMonth()-1,1))}><ChevronLeft/></button><b>{cursor.toLocaleDateString('pt-BR',{month:'long',year:'numeric'})}</b><button onClick={()=>setCursor(new Date(cursor.getFullYear(),cursor.getMonth()+1,1))}><ChevronRight/></button></div><div className="wl-calendar-week">{['dom','seg','ter','qua','qui','sex','sáb'].map(x=><span key={x}>{x}</span>)}</div><div className="wl-calendar-grid">{days.map((d,i)=>{const sameMonth=d.getMonth()===cursor.getMonth(),selected=from&&to&&d>=from&&d<=to,start=from&&iso(d)===iso(from),end=to&&iso(d)===iso(to);return <button key={`${iso(d)}-${i}`} className={`${sameMonth?'':'muted'} ${selected?'range':''} ${start?'start':''} ${end?'end':''}`} onClick={()=>pick(d)}>{d.getDate()}</button>})}</div><footer><button onClick={()=>{setFrom(undefined);setTo(undefined)}}>Limpar</button><button className="wl-primary" disabled={!from||loading} onClick={apply}>Aplicar período</button></footer></section></div>}</>
}
