'use client'

import { GitBranch, MessageCircle, Plus, Search } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { createSupabaseBrowserClient } from '@/lib/supabase/client'

type Funnel={id:string;name:string;status?:string;steps?:number;description?:string}
type Conversation={id:string;buyer_name?:string;buyer_email?:string;status?:string;updated_at?:string;metadata?:Record<string,unknown>}

export default function FunnelsMobile(){
 const db=useMemo(()=>createSupabaseBrowserClient(),[])
 const [active,setActive]=useState('funis'),[query,setQuery]=useState(''),[tab,setTab]=useState('Todas'),[funnels,setFunnels]=useState<Funnel[]>([]),[chats,setChats]=useState<Conversation[]>([]),[selected,setSelected]=useState<Conversation|null>(null),[loading,setLoading]=useState(true)
 useEffect(()=>{const h=(e:Event)=>setActive((e as CustomEvent<string>).detail||'dashboard');window.addEventListener('althea-mobile-page',h);return()=>window.removeEventListener('althea-mobile-page',h)},[])
 useEffect(()=>{let cancelled=false;void(async()=>{const {data:{user}}=await db.auth.getUser();if(!user){setLoading(false);return}const [f,c]=await Promise.all([db.from('funnels').select('id,name,status,data').eq('user_id',user.id).is('deleted_at',null),db.from('crm_conversations').select('id,buyer_name,buyer_email,status,updated_at,metadata').eq('user_id',user.id).order('updated_at',{ascending:false})]);if(cancelled)return;setFunnels((f.data||[]).map((x:any)=>{const d=x.data&&typeof x.data==='object'?x.data:{};return{id:String(x.id),name:String(x.name||d.name||'Funil'),status:String(x.status||d.status||'Ativo'),steps:Number(d.steps||d.step_count||0),description:String(d.description||'')}}));setChats((c.data||[]) as Conversation[]);setLoading(false)})();return()=>{cancelled=true}},[db])
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return chats.filter(c=>(tab==='Todas'||(tab==='Não lidas'&&c.status==='unread')||(tab==='Funis'&&!!c.metadata?.funnel_id))).filter(c=>!q||`${c.buyer_name||''} ${c.buyer_email||''}`.toLowerCase().includes(q))},[chats,query,tab])
 const go=(page:string)=>{setActive(page);window.dispatchEvent(new CustomEvent('althea-mobile-page',{detail:page}))}
 if(active!=='funis')return null
 return <section className="althea-mobile-funnels" aria-label="Funis e Chat mobile"><header className="amf-header"><img src="/althea-logo.png" alt="Althea Pay"/><button type="button" aria-label="Mais opções">⋮</button></header><main className="amf-content"><h1>Funis & Chat</h1><p>Conversas ativas ({chats.length})</p><label className="amf-search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar conversas..." aria-label="Buscar conversas"/></label><div className="amf-tabs">{['Todas','Não lidas','Funis'].map(x=><button key={x} type="button" className={tab===x?'active':''} onClick={()=>setTab(x)}>{x}{x!=='Funis'&&` ${x==='Todas'?chats.length:chats.filter(c=>c.status==='unread').length}`}</button>)}</div><section className="amf-card"><div className="amf-card-head"><strong>CONVERSAS</strong><button type="button" aria-label="Nova conversa"><Plus size={20}/></button></div>{loading?<div className="amf-empty"><div className="amf-skeleton"/><span>Carregando conversas...</span></div>:filtered.length===0?<div className="amf-empty"><MessageCircle size={55}/><strong>Nenhuma conversa ativa</strong><p>As conversas com seus clientes aparecerão aqui quando houver novos atendimentos.</p></div>:<div className="amf-chat-list">{filtered.map(c=><button key={c.id} type="button" className="amf-chat-row" onClick={()=>setSelected(c)}><span className="amf-avatar">{(c.buyer_name||c.buyer_email||'C').slice(0,1).toUpperCase()}</span><span><b>{c.buyer_name||'Cliente'}</b><small>{c.buyer_email||'Conversa ativa'}</small></span><em>{c.status||'Ativa'}</em></button>)}</div>}</section>{funnels.length>0&&<section className="amf-funnels"><div className="amf-card-head"><strong>FUNIS</strong><span>{funnels.length}</span></div>{funnels.slice(0,5).map(f=><article key={f.id}><GitBranch size={17}/><div><strong>{f.name}</strong><small>{f.status} {f.steps?`· ${f.steps} etapas`:''}</small></div></article>)}</section>}</main>{selected&&<div className="amf-modal" role="dialog" aria-modal="true"><div className="amf-sheet"><button className="amf-close" type="button" onClick={()=>setSelected(null)}>Fechar</button><span>CONVERSA</span><h2>{selected.buyer_name||'Cliente'}</h2><p>{selected.buyer_email||'Atendimento ativo'}</p><div className="amf-note">Mensagens e contexto da conversa serão exibidos aqui.</div></div></div>}<nav className="amf-bottom-nav">{[['dashboard','Dashboard'],['vendas','Vendas'],['funis','Funis'],['gateways','Gateway'],['configuracoes','Config']].map(([k,l])=><button key={k} type="button" className={active===k?'active':''} onClick={()=>go(k)}><span>{k==='dashboard'?'⌂':k==='vendas'?'▥':k==='funis'?'▢':k==='gateways'?'◇':'⚙'}</span><small>{l}</small></button>)}</nav></section>
}
