'use client'

import { useCallback, useEffect, useMemo, useState } from 'react'
import { CheckCircle2, ChevronDown, CreditCard, Filter, Search, X } from 'lucide-react'
import { createSupabaseBrowserClient } from '@/lib/supabase/client'

type Sale={id:string;amount:number|string|null;status?:string|null;currency?:string|null;data?:any;gateway_id?:string|null;external_id?:string|null;transaction_id?:string|null;occurred_at?:string|null;created_at?:string|null}
const lower=(v:any)=>String(v??'').toLowerCase()
const approved=(s:any)=>['approved','completed','paid','success','succeeded'].includes(lower(s))
const pending=(s:any)=>['pending','processing','created'].includes(lower(s))
const cancelled=(s:any)=>['failed','declined','cancelled','canceled','error','refunded','chargeback'].includes(lower(s))
const obj=(v:any)=>v&&typeof v==='object'&&!Array.isArray(v)?v:{}
const amount=(s:Sale)=>Number(s.amount??obj(s.data).amount??0)||0
const dateOf=(s:Sale)=>s.occurred_at||s.created_at||''
const fmtMoney=(n:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(n)
const fmtDate=(v:string)=>v?new Date(v).toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit',year:'2-digit'}):'—'
const fmtDateTime=(v:string)=>v?new Date(v).toLocaleString('pt-BR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}):'—'

export default function SalesMobile(){
 const db=useMemo(()=>createSupabaseBrowserClient() as any,[])
 const [active,setActive]=useState('vendas'),[sales,setSales]=useState<Sale[]>([]),[query,setQuery]=useState(''),[filterOpen,setFilterOpen]=useState(false),[periodOpen,setPeriodOpen]=useState(false),[period,setPeriod]=useState('Todo o período'),[status,setStatus]=useState('Todas'),[draftStatus,setDraftStatus]=useState('Todas'),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[selected,setSelected]=useState<Sale|null>(null)
 const today=new Date()
 const load=useCallback(async()=>{if(!db)return;setLoading(true);setError(null);try{const {data:{user}}=await db.auth.getUser();if(!user){setSales([]);return}const q=await db.from('sales').select('id,amount,status,currency,data,gateway_id,external_id,transaction_id,occurred_at,created_at').eq('user_id',user.id).order('created_at',{ascending:false}).limit(5000);if(q.error)throw q.error;setSales((q.data||[]) as Sale[])}catch(e:any){console.error('[ALTHEA-VENDAS]',e);setError('Não foi possível carregar as vendas.');setSales([])}finally{setLoading(false)}},[db])
 useEffect(()=>{void load()},[load])
 useEffect(()=>{if(!db)return;let uid='';let channel:any;void db.auth.getUser().then(({data:{user}}:any)=>{if(!user)return;uid=user.id;channel=db.channel(`sales-mobile-${uid}`).on('postgres_changes',{event:'*',schema:'public',table:'sales',filter:`user_id=eq.${uid}`},()=>void load()).subscribe()});return()=>{if(channel)void db.removeChannel(channel)}},[db,load])
 useEffect(()=>{const h=(e:Event)=>setActive((e as CustomEvent<string>).detail||'dashboard');window.addEventListener('althea-mobile-page',h);return()=>window.removeEventListener('althea-mobile-page',h)},[])
 const go=(page:string)=>{setActive(page);window.dispatchEvent(new CustomEvent('althea-mobile-page',{detail:page}))}
 const filtered=useMemo(()=>{const now=new Date();const from=period==='Hoje'?new Date(now.getFullYear(),now.getMonth(),now.getDate()):period==='Últimos 7 dias'?new Date(now.getTime()-6*86400000):period==='Últimos 30 dias'?new Date(now.getTime()-29*86400000):null;return sales.filter(s=>{const text=[s.id,s.external_id,s.transaction_id,s.gateway_id,obj(s.data).customer?.name,obj(s.data).customer?.email].join(' ').toLowerCase();if(query.trim()&&!text.includes(query.trim().toLowerCase()))return false;const d=dateOf(s);if(from&&(!d||new Date(d)<from))return false;if(status==='Pagas'&&!approved(s.status))return false;if(status==='Pendentes'&&!pending(s.status))return false;if(status==='Canceladas'&&!cancelled(s.status))return false;return true})},[sales,query,period,status])
 const totals=useMemo(()=>({gross:filtered.filter(approved).reduce((n,s)=>n+amount(s),0),paid:filtered.filter(approved).length,pending:filtered.filter(pending).length}),[filtered])
 const clear=()=>{setQuery('');setPeriod('Todo o período');setStatus('Todas');setDraftStatus('Todas')}
 const label=(s:Sale)=>{if(approved(s.status))return'Paga';if(pending(s.status))return'Pendente';if(lower(s.status)==='refunded')return'Reembolsada';return'Cancelada'}
 if(active!=='vendas')return null
 return <section className="althea-mobile-sales" aria-label="Vendas mobile">
  <header className="ams-header"><div className="ams-brand"><img src="/althea-logo.png" alt="Althea Pay"/></div><button className="ams-menu" type="button" aria-label="Sincronizar vendas" onClick={()=>void load()}><Search size={16}/></button></header>
  <main className="ams-content"><h1>Vendas</h1><p className="ams-subtitle">Transações reais sincronizadas com a operação</p>
   <label className="ams-search"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} type="search" placeholder="Buscar transações..." aria-label="Buscar transações"/></label>
   <div className="ams-filters"><button className="ams-filter period" type="button" onClick={()=>setPeriodOpen(v=>!v)}><span>{period}</span><ChevronDown size={13}/></button><button className="ams-filter" type="button" onClick={()=>{setDraftStatus(status);setFilterOpen(true)}}><Filter size={13}/><span>Filtros{status!=='Todas'?` · ${status}`:''}</span></button></div>
   {periodOpen&&<div className="ams-inline-menu">{['Todo o período','Hoje','Últimos 7 dias','Últimos 30 dias'].map(item=><button key={item} type="button" className={period===item?'selected':''} onClick={()=>{setPeriod(item);setPeriodOpen(false)}}>{item}<span>{period===item?'✓':''}</span></button>)}</div>}
   <section className="ams-transactions"><div className="ams-table-head"><span>Cliente</span><span>Valor</span><span>Status</span></div>{loading?<div className="ams-empty"><div className="ams-empty-icon"/><strong>Carregando vendas</strong><p>Sincronizando dados reais.</p></div>:error?<div className="ams-empty"><div className="ams-empty-icon"><X size={21}/></div><strong>Falha na sincronização</strong><p>{error}</p><button type="button" onClick={()=>void load()}>Tentar novamente</button></div>:filtered.length?<div className="ams-list">{filtered.map(s=>{const customer=obj(s.data).customer||{};return <button key={s.id} type="button" className="ams-sale-row" onClick={()=>setSelected(s)}><span className="ams-sale-client"><b>{String(customer.name||customer.full_name||customer.email||s.external_id||s.id).slice(0,26)}</b><small>{fmtDate(dateOf(s))} · {s.gateway_id||'Gateway não informado'}</small></span><span className="ams-sale-value">{fmtMoney(amount(s))}</span><span className={`ams-sale-status ${approved(s.status)?'paid':pending(s.status)?'pending':'other'}`}>{label(s)}</span></button>})}</div>:<div className="ams-empty"><div className="ams-empty-icon"><CreditCard size={21}/></div><strong>Nenhuma transação encontrada</strong><p>Tente ajustar os filtros ou o período selecionado.</p><button type="button" onClick={clear}>Limpar filtros</button></div>}</section>
   <section className="ams-summary"><article><span>Volume aprovado</span><strong>{fmtMoney(totals.gross)}</strong></article><article><span>Pagas</span><strong>{totals.paid}</strong></article><article><span>Pendentes</span><strong>{totals.pending}</strong></article></section>
  </main>
  <nav className="ams-bottom-nav" aria-label="Navegação principal">{[['dashboard','Dashboard'],['vendas','Vendas'],['funis','Funis/Chat'],['gateways','Gateways'],['configuracoes','Config.']].map(([key,labelText])=><button key={key} type="button" className={active===key?'active':''} onClick={()=>go(key)}><span>{key==='dashboard'?'▦':key==='vendas'?'▤':key==='funis'?'♧':key==='gateways'?'◈':'⚙'}</span><small>{labelText}</small></button>)}</nav>
  {selected&&<div className="ams-modal" role="dialog" aria-modal="true" aria-label="Detalhes da venda" onClick={e=>{if(e.currentTarget===e.target)setSelected(null)}}><div className="ams-sheet"><div className="ams-handle"/><div className="ams-sheet-title"><h2>Detalhes da venda</h2><button type="button" aria-label="Fechar" onClick={()=>setSelected(null)}><X size={17}/></button></div><div className="ams-sale-detail"><div><span>Status</span><b>{label(selected)}</b></div><div><span>Valor</span><b>{fmtMoney(amount(selected))}</b></div><div><span>Data</span><b>{fmtDateTime(dateOf(selected))}</b></div><div><span>ID</span><b>{selected.id}</b></div><div><span>Transação externa</span><b>{selected.external_id||selected.transaction_id||'Não informado'}</b></div><div><span>Gateway</span><b>{selected.gateway_id||'Não informado'}</b></div></div><button className="ams-apply" type="button" onClick={()=>setSelected(null)}><CheckCircle2 size={15}/> Fechar</button></div></div>}
  {filterOpen&&<div className="ams-modal" role="dialog" aria-modal="true" aria-label="Filtrar transações" onClick={e=>{if(e.currentTarget===e.target)setFilterOpen(false)}}><div className="ams-sheet"><div className="ams-handle"/><div className="ams-sheet-title"><h2>Filtrar transações</h2><button type="button" aria-label="Fechar" onClick={()=>setFilterOpen(false)}><X size={17}/></button></div>{['Todas','Pagas','Pendentes','Canceladas'].map(item=><button key={item} type="button" className={draftStatus===item?'selected':''} onClick={()=>setDraftStatus(item)}><span>{item}</span><b>{draftStatus===item?'✓':'○'}</b></button>)}<button className="ams-apply" type="button" onClick={()=>{setStatus(draftStatus);setFilterOpen(false)}}>Aplicar filtros</button></div></div>}
 </section>
}
