'use client'

import { CheckCircle2, CreditCard, Filter, RefreshCw, Search, X } from 'lucide-react'
import { useCallback, useEffect, useMemo, useState } from 'react'
import { createSupabaseBrowserClient } from '@/lib/supabase/client'

type Sale={id:string;amount:number|string|null;status?:string|null;currency?:string|null;data?:any;gateway_id?:string|null;external_id?:string|null;transaction_id?:string|null;occurred_at?:string|null;created_at?:string|null}
const lower=(v:any)=>String(v??'').toLowerCase()
const approved=(s:any)=>['approved','completed','paid','success','succeeded'].includes(lower(s))
const pending=(s:any)=>['pending','processing','created'].includes(lower(s))
const cancelled=(s:any)=>['failed','declined','cancelled','canceled','error','refunded','chargeback'].includes(lower(s))
const obj=(v:any)=>v&&typeof v==='object'&&!Array.isArray(v)?v:{}
const amount=(s:Sale)=>Number(s.amount??obj(s.data).amount??0)||0
const dateOf=(s:Sale)=>s.occurred_at||s.created_at||''
const fmtMoney=(n:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(n)||0)
const fmtDate=(v:string)=>v?new Date(v).toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit',year:'2-digit'}):'—'
const fmtDateTime=(v:string)=>v?new Date(v).toLocaleString('pt-BR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}):'—'
const iso=(d:Date)=>{const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`}

export default function SalesMobile(){
 const db=useMemo(()=>createSupabaseBrowserClient() as any,[])
 const now=new Date(), today=iso(now)
 const [active,setActive]=useState('vendas'),[sales,setSales]=useState<Sale[]>([]),[query,setQuery]=useState(''),[filterOpen,setFilterOpen]=useState(false),[periodOpen,setPeriodOpen]=useState(false),[startDate,setStartDate]=useState(today),[endDate,setEndDate]=useState(today),[status,setStatus]=useState('Todas'),[draftStatus,setDraftStatus]=useState('Todas'),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[selected,setSelected]=useState<Sale|null>(null)
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const {data:{user}}=await db.auth.getUser();if(!user){setSales([]);return}const q=await db.from('sales').select('id,amount,status,currency,data,gateway_id,external_id,transaction_id,occurred_at,created_at').eq('user_id',user.id).order('created_at',{ascending:false}).limit(5000);if(q.error)throw q.error;setSales((q.data||[]) as Sale[])}catch(e){console.error('[ALTHEA-VENDAS]',e);setError('Não foi possível carregar as vendas.')}finally{setLoading(false)}},[db])
 useEffect(()=>{void load()},[load])
 useEffect(()=>{let channel:any;void db.auth.getUser().then(({data:{user}}:any)=>{if(!user)return;channel=db.channel(`sales-mobile-${user.id}`).on('postgres_changes',{event:'*',schema:'public',table:'sales',filter:`user_id=eq.${user.id}`},()=>void load()).subscribe()});return()=>{if(channel)void db.removeChannel(channel)}},[db,load])
 useEffect(()=>{const h=(e:Event)=>setActive((e as CustomEvent<string>).detail||'dashboard');window.addEventListener('althea-mobile-page',h);return()=>window.removeEventListener('althea-mobile-page',h)},[])
 const go=(page:string)=>{setActive(page);window.dispatchEvent(new CustomEvent('althea-mobile-page',{detail:page}))}
 const filtered=useMemo(()=>sales.filter(s=>{const text=[s.id,s.external_id,s.transaction_id,s.gateway_id,obj(s.data).customer?.name,obj(s.data).customer?.email].join(' ').toLowerCase();if(query.trim()&&!text.includes(query.trim().toLowerCase()))return false;const d=dateOf(s).slice(0,10);if(startDate&&(!d||d<startDate))return false;if(endDate&&(!d||d>endDate))return false;if(status==='Pagas'&&!approved(s.status))return false;if(status==='Pendentes'&&!pending(s.status))return false;if(status==='Canceladas'&&!cancelled(s.status))return false;return true}),[sales,query,startDate,endDate,status])
 const totals=useMemo(()=>({total:filtered.reduce((n,s)=>n+amount(s),0),paid:filtered.filter(s=>approved(s.status)).length,pending:filtered.filter(s=>pending(s.status)).length}),[filtered])
 const clear=()=>{setQuery('');setStartDate(today);setEndDate(today);setStatus('Todas');setDraftStatus('Todas')}
 const label=(s:Sale)=>approved(s.status)?'Paga':pending(s.status)?'Pendente':lower(s.status)==='refunded'?'Reembolsada':'Cancelada'
 if(active!=='vendas')return null
 return <section className="althea-mobile-sales" aria-label="Vendas mobile">
  <header className="ams-header"><button type="button" className="ams-brand" aria-label="Voltar ao Dashboard" onClick={()=>go('dashboard')}><img src="/althea-logo.png" alt="ALTHEA PAY"/></button><button className="ams-menu" type="button" aria-label="Sincronizar vendas" onClick={()=>void load()}><RefreshCw size={16}/></button></header>
  <main className="ams-content"><h1>Vendas</h1><p className="ams-subtitle">Transações</p>
   <label className="ams-search"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} type="search" placeholder="Buscar transações..." aria-label="Buscar transações"/></label>
   <div className="ams-filters"><div className="ams-date-range"><div><span>De</span><input type="date" value={startDate} max={endDate} onChange={e=>setStartDate(e.target.value)}/></div><i>|</i><div><span>Até</span><input type="date" value={endDate} min={startDate} onChange={e=>setEndDate(e.target.value)}/></div></div><button className="ams-filter" type="button" onClick={()=>{setDraftStatus(status);setFilterOpen(true)}}><Filter size={13}/><span>Filtros{status!=='Todas'?` · ${status}`:''}</span></button></div>
   <div className="ams-period-line"><button type="button" onClick={()=>setPeriodOpen(v=>!v)}>{startDate===today&&endDate===today?'Hoje':`${fmtDate(startDate)} — ${fmtDate(endDate)}`} <span>⌄</span></button>{periodOpen&&<div className="ams-inline-menu"><button type="button" onClick={()=>{setStartDate(today);setEndDate(today);setPeriodOpen(false)}}>Hoje</button><button type="button" onClick={()=>{const d=new Date(now);d.setDate(d.getDate()-6);setStartDate(iso(d));setEndDate(today);setPeriodOpen(false)}}>Últimos 7 dias</button><button type="button" onClick={()=>{const d=new Date(now);d.setDate(d.getDate()-29);setStartDate(iso(d));setEndDate(today);setPeriodOpen(false)}}>Últimos 30 dias</button><button type="button" onClick={()=>{setStartDate('');setEndDate('');setPeriodOpen(false)}}>Todo o período</button></div>}</div>
   <section className="ams-transactions"><div className="ams-table-head"><span>Cliente</span><span>Valor</span><span>Status</span></div>{loading?<div className="ams-empty"><div className="ams-empty-icon"/><strong>Carregando vendas</strong><p>Sincronizando dados reais.</p></div>:error?<div className="ams-empty"><div className="ams-empty-icon"><X size={21}/></div><strong>Falha na sincronização</strong><p>{error}</p><button type="button" onClick={()=>void load()}>Tentar novamente</button></div>:filtered.length?<div className="ams-list">{filtered.map(s=>{const customer=obj(s.data).customer||{};return <button key={s.id} type="button" className="ams-sale-row" onClick={()=>setSelected(s)}><span className="ams-sale-client"><b>{String(customer.name||customer.full_name||customer.email||s.external_id||s.id).slice(0,26)}</b><small>{fmtDate(dateOf(s))} · {s.gateway_id||'Gateway não informado'}</small></span><span className="ams-sale-value">{fmtMoney(amount(s))}</span><span className={`ams-sale-status ${approved(s.status)?'paid':pending(s.status)?'pending':'other'}`}>{label(s)}</span></button>})}</div>:<div className="ams-empty"><div className="ams-empty-icon"><CreditCard size={21}/></div><strong>Nenhuma transação encontrada</strong><p>Tente ajustar os filtros ou o período selecionado.</p><button type="button" onClick={clear}>Limpar filtros</button></div>}</section>
   <section className="ams-summary"><article><span>Total</span><strong>{fmtMoney(totals.total)}</strong></article><article><span>Pagas</span><strong>{totals.paid}</strong></article><article><span>Pend.</span><strong>{totals.pending}</strong></article></section>
  </main>
  <nav className="ams-bottom-nav" aria-label="Navegação principal">{[['dashboard','Dashboard'],['vendas','Vendas'],['funis','Funis/Chat'],['gateways','Gateways'],['configuracoes','Config.']].map(([key,labelText])=><button key={key} type="button" className={active===key?'active':''} onClick={()=>go(key)}><span>{key==='dashboard'?'▦':key==='vendas'?'▤':key==='funis'?'♧':key==='gateways'?'◈':'⚙'}</span><small>{labelText}</small></button>)}</nav>
  {selected&&<div className="ams-modal" role="dialog" aria-modal="true" aria-label="Detalhes da venda" onClick={e=>{if(e.currentTarget===e.target)setSelected(null)}}><div className="ams-sheet"><div className="ams-handle"/><div className="ams-sheet-title"><h2>Detalhes da venda</h2><button type="button" aria-label="Fechar" onClick={()=>setSelected(null)}><X size={17}/></button></div><div className="ams-sale-detail"><div><span>Status</span><b>{label(selected)}</b></div><div><span>Valor</span><b>{fmtMoney(amount(selected))}</b></div><div><span>Data</span><b>{fmtDateTime(dateOf(selected))}</b></div><div><span>ID</span><b>{selected.id}</b></div><div><span>Transação externa</span><b>{selected.external_id||selected.transaction_id||'Não informado'}</b></div><div><span>Gateway</span><b>{selected.gateway_id||'Não informado'}</b></div></div><button className="ams-apply" type="button" onClick={()=>setSelected(null)}><CheckCircle2 size={15}/> Fechar</button></div></div>}
  {filterOpen&&<div className="ams-modal" role="dialog" aria-modal="true" aria-label="Filtrar transações" onClick={e=>{if(e.currentTarget===e.target)setFilterOpen(false)}}><div className="ams-sheet"><div className="ams-handle"/><div className="ams-sheet-title"><h2>Filtrar transações</h2><button type="button" aria-label="Fechar" onClick={()=>setFilterOpen(false)}><X size={17}/></button></div>{['Todas','Pagas','Pendentes','Canceladas'].map(item=><button key={item} type="button" className={draftStatus===item?'selected':''} onClick={()=>setDraftStatus(item)}><span>{item}</span><b>{draftStatus===item?'✓':'○'}</b></button>)}<button className="ams-apply" type="button" onClick={()=>{setStatus(draftStatus);setFilterOpen(false)}}>Aplicar filtros</button></div></div>}
 </section>
}
