import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

type O=Record<string,unknown>;
const url=Deno.env.get("SUPABASE_URL")??"",service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??"",internal=Deno.env.get("ALTHEA_INTERNAL_SECRET")??"";
const db=createClient(url,service,{auth:{persistSession:false}});
const json=(v:unknown,s=200)=>new Response(JSON.stringify(v),{status:s,headers:{"Content-Type":"application/json","Cache-Control":"no-store"}});
const text=(v:unknown)=>typeof v==="string"?v.trim():"";
const num=(v:unknown)=>{const n=Number(v);return Number.isFinite(n)?n:0};
const approved=(v:unknown)=>["approved","completed","paid","success","succeeded"].includes(text(v).toLowerCase());
async function generate(date:string,metrics:O,evidence:O[]){const engine=(Deno.env.get("ALTHEA_AI_ENGINE_URL")??"").replace(/\/$/,"");const key=Deno.env.get("ALTHEA_AI_ENGINE_KEY")??"";if(!engine||!key)return `Resumo executivo de ${date}: ${num(metrics.approved_sales)} venda(s) aprovada(s), ${Number(metrics.revenue).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})} de receita aprovada, ${metrics.checkouts_abandoned} checkout(s) com sinal de abandono e ${metrics.gateway_incidents} incidente(s) de gateway.`;try{const r=await fetch(`${engine}/v1/chat/completions`,{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({model:Deno.env.get("ALTHEA_AI_ENGINE_MODEL")??"althea-reasoning",temperature:.15,max_tokens:1800,messages:[{role:"system",content:"Você é a Iara da Althea Pay. Escreva um resumo executivo diário em português do Brasil. Não invente números, causalidade ou eventos. Use somente os dados fornecidos."},{role:"user",content:JSON.stringify({date,metrics,evidence})}]})});if(!r.ok)throw new Error();const j=await r.json();const c=text(j?.choices?.[0]?.message?.content);if(!c)throw new Error();return c}catch{return `Resumo executivo de ${date}: ${num(metrics.approved_sales)} venda(s) aprovada(s), ${Number(metrics.revenue).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})} de receita aprovada, ${metrics.checkouts_abandoned} checkout(s) com sinal de abandono e ${metrics.gateway_incidents} incidente(s) de gateway.`}}
async function reportFor(userId:string,start:string,end:string,reportDate:string){const [sales,checkouts,events,attempts,health]=await Promise.all([db.from("sales").select("id,amount,currency,status,occurred_at,funnel_id,product_id,gateway_id").eq("user_id",userId).gte("occurred_at",start).lt("occurred_at",end),db.from("checkout_sessions").select("id,status,amount,currency,created_at,abandoned_at").eq("user_id",userId).gte("created_at",start).lt("created_at",end),db.from("integration_events").select("id,event_type,status,error_message,created_at").eq("user_id",userId).gte("created_at",start).lt("created_at",end),db.from("gateway_payment_attempts").select("id,gateway_id,gateway_name,status,failure_class,error_message,created_at").eq("user_id",userId).gte("created_at",start).lt("created_at",end),db.from("gateway_health_snapshots").select("gateway_id,gateway_name,is_healthy,latency_ms,checked_at").eq("user_id",userId).gte("checked_at",start).lt("checked_at",end)]);if(sales.error||checkouts.error||events.error||attempts.error||health.error)return false;const sr=sales.data??[],cr=checkouts.data??[],er=events.data??[],ar=attempts.data??[],hr=health.data??[];const approvedSales=sr.filter(x=>approved(x.status)),revenue=approvedSales.reduce((sum,x)=>sum+num(x.amount),0),abandoned=cr.filter(x=>["abandoned","abandonado"].includes(text(x.status).toLowerCase())||Boolean(x.abandoned_at)),incidents=er.filter(x=>x.error_message||["failed","error","timeout"].some(t=>text(x.event_type).toLowerCase().includes(t))).length+ar.filter(x=>["error","unknown"].includes(text(x.failure_class).toLowerCase())).length;const latest=new Map<string,O>();for(const h of hr)latest.set(String(h.gateway_id),h as O);const unhealthy=[...latest.values()].filter(x=>x.is_healthy===false);const metrics={approved_sales:approvedSales.length,revenue,currency:"BRL",checkouts:cr.length,checkouts_abandoned:abandoned.length,gateway_incidents:incidents,gateways_observed:latest.size,gateways_unhealthy:unhealthy.length};const evidence=[...ar.filter(x=>x.error_message).slice(0,10),...er.filter(x=>x.error_message).slice(0,10),...unhealthy.slice(0,10)] as O[];const report=await generate(reportDate,metrics,evidence);const up=await db.from("iara_daily_reports").upsert({user_id:userId,report_date:reportDate,report_text:report,metrics,evidence,delivery_status:"GENERATED",generated_at:new Date().toISOString()},{onConflict:"user_id,report_date"});return !up.error;}
Deno.serve(async req=>{if(req.method!=="POST")return json({ok:false,error:"method_not_allowed"},405);if(!internal||req.headers.get("x-althea-internal-secret")!==internal)return json({ok:false,error:"forbidden"},403);if(!url||!service)return json({ok:false,error:"server_configuration_error"},500);const end=new Date();end.setUTCHours(0,0,0,0);const start=new Date(end.getTime()-86400000),startIso=start.toISOString(),endIso=end.toISOString(),reportDate=startIso.slice(0,10);let page=1,processed=0,failed=0;for(;;){const users=await db.auth.admin.listUsers({page,perPage:100});if(users.error)return json({ok:false,error:"user_scan_failed"},500);const rows=users.data.users;if(!rows.length)break;for(const u of rows){if(await reportFor(u.id,startIso,endIso,reportDate))processed++;else failed++;}if(rows.length<100)break;page++;}return json({ok:true,report_date:reportDate,processed,failed});});
