'use client'

import { useEffect, useMemo, useState } from 'react'
import { ArrowLeft, BrainCircuit, CheckCircle2, Clock3, CreditCard, DollarSign, MessageCircle, RefreshCw, ShoppingCart, Tag, UserRound, XCircle } from 'lucide-react'

type Json = Record<string, unknown>
type C360 = { profile: Json; conversations: Json[]; messages: Json[]; notes: Json[]; tags: Json[]; sales: Json[]; checkouts: Json[]; payment_attempts: Json[]; events: Json[]; aggregates: Json; scores: Json; generated_at: string }
type Predictive = { conversion_probability?: number; recovery_probability?: number; ltv_propensity?: number; overall_score?: number; confidence?: number; method?: string }
const s=(v:unknown)=>typeof v==='string'&&v.trim()?v.trim():null
const n=(v:unknown)=>{const x=Number(v);return Number.isFinite(x)?x:0}
const pct=(v:unknown)=>Math.max(0,Math.min(100,Math.round(n(v)*100)))
const money=(v:unknown,currency='BRL')=>{try{return new Intl.NumberFormat('pt-BR',{style:'currency',currency}).format(n(v))}catch{return`${currency} ${n(v).toFixed(2)}`}}
const label=(v:unknown)=>s(v)?.replaceAll('_',' ')??'—'
const statusIcon=(v:unknown)=>{const x=String(v??'').toLowerCase();if(['approved','paid','completed','success','succeeded'].includes(x))return <CheckCircle2 size={14} className="text-[#1DB854]"/>;if(['failed','declined','rejected','error','refused'].includes(x))return <XCircle size={14} className="text-rose-300"/>;return <Clock3 size={14} className="text-amber-300"/>}
function Score({title,value}:{title:string;value:number}){return <div className="rounded-2xl border border-white/10 bg-white/[.025] p-4"><div className="flex justify-between text-[9px] font-black uppercase tracking-wider text-slate-500"><span>{title}</span><b className="text-white">{value}/100</b></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-white/10"><div className="h-full bg-[#1DB854]" style={{width:`${value}%`}}/></div></div>}

export default function Customer360Page(){
 const[conversation,setConversation]=useState('');const[data,setData]=useState<C360|null>(null);const[predictive,setPredictive]=useState<Predictive|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('')
 useEffect(()=>{setConversation(new URLSearchParams(window.location.search).get('conversation')?.trim()??'')},[])
 const load=async()=>{if(!conversation)return;setLoading(true);setError('');try{const r=await fetch(`/api/crm/customer-360?conversation=${encodeURIComponent(conversation)}`,{cache:'no-store'});const b=await r.json();if(!r.ok)throw new Error(b.error??'Falha ao carregar Customer 360.');setData(b as C360);const p=await fetch(`/api/crm/predictive-scores?conversation=${encodeURIComponent(conversation)}`,{cache:'no-store'});setPredictive(p.ok?await p.json():null)}catch(e){setError(e instanceof Error?e.message:'Falha ao carregar Customer 360.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[conversation])
 const profile=data?.profile??{};const agg=data?.aggregates??{};const scores=data?.scores??{};const nextAction=useMemo(()=>{if(pct(predictive?.recovery_probability)>=70)return'Priorizar recuperação.';if(pct(predictive?.conversion_probability)>=70)return'Priorizar fechamento.';if(n(scores.recovery_score)>=70)return'Priorizar recuperação.';if(n(scores.conversion_score)>=70)return'Priorizar fechamento.';if(n(agg.unread)>0)return'Responder mensagens não lidas.';if(n(agg.abandoned_checkouts)>0)return'Retomar checkout abandonado.';return'Monitorar novos sinais reais da jornada.'},[agg,predictive,scores])
 if(loading)return <main className="min-h-screen bg-[#070A09] p-6 text-slate-100"><div className="mx-auto max-w-[1500px] space-y-3"><div className="h-10 w-60 animate-pulse rounded-xl bg-white/[.04]"/><div className="h-40 animate-pulse rounded-[24px] bg-white/[.03]"/><div className="grid gap-3 md:grid-cols-3"><div className="h-28 animate-pulse rounded-2xl bg-white/[.03]"/><div className="h-28 animate-pulse rounded-2xl bg-white/[.03]"/><div className="h-28 animate-pulse rounded-2xl bg-white/[.03]"/></div></div></main>
 if(error||!data)return <main className="min-h-screen bg-[#070A09] p-6 text-slate-100"><div className="mx-auto max-w-[900px] rounded-[24px] border border-rose-500/20 bg-rose-500/10 p-6"><p className="text-sm text-rose-200">{error||'Conversa não encontrada.'}</p><a href={`/dashboard/crm?conversation=${encodeURIComponent(conversation)}`} className="mt-4 inline-flex rounded-xl border border-white/10 px-3 py-2 text-xs">Voltar ao CRM</a></div></main>
 return <main className="min-h-screen bg-[#070A09] px-3 py-5 text-slate-100 lg:px-7"><div className="mx-auto max-w-[1500px]"><header className="mb-5 flex items-center justify-between gap-3"><div className="flex items-center gap-3"><a href={`/dashboard/crm?conversation=${encodeURIComponent(conversation)}`} className="rounded-xl border border-white/10 p-2 text-slate-400"><ArrowLeft size={17}/></a><div><div className="text-[9px] font-black uppercase tracking-[.22em] text-[#1DB854]">ALTHEA REVENUE OS</div><h1 className="text-2xl font-black">Customer 360</h1></div></div><button onClick={()=>void load()} className="rounded-xl border border-white/10 p-2 text-slate-400"><RefreshCw size={16}/></button></header>
 <section className="grid gap-3 lg:grid-cols-[1.4fr_.6fr]"><div className="rounded-[24px] border border-white/10 bg-[#0B0F0D] p-5"><div className="flex items-center gap-4"><div className="flex h-14 w-14 items-center justify-center rounded-full bg-[#12351F] text-lg font-black text-[#1DB854]">{(s(profile.buyer_name)||'CL').slice(0,2).toUpperCase()}</div><div><h2 className="text-xl font-black">{s(profile.buyer_name)||'Cliente sem identificação'}</h2><p className="mt-1 text-sm text-slate-500">{s(profile.buyer_email)||'E-mail não informado'}</p></div></div><div className="mt-4 grid gap-2 sm:grid-cols-3"><div className="rounded-xl border border-white/[.07] p-3"><span className="text-[9px] uppercase tracking-wider text-slate-600">Status</span><b className="mt-1 block text-xs">{label(profile.status)}</b></div><div className="rounded-xl border border-white/[.07] p-3"><span className="text-[9px] uppercase tracking-wider text-slate-600">Transação</span><b className="mt-1 block truncate text-xs">{s(profile.transaction_id)||'—'}</b></div><div className="rounded-xl border border-white/[.07] p-3"><span className="text-[9px] uppercase tracking-wider text-slate-600">Cliente</span><b className="mt-1 block truncate text-xs">{s(profile.customer_id)||'—'}</b></div></div></div><div className="rounded-[24px] border border-[#1DB854]/15 bg-[#0C1711] p-5"><div className="flex items-center gap-2 text-[9px] font-black uppercase tracking-wider text-[#1DB854]"><BrainCircuit size={13}/> Próxima ação</div><p className="mt-3 text-sm leading-6 text-slate-300">{nextAction}</p></div></section>
 <section className="mt-3 grid gap-3 md:grid-cols-2 xl:grid-cols-4"><div className="rounded-2xl border border-white/10 bg-[#0B0F0D] p-4"><DollarSign size={16} className="text-[#1DB854]"/><span className="mt-3 block text-[9px] uppercase tracking-widest text-slate-600">Receita aprovada</span><b className="mt-1 block text-xl">{money(agg.approved_revenue)}</b></div><div className="rounded-2xl border border-white/10 bg-[#0B0F0D] p-4"><ShoppingCart size={16} className="text-[#1DB854]"/><span className="mt-3 block text-[9px] uppercase tracking-widest text-slate-600">Vendas aprovadas</span><b className="mt-1 block text-xl">{n(agg.approved_sales_count)}</b></div><div className="rounded-2xl border border-white/10 bg-[#0B0F0D] p-4"><CreditCard size={16} className="text-[#1DB854]"/><span className="mt-3 block text-[9px] uppercase tracking-widest text-slate-600">Tentativas</span><b className="mt-1 block text-xl">{n(agg.payment_attempts)}</b></div><div className="rounded-2xl border border-white/10 bg-[#0B0F0D] p-4"><MessageCircle size={16} className="text-[#1DB854]"/><span className="mt-3 block text-[9px] uppercase tracking-widest text-slate-600">Conversas</span><b className="mt-1 block text-xl">{n(agg.conversations)}</b></div></section>
 <section className="mt-3 grid gap-3 md:grid-cols-3"><Score title="Engajamento" value={n(scores.engagement_score)}/><Score title="Conversão" value={n(scores.conversion_score)}/><Score title="Recuperação" value={n(scores.recovery_score)}/></section>
 <section className="mt-3 rounded-[24px] border border-white/10 bg-[#0B0F0D] p-5"><div className="flex items-center gap-2 text-[10px] font-black uppercase tracking-wider text-slate-500"><UserRound size={14}/> Jornada operacional</div><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><div><span className="text-[9px] text-slate-600">Checkouts</span><b className="mt-1 block">{n(agg.checkout_count)}</b></div><div><span className="text-[9px] text-slate-600">Abandonados</span><b className="mt-1 block">{n(agg.abandoned_checkouts)}</b></div><div><span className="text-[9px] text-slate-600">Mensagens recebidas</span><b className="mt-1 block">{n(agg.inbound_messages)}</b></div><div><span className="text-[9px] text-slate-600">Eventos</span><b className="mt-1 block">{n(agg.event_count)}</b></div></div></section>
 <section className="mt-3 rounded-[24px] border border-white/10 bg-[#0B0F0D] p-5"><div className="flex items-center gap-2 text-[10px] font-black uppercase tracking-wider text-slate-500"><Clock3 size={14}/> Linha de eventos reais</div><div className="mt-4 space-y-2">{data.events.slice(0,20).map((event,i)=><div key={String(event.id??i)} className="flex items-center justify-between gap-3 rounded-xl border border-white/[.06] px-3 py-2.5"><div className="flex min-w-0 items-center gap-2">{statusIcon(event.status)}<span className="truncate text-xs">{label(event.status)}</span></div><span className="shrink-0 text-[9px] text-slate-600">{s(event.received_at)?new Date(String(event.received_at)).toLocaleString('pt-BR'):'—'}</span></div>)}</div></section>
 <section className="mt-3 rounded-[24px] border border-white/10 bg-[#0B0F0D] p-5"><div className="flex items-center gap-2 text-[10px] font-black uppercase tracking-wider text-slate-500"><Tag size={14}/> Dados vinculados</div><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><div><span className="text-[9px] text-slate-600">Notas</span><b className="mt-1 block">{data.notes.length}</b></div><div><span className="text-[9px] text-slate-600">Tags</span><b className="mt-1 block">{data.tags.length}</b></div><div><span className="text-[9px] text-slate-600">Checkouts</span><b className="mt-1 block">{data.checkouts.length}</b></div><div><span className="text-[9px] text-slate-600">Tentativas de pagamento</span><b className="mt-1 block">{data.payment_attempts.length}</b></div></div></section>
 {predictive&&<section className="mt-3 rounded-[24px] border border-[#1DB854]/15 bg-[#0C1711] p-5"><div className="text-[10px] font-black uppercase tracking-wider text-[#1DB854]">Predictive Intelligence</div><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><div><span className="text-[9px] text-slate-600">Conversão</span><b className="mt-1 block">{pct(predictive.conversion_probability)}%</b></div><div><span className="text-[9px] text-slate-600">Recuperação</span><b className="mt-1 block">{pct(predictive.recovery_probability)}%</b></div><div><span className="text-[9px] text-slate-600">LTV</span><b className="mt-1 block">{pct(predictive.ltv_propensity)}%</b></div><div><span className="text-[9px] text-slate-600">Confiança</span><b className="mt-1 block">{pct(predictive.confidence)}%</b></div></div></section>}
 </div></main>
}
