'use client'

import { useEffect, useMemo, useState } from 'react'
import { ArrowLeft, RefreshCw, ShieldCheck, Sparkles, UserRound, WalletCards, Zap } from 'lucide-react'
import Link from 'next/link'

type Opportunity={event_id:string;received_at:string;status:string;transaction_id:string|null;buyer_name:string|null;buyer_email:string|null;funnel_id:string|null;product_id:string|null;amount:number|null;currency:string|null;priority:number;opportunity_type:string;next_action:string}
const money=(v:number|null,c:string|null)=>v==null?'—':new Intl.NumberFormat('pt-BR',{style:'currency',currency:c||'BRL'}).format(v)
const ago=(v:string)=>{const m=Math.max(0,Math.floor((Date.now()-new Date(v).getTime())/60000));if(m<60)return`${m} min`;const h=Math.floor(m/60);if(h<24)return`${h} h`;return`${Math.floor(h/24)} d`}

export default function RecoveryPage(){
 const[rows,setRows]=useState<Opportunity[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[working,setWorking]=useState('')
 const load=async()=>{setLoading(true);setError('');try{const r=await fetch('/api/crm/recovery/opportunities?days=7',{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Falha ao carregar recuperação.');setRows(j.opportunities??[])}catch(e){setError(e instanceof Error?e.message:'Falha ao carregar recuperação.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[])
 const totals=useMemo(()=>({count:rows.length,high:rows.filter(x=>x.priority>=80).length,value:rows.reduce((a,x)=>a+(x.amount||0),0)}),[rows])
 const execute=async(id:string)=>{setWorking(id);setError('');try{const r=await fetch('/api/crm/recovery/opportunities',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({event_id:id})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Não foi possível acionar a recuperação.');setRows(x=>x.filter(o=>o.event_id!==id))}catch(e){setError(e instanceof Error?e.message:'Falha ao acionar recuperação.')}finally{setWorking('')}}
 return <main className="min-h-screen bg-[#070A09] px-4 py-6 text-slate-100 lg:px-8"><div className="mx-auto max-w-[1400px]"><div className="mb-7 flex flex-wrap items-center justify-between gap-4"><div><Link href="/dashboard/crm" className="mb-4 inline-flex items-center gap-2 text-xs text-slate-500 hover:text-white"><ArrowLeft size={14}/> Voltar ao Chat CRM</Link><div className="flex items-center gap-2 text-[10px] font-black uppercase tracking-[.2em] text-[#1DB854]"><Sparkles size={13}/> RECOVERY INTELLIGENCE</div><h1 className="mt-2 text-3xl font-black tracking-tight">Central de Recuperação</h1><p className="mt-1 max-w-2xl text-sm text-slate-500">Oportunidades reais de recuperação priorizadas por status, valor, identificação do cliente e recência. Sem leads fictícios.</p></div><button onClick={()=>void load()} className="inline-flex items-center gap-2 rounded-xl border border-white/10 bg-white/[.03] px-4 py-2.5 text-xs font-bold text-slate-300"><RefreshCw size={14} className={loading?'animate-spin':''}/> Atualizar</button></div>
 {error&&<div className="mb-5 rounded-2xl border border-rose-500/20 bg-rose-500/10 px-4 py-3 text-xs text-rose-200">{error}</div>}
 <section className="mb-5 grid gap-3 md:grid-cols-3"><div className="rounded-2xl border border-white/10 bg-[#0B0F0D] p-5"><div className="text-[9px] font-black uppercase tracking-[.18em] text-slate-600">Oportunidades</div><div className="mt-2 text-2xl font-black">{totals.count}</div></div><div className="rounded-2xl border border-white/10 bg-[#0B0F0D] p-5"><div className="text-[9px] font-black uppercase tracking-[.18em] text-slate-600">Alta prioridade</div><div className="mt-2 text-2xl font-black">{totals.high}</div></div><div className="rounded-2xl border border-white/10 bg-[#0B0F0D] p-5"><div className="text-[9px] font-black uppercase tracking-[.18em] text-slate-600">Valor identificado</div><div className="mt-2 text-2xl font-black">{money(totals.value,'BRL')}</div></div></section>
 <section className="overflow-hidden rounded-3xl border border-white/10 bg-[#0B0F0D]">{loading?<div className="space-y-3 p-5">{[1,2,3,4].map(i=><div key={i} className="h-24 animate-pulse rounded-2xl bg-white/[.03]"/>)}</div>:rows.length===0?<div className="p-16 text-center"><ShieldCheck className="mx-auto mb-3 text-[#1DB854]" size={30}/><h2 className="font-bold">Nenhuma oportunidade pendente</h2><p className="mt-1 text-sm text-slate-600">A fila está limpa com base nos eventos reais dos últimos 7 dias.</p></div>:<div className="divide-y divide-white/[.06]">{rows.map(o=><article key={o.event_id} className="p-5 transition hover:bg-white/[.02]"><div className="flex flex-col gap-5 xl:flex-row xl:items-center xl:justify-between"><div className="min-w-0 flex-1"><div className="mb-2 flex flex-wrap items-center gap-2"><span className={`rounded-full px-2.5 py-1 text-[9px] font-black uppercase tracking-wider ${o.priority>=80?'bg-[#1DB854]/15 text-[#54e57f]':'bg-white/[.05] text-slate-400'}`}>Prioridade {o.priority}</span><span className="rounded-full border border-white/10 px-2.5 py-1 text-[9px] font-bold uppercase text-slate-500">{o.opportunity_type.replaceAll('_',' ')}</span><span className="text-[10px] text-slate-600">há {ago(o.received_at)}</span></div><div className="flex items-center gap-2"><UserRound size={15} className="text-slate-600"/><strong className="truncate">{o.buyer_name||o.buyer_email||'Cliente não identificado'}</strong></div><div className="mt-1 flex flex-wrap gap-x-4 gap-y-1 text-xs text-slate-600"><span>{o.buyer_email||'sem e-mail'}</span><span>Transação: {o.transaction_id||'não informada'}</span>{o.amount!=null&&<span className="font-bold text-slate-400">{money(o.amount,o.currency)}</span>}</div><p className="mt-3 text-xs text-slate-400">{o.next_action}</p></div><div className="flex shrink-0 items-center gap-2"><Link href={`/dashboard/crm?recovery_event=${encodeURIComponent(o.event_id)}`} className="rounded-xl border border-white/10 px-4 py-2.5 text-xs font-bold text-slate-300">Abrir CRM</Link><button disabled={working===o.event_id} onClick={()=>void execute(o.event_id)} className="inline-flex items-center gap-2 rounded-xl bg-[#1DB854] px-4 py-2.5 text-xs font-black text-black disabled:opacity-50"><Zap size={14}/>{working===o.event_id?'Processando...':'Acionar recuperação'}</button></div></div></article>)}</div>}</section><div className="mt-5 flex items-center gap-2 text-[10px] uppercase tracking-wider text-slate-700"><WalletCards size={13}/> Motor conectado a eventos reais de checkout, venda e pagamento</div></div></main>
}
