import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
const db=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);
const json=(x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{"content-type":"application/json"}});
const emailOf=(v:unknown)=>{const s=String(v??"");const m=s.match(/<([^>]+)>/);return (m?.[1]||s).trim().toLowerCase()};
function bytesFromB64(v:string){const bin=atob(v);return Uint8Array.from(bin,c=>c.charCodeAt(0))}
async function verify(raw:string,req:Request){const secret=Deno.env.get("RESEND_WEBHOOK_SIGNING_SECRET")||"";const id=req.headers.get("svix-id")||"",ts=req.headers.get("svix-timestamp")||"",sig=req.headers.get("svix-signature")||"";if(!secret||!id||!ts||!sig)return false;const keyRaw=secret.replace(/^whsec_/,'');let key:Uint8Array;try{key=bytesFromB64(keyRaw)}catch{return false}const cryptoKey=await crypto.subtle.importKey("raw",key,{name:"HMAC",hash:"SHA-256"},false,["sign"]);const mac=await crypto.subtle.sign("HMAC",cryptoKey,new TextEncoder().encode(`${id}.${ts}.${raw}`));const encoded=btoa(String.fromCharCode(...new Uint8Array(mac)));return sig.split(" ").some(part=>part===`v1,${encoded}`)}
async function accountFor(address:string){const q=await db.from("crm_channel_accounts").select("id,user_id,channel,provider,external_account_id,status,credentials_ref,metadata").eq("channel","email").eq("status","active").limit(200);if(q.error)throw q.error;const target=emailOf(address);return (q.data||[]).find((a:any)=>emailOf(a.metadata?.from_email||a.external_account_id||"")===target) as any;}
Deno.serve(async req=>{if(req.method!=="POST")return json({error:"method_not_allowed"},405);try{const raw=await req.text();if(!(await verify(raw,req)))return json({error:"invalid_signature"},401);const event=JSON.parse(raw);const type=String(event?.type||"");const d=event?.data||{};if(type==="email.received"){const from=emailOf(d.from);const to=Array.isArray(d.to)?d.to.map(emailOf):[];const account=await accountFor(to[0]||"");if(!account)return json({ok:true,ignored:true,reason:"channel_account_not_found"});const subject=String(d.subject||"").trim();const text=String(d.text||d.html||subject||"").trim();if(!text)return json({ok:true,ignored:true,reason:"empty_email"});const r=await db.rpc("crm_ingest_channel_message",{p_user_id:account.user_id,p_channel:"email",p_channel_account_id:account.id,p_external_user_id:from,p_body:text,p_external_message_id:String(d.email_id||d.message_id||""),p_phone_e164:null,p_email:from,p_display_name:from,p_metadata:{provider:"resend",subject,headers:{message_id:d.message_id||null},attachments:d.attachments||[]}});if(r.error)throw r.error;return json({ok:true,type,ingested:true,data:r.data});}const map:Record<string,string>={"email.sent":"sent","email.delivered":"delivered","email.delivery_delayed":"failed","email.bounced":"failed","email.failed":"failed","email.suppressed":"failed"};const status=map[type];if(status){const from=emailOf(d.from||"");const account=await accountFor(from);if(!account)return json({ok:true,ignored:true,reason:"channel_account_not_found"});const id=String(d.email_id||d.message_id||"");if(!id)return json({ok:true,ignored:true,reason:"missing_email_id"});const r=await db.rpc("crm_record_channel_delivery_status",{p_channel_account_id:account.id,p_external_message_id:id,p_status:status,p_provider_event:event});if(r.error)throw r.error;return json({ok:true,type,status,data:r.data});}return json({ok:true,ignored:true,reason:"unsupported_event",type});}catch(e){return json({ok:false,error:e instanceof Error?e.message:String(e)},400)}});
