import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"content-type,x-althea-internal-secret,x-althea-gateway-id,x-althea-idempotency-key","Access-Control-Allow-Methods":"POST,OPTIONS"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json"}});
const rec=(v:unknown):v is Record<string,unknown>=>typeof v==="object"&&v!==null&&!Array.isArray(v);
const text=(v:unknown)=>String(v??"").trim();
function secret(body:Record<string,unknown>):string{const c=rec(body.credential)?body.credential:{};return text(c.api_key??c.access_token??c.secret_key);}
function authHeader(provider:string,key:string){return provider==="stripe"?`Basic ${btoa(`${key}:`)}`:`Bearer ${key}`;}
async function request(provider:string,url:string,key:string,method:string,body:Record<string,unknown>|null,idempotency:string){const headers:Record<string,string>={Authorization:authHeader(provider,key),"Content-Type":"application/json"};if(idempotency&&provider!=="asaas")headers[provider==="mercado_pago"?"X-Idempotency-Key":"Idempotency-Key"]=idempotency;const response=await fetch(url,{method,headers,body:body?JSON.stringify(body):undefined});const payload=await response.json().catch(()=>({}));return{response,payload:rec(payload)?payload:{}};}
function stripeForm(data:Record<string,string>){return new URLSearchParams(data).toString();}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return json({error:"method_not_allowed"},405);const expected=Deno.env.get("ALTHEA_INTERNAL_SECRET")??"";if(!expected||req.headers.get("x-althea-internal-secret")!==expected)return json({error:"forbidden"},403);let body:Record<string,unknown>;try{const x=await req.json();if(!rec(x))return json({error:"invalid_json"},400);body=x;}catch{return json({error:"invalid_json"},400)}const provider=text(body.provider).toLowerCase(),operation=text(body.operation).toLowerCase(),environment=text(body.environment).toLowerCase(),key=secret(body),idempotency=text(body.idempotency_key??req.headers.get("x-althea-idempotency-key"));if(!["stripe","asaas","mercado_pago"].includes(provider))return json({error:"unsupported_provider"},422);if(!key)return json({error:"provider_credential_missing"},422);const amount=Number(body.amount??0),currency=text(body.currency||"BRL").toUpperCase(),metadata=rec(body.metadata)?body.metadata:{},customer=rec(body.customer)?body.customer:{};if(!Number.isFinite(amount)||amount<=0)return json({error:"invalid_amount"},422);try{
if(provider==="stripe"){
const base="https://api.stripe.com/v1";
if(operation==="refund"){const form=stripeForm({payment_intent:text(body.original_external_id),...(Number.isFinite(amount)&&amount>0?{amount:String(Math.round(amount))}:{})});const r=await fetch(`${base}/refunds`,{method:"POST",headers:{Authorization:authHeader(provider,key),"Content-Type":"application/x-www-form-urlencoded","Idempotency-Key":idempotency},body:form});const p=await r.json().catch(()=>({}));if(!r.ok)return json({error:rec(p.error)?p.error.message:"stripe_refund_failed",failure_code:rec(p.error)?p.error.code:`http_${r.status}`},r.status);return json({id:p.id,status:p.status==="succeeded"?"approved":"pending",amount:p.amount,currency:String(p.currency??currency).toUpperCase()});}
const formData:Record<string,string>={amount:String(Math.round(amount)),currency:currency.toLowerCase(),"metadata[althea_idempotency]":idempotency};const token=text(body.payment_token);if(token){formData.payment_method=token;formData.confirm="true";}const r=await fetch(`${base}/payment_intents`,{method:"POST",headers:{Authorization:authHeader(provider,key),"Content-Type":"application/x-www-form-urlencoded","Idempotency-Key":idempotency},body:stripeForm(formData)});const p=await r.json().catch(()=>({}));if(!r.ok)return json({error:rec(p.error)?p.error.message:"stripe_payment_failed",failure_code:rec(p.error)?p.error.code:`http_${r.status}`},r.status);const s=text(p.status);return json({id:p.id,status:s==="succeeded"||s==="requires_capture"?"approved":s==="requires_payment_method"?"declined":"pending",amount:p.amount,currency:String(p.currency??currency).toUpperCase()});
}
if(provider==="asaas"){
const base=environment==="sandbox"?"https://api-sandbox.asaas.com/v3":"https://api.asaas.com/v3";
if(operation==="refund"){const r=await request(provider,`${base}/payments/${encodeURIComponent(text(body.original_external_id))}/refund`,key,"POST",Number.isFinite(amount)?{value:amount/100}:null,idempotency);if(!r.response.ok)return json({error:rec(r.payload.errors?.[0])?r.payload.errors[0].description:r.payload.message??"asaas_refund_failed",failure_code:`http_${r.response.status}`},r.response.status);return json({id:r.payload.id??text(body.original_external_id),status:"approved",amount:Number(r.payload.value??amount/100)*100,currency});}
const providerCustomer=text(customer.provider_customer_id);if(!providerCustomer)return json({error:"asaas_provider_customer_id_required"},422);const billingType=text(metadata.billing_type)||"UNDEFINED",dueDate=text(metadata.due_date)||new Date(Date.now()+86400000).toISOString().slice(0,10);const create=await request(provider,`${base}/payments`,key,"POST",{customer:providerCustomer,billingType,value:amount/100,dueDate,description:text(metadata.description)||"ALTHEA PAY charge"},idempotency);if(!create.response.ok)return json({error:rec(create.payload.errors?.[0])?create.payload.errors[0].description:create.payload.message??"asaas_payment_failed",failure_code:`http_${create.response.status}`},create.response.status);const s=text(create.payload.status);return json({id:create.payload.id,status:s==="RECEIVED"?"approved":s==="CONFIRMED"||s==="PENDING"?"pending":"declined",amount:Number(create.payload.value??amount/100)*100,currency});
}
const base="https://api.mercadopago.com/v1";
if(operation==="refund"){const r=await request(provider,`${base}/payments/${encodeURIComponent(text(body.original_external_id))}/refunds`,key,"POST",Number.isFinite(amount)?{amount:amount/100}:null,idempotency);if(!r.response.ok)return json({error:r.payload.message??"mercado_pago_refund_failed",failure_code:`http_${r.response.status}`},r.response.status);return json({id:r.payload.id,status:r.payload.status==="approved"?"approved":"pending",amount:Number(r.payload.amount??amount/100)*100,currency});}
const paymentMethod=text(metadata.payment_method_id),token=text(body.payment_token),email=text(customer.email);if(!paymentMethod||!token||!email)return json({error:"mercado_pago_payment_method_token_and_customer_email_required"},422);const create=await request(provider,`${base}/payments`,key,"POST",{transaction_amount:amount/100,description:text(metadata.description)||"ALTHEA PAY charge",payment_method_id:paymentMethod,token,installments:Number(metadata.installments)||1,payer:{email}},idempotency);if(!create.response.ok)return json({error:create.payload.message??"mercado_pago_payment_failed",failure_code:`http_${create.response.status}`},create.response.status);return json({id:create.payload.id,status:create.payload.status==="approved"?"approved":create.payload.status==="rejected"?"declined":"pending",amount:Number(create.payload.transaction_amount??amount/100)*100,currency});
}catch(error){return json({error:"provider_adapter_error",detail:error instanceof Error?error.message:"unknown_error"},502)}});
