import { withSupabase } from 'npm:@supabase/server'

const corsHeaders = {'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'content-type, x-althea-signature, x-althea-event-id, x-althea-timestamp','Access-Control-Allow-Methods':'POST, OPTIONS'}
const encoder=new TextEncoder(); const SUCCESS=['approved','paid','completed','success']; const FAILURE=['failed','declined','cancelled','canceled','expired']
function hex(b:ArrayBuffer){return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function hmac(secret:string,value:string){const k=await crypto.subtle.importKey('raw',encoder.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return hex(await crypto.subtle.sign('HMAC',k,encoder.encode(value)))}
function eq(a:string,b:string){if(a.length!==b.length)return false;let r=0;for(let i=0;i<a.length;i++)r|=a.charCodeAt(i)^b.charCodeAt(i);return r===0}
function norm(v:unknown){return String(v??'').trim().toLowerCase()}
Deno.serve(withSupabase({auth:'none'},async(req,ctx)=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:corsHeaders});if(req.method!=='POST')return Response.json({ok:false,error:'method_not_allowed'},{status:405,headers:corsHeaders})
 const raw=await req.text(),sig=req.headers.get('x-althea-signature')||'',eventId=req.headers.get('x-althea-event-id')||crypto.randomUUID(),timestamp=req.headers.get('x-althea-timestamp')||'',secret=Deno.env.get('ALTHEA_WEBHOOK_SECRET')||''
 if(!secret)return Response.json({ok:false,error:'webhook_secret_not_configured'},{status:503,headers:corsHeaders});if(!/^\d+$/.test(timestamp))return Response.json({ok:false,error:'invalid_timestamp'},{status:400,headers:corsHeaders});if(Math.abs(Date.now()-Number(timestamp))>300000)return Response.json({ok:false,error:'stale_webhook'},{status:401,headers:corsHeaders});if(!eq(sig,await hmac(secret,`${timestamp}.${raw}`)))return Response.json({ok:false,error:'invalid_signature'},{status:401,headers:corsHeaders})
 try{const p=JSON.parse(raw),eventType=String(p.event_type||p.type||'unknown'),userId=String(p.user_id||''),funnelId=p.funnel_id?String(p.funnel_id):null,checkoutId=p.checkout_id?String(p.checkout_id):null,transactionId=p.transaction_id?String(p.transaction_id):null,externalId=p.external_id?String(p.external_id):null,status=norm(p.status);if(!userId||!funnelId)return Response.json({ok:false,error:'user_id_and_funnel_id_required'},{status:400,headers:corsHeaders});const db=ctx.supabaseAdmin,eventKey=`${userId}:${eventId}`
 const {data:existing}=await db.from('integration_events').select('id,status').eq('event_key',eventKey).maybeSingle();if(existing)return Response.json({ok:true,duplicate:true,event_id:existing.id,status:existing.status},{headers:corsHeaders})
 const {data:event,error:ee}=await db.from('integration_events').insert({user_id:userId,funnel_id:funnelId,event_type:eventType,external_id:eventId,event_key:eventKey,status:'processing',payload:p,occurred_at:new Date(Number(timestamp)).toISOString()}).select('id').single();if(ee)throw ee
 let transaction:any=null;if(transactionId){const r=await db.from('gateway_transactions').select('*').eq('id',transactionId).eq('user_id',userId).maybeSingle();if(r.error)throw r.error;transaction=r.data;if(transaction){const patch:any={updated_at:new Date().toISOString()};if(status)patch.status=status;if(p.failure_code)patch.failure_code=String(p.failure_code);if(externalId)patch.external_id=externalId;const u=await db.from('gateway_transactions').update(patch).eq('id',transaction.id).eq('user_id',userId);if(u.error)throw u.error;transaction={...transaction,...patch}}}
 let checkout:any=null;if(checkoutId){const r=await db.from('checkout_sessions').select('*').eq('id',checkoutId).eq('user_id',userId).maybeSingle();if(r.error)throw r.error;checkout=r.data;const cs=SUCCESS.includes(status)?'completed':(FAILURE.includes(status)||status==='refunded'?'failed':null);if(cs){const u=await db.from('checkout_sessions').update({status:cs,completed_at:cs==='completed'?new Date().toISOString():null,updated_at:new Date().toISOString()}).eq('id',checkoutId).eq('user_id',userId);if(u.error)throw u.error}const ce=await db.from('checkout_events').upsert({user_id:userId,checkout_id:checkoutId,event_type:eventType,external_id:eventId,payload:p},{onConflict:'checkout_id,external_id',ignoreDuplicates:true});if(ce.error)throw ce.error}
 const lower=eventType.toLowerCase(),purchase=SUCCESS.includes(status)&&['purchase','payment.approved','payment_approved','sale.approved','paid','approved'].includes(lower),reversal=['refunded','chargeback'].includes(status)||['refund','refunded','chargeback'].includes(lower);let saleId:string|null=null
 if(purchase&&transaction){const attribution=checkout?.attribution&&typeof checkout.attribution==='object'?checkout.attribution:{},saleExternalId=externalId||transaction.external_id||eventId,sale={funnel_id:funnelId,product_id:checkout?.product_id??transaction.product_id??null,checkout_id:checkoutId,transaction_id:transaction.id,amount:transaction.amount??checkout?.amount??p.amount??0,currency:transaction.currency??checkout?.currency??p.currency??'BRL',status:'approved',attribution,source:attribution.source??null,medium:attribution.medium??null,campaign:attribution.campaign??null,content:attribution.content??null,term:attribution.term??null,click_id:attribution.click_id??null,external_id:saleExternalId,gateway_id:transaction.gateway_id??null,occurred_at:new Date(Number(timestamp)).toISOString(),data:p};const ex=await db.from('sales').select('id').eq('user_id',userId).eq('external_id',saleExternalId).maybeSingle();if(ex.data){saleId=ex.data.id;const u=await db.from('sales').update(sale).eq('id',saleId).eq('user_id',userId);if(u.error)throw u.error}else{const i=await db.from('sales').insert({id:`sale_${eventId}`,user_id:userId,...sale}).select('id').single();if(i.error)throw i.error;saleId=i.data.id}}
 if(reversal){const saleExternalId=externalId||transaction?.external_id||eventId;const u=await db.from('sales').update({status:status==='chargeback'?'chargeback':'refunded',data:p}).eq('user_id',userId).eq('external_id',saleExternalId);if(u.error)throw u.error}
 await db.from('integration_events').update({status:'processed',processed_at:new Date().toISOString(),error_message:null}).eq('id',event.id)
 // Trigger the automation layer after the business event is persisted. Failure here does not roll back the webhook.
 const automationUrl=`${Deno.env.get('SUPABASE_URL')}/functions/v1/automation-engine-v2`,internal=Deno.env.get('ALTHEA_INTERNAL_SECRET')||''
 if(internal){try{await fetch(automationUrl,{method:'POST',headers:{'content-type':'application/json','x-internal-secret':internal},body:JSON.stringify({user_id:userId,funnel_id:funnelId,event_id:event.id,event_type:eventType,transaction_id:transactionId,checkout_id:checkoutId,sale_id:saleId,external_id:externalId,payload:p})})}catch(e){console.error('automation trigger failed',e)}}
 return Response.json({ok:true,duplicate:false,event_id:event.id,processed:true,sale_synced:purchase||reversal,automation_triggered:Boolean(internal)},{headers:corsHeaders})
 }catch(error){console.error('althea-webhook',error);return Response.json({ok:false,error:error instanceof Error?error.message:'webhook_processing_failed'},{status:500,headers:corsHeaders})}
}))
