import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

type JsonObject = Record<string, unknown>;
const url = Deno.env.get("SUPABASE_URL") ?? "";
const key = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "";
const db = createClient(url, key, { auth: { persistSession: false } });
const json = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status, headers: { "content-type": "application/json" } });
const object = (value: unknown): value is JsonObject => typeof value === "object" && value !== null && !Array.isArray(value);
const aliases: Record<string, string> = { paid: "approved", success: "approved", completed: "approved", captured: "approved", authorized: "approved", processing: "pending", pending: "pending", failed: "failed", declined: "failed", refunded: "refunded", refund: "refunded", chargeback: "chargeback", charged_back: "chargeback", disputed: "chargeback", created: "created" };
const normalize = (value: unknown): string => aliases[String(value ?? "").trim().toLowerCase()] ?? String(value ?? "").trim().toLowerCase();
function eventKind(event: JsonObject, payload: JsonObject, normalizedStatus: string): "payment" | "refund" | "chargeback" { const explicit = String(payload.event_kind ?? payload.event_type ?? event.event_kind ?? event.event_type ?? "").toLowerCase(); if (explicit.includes("chargeback") || explicit.includes("dispute")) return "chargeback"; if (explicit.includes("refund") || normalizedStatus === "refunded") return "refund"; if (normalizedStatus === "chargeback") return "chargeback"; return "payment"; }
async function callAutomation(payload: JsonObject): Promise<void> { const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), 3500); try { const response = await fetch(`${url}/functions/v1/automation-engine-v2`, { method: "POST", signal: controller.signal, headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); if (!response.ok) console.error(`automation_http_${response.status}`); } catch (error) { console.error("automation_dispatch_failed", error instanceof Error ? error.message : String(error)); } finally { clearTimeout(timer); } }
async function processOne(event: JsonObject): Promise<JsonObject> { const webhookId = String(event.id ?? ""); const payload = object(event.payload) ? event.payload : {}; const rawStatus = String(payload.status ?? payload.payment_status ?? payload.transaction_status ?? payload.state ?? event.event_type ?? "").trim().toLowerCase(); const status = normalize(rawStatus); const externalId = String(payload.external_id ?? payload.transaction_id ?? payload.payment_id ?? payload.id ?? event.external_id ?? "").trim(); if (!webhookId || !externalId) return { ok: false, retry: false, reason: "external_transaction_id_missing" }; if (!Object.prototype.hasOwnProperty.call(aliases, rawStatus)) return { ok: false, retry: false, reason: "unsupported_provider_status", status }; const kind = eventKind(event, payload, status); const amountValue = payload.amount ?? payload.value ?? payload.total_amount; const amount = typeof amountValue === "number" ? amountValue : Number(amountValue); const currencyValue = String(payload.currency ?? payload.currency_code ?? "").trim().toUpperCase(); const { data, error } = await db.rpc("process_gateway_webhook_v11", { p_webhook_id: webhookId, p_next_status: status, p_external_transaction_id: externalId, p_failure_code: payload.failure_code ? String(payload.failure_code) : null, p_event_kind: kind, p_amount: Number.isFinite(amount) && amount > 0 ? amount : null, p_currency: currencyValue || null, p_external_event_id: event.provider_event_id ? String(event.provider_event_id) : null }); if (error) throw error; if (object(data) && data.transaction_id) await callAutomation({ user_id: event.user_id ?? null, event_id: webhookId, event_type: String(event.event_type ?? "gateway.webhook"), transaction_id: data.transaction_id, external_id: externalId, payload }); return object(data) ? { ok: true, ...data } : { ok: true, data }; }
Deno.serve(async (request) => { if (request.method !== "POST") return json({ error: "method_not_allowed" }, 405); const suppliedSecret = request.headers.get("x-internal-secret"); if (!suppliedSecret) return json({ error: "unauthorized" }, 401); const auth = await db.rpc("verify_althea_internal_secret", { p_secret: suppliedSecret }); if (auth.error || auth.data !== true) return json({ error: "unauthorized" }, 401); try { const body = await request.json().catch(() => ({})); const requested = object(body) && body.webhook_id ? String(body.webhook_id) : ""; const now = new Date().toISOString(); let events: JsonObject[] = []; if (requested) { const result = await db.from("gateway_webhook_events").select("*").eq("id", requested).maybeSingle(); if (result.error) throw result.error; if (result.data) events = [result.data as JsonObject]; } else { const result = await db.from("gateway_webhook_events").select("*").in("status", ["accepted", "failed"]).or(`next_attempt_at.is.null,next_attempt_at.lte.${now}`).order("received_at", { ascending: true }).limit(50); if (result.error) throw result.error; events = (result.data ?? []) as JsonObject[]; } let processed = 0; let failed = 0; let dead = 0; for (const event of events) { const id = String(event.id ?? ""); const attempts = Number(event.attempts ?? 0) + 1; const claim = await db.from("gateway_webhook_events").update({ status: "processing", attempts, updated_at: new Date().toISOString() }).eq("id", id).in("status", ["accepted", "failed"]).select("id").maybeSingle(); if (claim.error || !claim.data) continue; try { const result = await processOne(event); if (!result.ok && result.retry === false) { await db.from("gateway_webhook_events").update({ status: "dead_letter", last_error: String(result.reason ?? "processing_rejected"), next_attempt_at: null, updated_at: new Date().toISOString() }).eq("id", id).eq("status", "processing"); dead++; continue; } processed++; } catch (error) { failed++; const message = error instanceof Error ? error.message : String(error); const isDead = attempts >= 8; const delay = Math.min(3600, 30 * 2 ** Math.max(0, attempts - 1)); const nextAttempt = new Date(Date.now() + delay * 1000).toISOString(); await db.from("gateway_webhook_events").update({ status: isDead ? "dead_letter" : "failed", last_error: message, next_attempt_at: isDead ? null : nextAttempt, updated_at: new Date().toISOString() }).eq("id", id).eq("status", "processing"); if (isDead) dead++; } } return json({ ok: true, scanned: events.length, processed, failed, dead_lettered: dead }); } catch (error) { return json({ ok: false, error: error instanceof Error ? error.message : String(error) }, 500); } });