create or replace function public.dashboard_operational_data_for_user(
  p_start_date date, p_end_date date, p_product text default null, p_funnel text default null, p_gateway text default null,
  p_status text default null, p_source text default null, p_campaign text default null, p_currency text default null, p_payment_method text default null)
returns jsonb language sql stable set search_path=public as $function$
with sales_base as (select s.* from public.sales s where s.user_id=auth.uid() and ((coalesce(s.occurred_at,s.created_at) at time zone 'America/Sao_Paulo')::date between p_start_date and p_end_date) and (p_product is null or s.product_id=p_product) and (p_funnel is null or s.funnel_id=p_funnel) and (p_gateway is null or s.gateway_id=p_gateway) and (p_status is null or lower(coalesce(s.status,''))=lower(p_status)) and (p_source is null or coalesce(s.source,s.attribution->>'source')=p_source) and (p_campaign is null or coalesce(s.campaign,s.attribution->>'campaign')=p_campaign) and (p_currency is null or lower(coalesce(s.currency,''))=lower(p_currency)) and (p_payment_method is null or lower(coalesce(s.data->>'payment_method',s.data->>'payment_type',s.data->>'method',''))=lower(p_payment_method))),
checkout_base as (select c.* from public.checkout_sessions c where c.user_id=auth.uid() and ((c.created_at at time zone 'America/Sao_Paulo')::date between p_start_date and p_end_date) and (p_product is null or c.product_id=p_product) and (p_funnel is null or c.funnel_id=p_funnel) and (p_currency is null or lower(coalesce(c.currency,''))=lower(p_currency))),
sales_counts as (select count(*) total,count(*) filter(where lower(coalesce(status,''))='approved') approved,count(*) filter(where lower(coalesce(status,'')) in ('pending','processing')) pending,count(*) filter(where lower(coalesce(status,'')) in ('declined','failed','rejected')) declined,count(*) filter(where lower(coalesce(status,'')) in ('cancelled','canceled')) cancelled,count(*) filter(where lower(coalesce(status,''))='refunded') refunded,count(*) filter(where lower(coalesce(status,''))='chargeback') chargebacks,coalesce(sum(amount) filter(where lower(coalesce(status,''))='approved'),0) revenue from sales_base),
checkout_counts as (select count(*) visits,count(*) filter(where lower(coalesce(status,'')) in ('started','pending','processing')) started,count(*) filter(where completed_at is not null or lower(coalesce(status,'')) in ('completed','paid','approved')) completed,count(*) filter(where abandoned_at is not null or lower(coalesce(status,''))='abandoned') abandoned from checkout_base),
refund_base as (select count(*) refunds,coalesce(sum(amount),0) amount from public.gateway_refunds where user_id=auth.uid() and ((created_at at time zone 'America/Sao_Paulo')::date between p_start_date and p_end_date)),
dispute_base as (select count(*) disputes,coalesce(sum(amount),0) amount from public.disputes where user_id=auth.uid() and ((created_at at time zone 'America/Sao_Paulo')::date between p_start_date and p_end_date)),
gateway_base as (select count(distinct gateway_id) gateways,count(*) attempts,count(*) filter(where lower(coalesce(status,'')) in ('approved','success','succeeded','completed')) approved,count(*) filter(where lower(coalesce(status,'')) in ('failed','declined','rejected','error')) failed from public.gateway_payment_attempts where user_id=auth.uid() and ((created_at at time zone 'America/Sao_Paulo')::date between p_start_date and p_end_date)),
crm_base as (select count(*) conversations,count(*) filter(where unread_count>0) unread,count(*) filter(where lower(coalesce(status,'')) in ('open','pending','waiting')) open from public.crm_conversations where user_id=auth.uid() and ((created_at at time zone 'America/Sao_Paulo')::date between p_start_date and p_end_date)),
ops_base as (select count(*) events,count(*) filter(where lower(coalesce(status,'')) in ('failed','error','dead_letter')) failed,count(*) filter(where processed_at is null) pending from public.integration_events where user_id=auth.uid() and ((created_at at time zone 'America/Sao_Paulo')::date between p_start_date and p_end_date)),
security_base as (select count(*) events,count(*) filter(where lower(coalesce(action,'')) like '%login%' or lower(coalesce(action,'')) like '%auth%') auth_events from public.audit_logs where user_id=auth.uid() and ((created_at at time zone 'America/Sao_Paulo')::date between p_start_date and p_end_date)),
affiliate_base as (select count(*) affiliates from public.affiliate_profiles where user_id=auth.uid()), commissions as (select coalesce(sum(amount_distributed),0) amount from public.affiliate_commissions where user_id=auth.uid() and ((created_at at time zone 'America/Sao_Paulo')::date between p_start_date and p_end_date)),
clients_base as (select count(*) total from public.clients where user_id=auth.uid() and ((created_at at time zone 'America/Sao_Paulo')::date between p_start_date and p_end_date)),
leads_base as (select count(*) leads from public.attribution_sessions where user_id=auth.uid() and ((first_seen_at at time zone 'America/Sao_Paulo')::date between p_start_date and p_end_date)),
funnel_base as (select count(*) total from public.funnels where user_id=auth.uid() and deleted_at is null),
filter_options as (select coalesce((select jsonb_agg(v order by v) from (select distinct product_id v from sales_base where product_id is not null and product_id<>'') q),'[]'::jsonb) products,coalesce((select jsonb_agg(v order by v) from (select distinct funnel_id v from sales_base where funnel_id is not null and funnel_id<>'') q),'[]'::jsonb) funnels,coalesce((select jsonb_agg(v order by v) from (select distinct gateway_id v from sales_base where gateway_id is not null and gateway_id<>'') q),'[]'::jsonb) gateways,coalesce((select jsonb_agg(v order by v) from (select distinct status v from sales_base where status is not null and status<>'') q),'[]'::jsonb) statuses,coalesce((select jsonb_agg(v order by v) from (select distinct currency v from sales_base where currency is not null and currency<>'') q),'[]'::jsonb) currencies,coalesce((select jsonb_agg(v order by v) from (select distinct coalesce(source,attribution->>'source') v from sales_base where coalesce(source,attribution->>'source') is not null and coalesce(source,attribution->>'source')<>'') q),'[]'::jsonb) sources,coalesce((select jsonb_agg(v order by v) from (select distinct coalesce(campaign,attribution->>'campaign') v from sales_base where coalesce(campaign,attribution->>'campaign') is not null and coalesce(campaign,attribution->>'campaign')<>'') q),'[]'::jsonb) campaigns,coalesce((select jsonb_agg(v order by v) from (select distinct lower(coalesce(data->>'payment_method',data->>'payment_type',data->>'method')) v from sales_base where coalesce(data->>'payment_method',data->>'payment_type',data->>'method') is not null) q),'[]'::jsonb) payment_methods)
select jsonb_build_object('financial',jsonb_build_object('revenue',sc.revenue,'approved',sc.approved,'pending',sc.pending,'refunds',rb.refunds,'refundAmount',rb.amount,'disputes',db.disputes,'disputeAmount',db.amount),'sales',jsonb_build_object('total',sc.total,'approved',sc.approved,'pending',sc.pending,'declined',sc.declined,'cancelled',sc.cancelled,'refunded',sc.refunded,'chargebacks',sc.chargebacks,'averageTicket',case when sc.approved>0 then round(sc.revenue/sc.approved,2) else 0 end),'funnels',jsonb_build_object('total',(select total from funnel_base),'visits',cc.visits,'leads',lb.leads,'sales',sc.approved,'revenue',sc.revenue),'checkouts',jsonb_build_object('visits',cc.visits,'started',cc.started,'completed',cc.completed,'abandoned',cc.abandoned,'conversion',case when cc.visits>0 then round(cc.completed::numeric/cc.visits*100,1) else 0 end),'products',jsonb_build_object('sales',sc.approved,'revenue',sc.revenue,'averageTicket',case when sc.approved>0 then round(sc.revenue/sc.approved,2) else 0 end),'clients',jsonb_build_object('total',cb.total,'new',cb.total,'recurring',0,'active',0,'retention',0,'repurchase',0,'ltv',0),'payments',jsonb_build_object('approved',sc.approved,'declined',sc.declined,'pending',sc.pending,'cancelled',sc.cancelled,'refunds',rb.refunds,'chargebacks',sc.chargebacks),'gateways',jsonb_build_object('count',gb.gateways,'attempts',gb.attempts,'approved',gb.approved,'failed',gb.failed,'approvalRate',case when gb.attempts>0 then round(gb.approved::numeric/gb.attempts*100,1) else 0 end),'subscriptions',jsonb_build_object('available',false,'reason','subscription_source_not_available'),'affiliates',jsonb_build_object('count',(select affiliates from affiliate_base),'sales',sc.approved,'revenue',sc.revenue,'commissions',(select amount from commissions)),'marketing',jsonb_build_object('leads',lb.leads,'sales',sc.approved,'revenue',sc.revenue),'crm',jsonb_build_object('conversations',cr.conversations,'unread',cr.unread,'open',cr.open),'operations',jsonb_build_object('events',op.events,'failed',op.failed,'pending',op.pending),'security',jsonb_build_object('events',se.events,'authEvents',se.auth_events),'activity',jsonb_build_object('events',se.events),'alerts',jsonb_build_object('failedOperations',op.failed,'gatewayFailures',gb.failed,'unreadCrm',cr.unread,'disputes',db.disputes),'intelligence',jsonb_build_object('revenue',sc.revenue,'sales',sc.approved,'conversion',case when cc.visits>0 then round(cc.completed::numeric/cc.visits*100,1) else 0 end),'filters',(select to_jsonb(f) from filter_options f),'measuredAt',now()) from sales_counts sc,checkout_counts cc,refund_base rb,dispute_base db,gateway_base gb,crm_base cr,ops_base op,security_base se,clients_base cb,leads_base lb;
$function$;
grant execute on function public.dashboard_operational_data_for_user(date,date,text,text,text,text,text,text,text,text) to authenticated;