do $$ declare r record; begin for r in select schemaname, tablename, policyname, cmd, qual, with_check from pg_policies where schemaname='public' and tablename like 'crm_%' and 'public'=any(roles) and policyname not like '%public%' loop execute format('drop policy if exists %I on %I.%I',r.policyname,r.schemaname,r.tablename); if r.cmd='SELECT' then execute format('create policy %I on %I.%I for select to authenticated using (%s)',r.policyname,r.schemaname,r.tablename,r.qual); elsif r.cmd='INSERT' then execute format('create policy %I on %I.%I for insert to authenticated with check (%s)',r.policyname,r.schemaname,r.tablename,r.with_check); elsif r.cmd='UPDATE' then execute format('create policy %I on %I.%I for update to authenticated using (%s) with check (%s)',r.policyname,r.schemaname,r.tablename,r.qual,r.with_check); elsif r.cmd='DELETE' then execute format('create policy %I on %I.%I for delete to authenticated using (%s)',r.policyname,r.schemaname,r.tablename,r.qual); elsif r.cmd='ALL' then execute format('create policy %I on %I.%I for all to authenticated using (%s) with check (%s)',r.policyname,r.schemaname,r.tablename,r.qual,r.with_check); end if; end loop; end $$;

create index if not exists crm_conversations_user_customer_idx on public.crm_conversations(user_id,customer_id) where customer_id is not null;
create index if not exists crm_conversations_user_email_lower_idx on public.crm_conversations(user_id,lower(buyer_email)) where buyer_email is not null;
create index if not exists crm_conversations_user_whatsapp_idx on public.crm_conversations(user_id,customer_whatsapp) where customer_whatsapp is not null;
create index if not exists crm_conversations_user_funnel_product_updated_idx on public.crm_conversations(user_id,funnel_id,product_id,updated_at desc);
create index if not exists crm_messages_conversation_direction_created_idx on public.crm_messages(conversation_id,direction,created_at desc);
create index if not exists crm_agents_user_status_assigned_idx on public.crm_agents(user_id,status,last_assigned_at);
create index if not exists crm_team_members_user_team_active_idx on public.crm_team_members(user_id,team_id,active);
create index if not exists crm_team_members_user_agent_active_idx on public.crm_team_members(user_id,agent_id,active) where agent_id is not null;
