-- Canonical Multi-Gateway commercial bridge: checkout telemetry, decline details,
-- routing overrides/splits, repricing, payment-link state and operator outbox.
-- The live migration is the source of truth; this file mirrors the deployed schema.

create table if not exists public.gateway_checkout_telemetry (id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id),funnel_id text,checkout_id uuid,transaction_id uuid,event_type text not null,payment_method text,field_name text,payload jsonb not null default '{}'::jsonb,occurred_at timestamptz not null default now(),created_at timestamptz not null default now());
create table if not exists public.gateway_decline_details (id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id),transaction_id uuid,attempt_id uuid,gateway_id text,provider text not null,provider_code text,provider_subcode text,category text not null,safe_message text not null,raw_error jsonb not null default '{}'::jsonb,provider_request_id text,created_at timestamptz not null default now());
create table if not exists public.gateway_routing_overrides (id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id),funnel_id text not null,forced_gateway_id text not null,reason text not null,active boolean not null default true,starts_at timestamptz not null default now(),expires_at timestamptz not null,created_by uuid not null references auth.users(id),created_at timestamptz not null default now());
create table if not exists public.gateway_routing_split_policies (id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id),funnel_id text not null,name text not null,allocations jsonb not null,version bigint not null default 1,active boolean not null default true,created_by uuid not null references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.gateway_checkout_mutations (id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id),checkout_id uuid not null,transaction_id uuid,mutation_type text not null,previous_amount numeric not null,new_amount numeric not null,currency text not null,reason text not null,idempotency_key text not null,actor_id uuid not null references auth.users(id),created_at timestamptz not null default now(),unique(user_id,idempotency_key));
create table if not exists public.gateway_payment_links (id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id),funnel_id text,checkout_id uuid,transaction_id uuid,gateway_id text,provider text,link_type text not null,status text not null default 'pending',amount numeric not null,currency text not null,external_id text,payment_url text,pix_copy_paste text,qr_code_base64 text,expires_at timestamptz,metadata jsonb not null default '{}'::jsonb,idempotency_key text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(user_id,idempotency_key));
create table if not exists public.gateway_operator_events (id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id),funnel_id text,checkout_id uuid,transaction_id uuid,event_type text not null,status text not null default 'queued',idempotency_key text not null,payload jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),delivered_at timestamptz,unique(user_id,idempotency_key));

alter table public.gateway_checkout_telemetry enable row level security;
alter table public.gateway_decline_details enable row level security;
alter table public.gateway_routing_overrides enable row level security;
alter table public.gateway_routing_split_policies enable row level security;
alter table public.gateway_checkout_mutations enable row level security;
alter table public.gateway_payment_links enable row level security;
alter table public.gateway_operator_events enable row level security;
