import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"content-type,x-gateway-id,x-provider-event-id,stripe-signature,x-signature,x-request-id,asaas-access-token","Access-Control-Allow-Methods":"POST,OPTIONS"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"content-type":"application/json"}});
const rec=(v:unknown):v is Record<string,unknown>=>typeof v==="object"&&v!==null&&!Array.isArray(v);
const hex=(bytes:ArrayBuffer)=>Array.from(new Uint8Array(bytes)).map(b=>b.toString(16).padStart(2,"0")).join("");
const safe=(a:string,b:string)=>{if(a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);return d===0;};
async function hmac(secret:string,value:string){const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);return hex(await crypto.subtle.sign("HMAC",key,new TextEncoder().encode(value)));}
Deno.serve(async request=>{if(request.method==="OPTIONS")return new Response("ok",{headers:cors});if(request.method!=="POST")return json({error:"method_not_allowed"},405);const serviceRole=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"),supabaseUrl=Deno.env.get("SUPABASE_URL");if(!serviceRole||!supabaseUrl)return json({error:"server_configuration_error"},500);const gatewayId=(request.headers.get("x-gateway-id")??new URL(request.url).searchParams.get("gateway_id")??"").trim();if(!gatewayId)return json({error:"gateway_id_required"},400);const admin=createClient(supabaseUrl,serviceRole,{auth:{persistSession:false}});const gateway=await admin.from("gateways").select("id,provider,environment,status").eq("id",gatewayId).maybeSingle();if(gateway.error||!gateway.data)return json({error:"gateway_not_found"},404);const provider=String(gateway.data.provider).toLowerCase();const secretResult=await admin.rpc("resolve_gateway_webhook_secret",{p_gateway_id:gatewayId});if(secretResult.error||!secretResult.data)return json({error:"webhook_secret_not_configured"},503);const secret=String(secretResult.data);const rawBody=await request.text();if(rawBody.length>1024*1024)return json({error:"payload_too_large"},413);let payload:Record<string,unknown>;try{const parsed=JSON.parse(rawBody);if(!parsed||typeof parsed!=="object"||Array.isArray(parsed))return json({error:"invalid_payload"},400);payload=parsed as Record<string,unknown>;}catch{return json({error:"invalid_json"},400)}
let valid=false;
if(provider==="stripe"){
 const header=request.headers.get("stripe-signature")??"";const pairs=Object.fromEntries(header.split(",").map(x=>{const [k,...v]=x.split("=");return[k,v.join("=")]}));const timestamp=Number(pairs.t),signature=String(pairs.v1??"");if(!Number.isFinite(timestamp)||!signature||Math.abs(Date.now()-timestamp*1000)>300000)return json({error:"invalid_or_stale_signature"},401);const expected=await hmac(secret,`${timestamp}.${rawBody}`);valid=safe(expected,signature.toLowerCase());
}else if(provider==="asaas"){
 const supplied=request.headers.get("asaas-access-token")??"";valid=safe(secret,supplied);
}else if(provider==="mercado_pago"){
 const signature=request.headers.get("x-signature")??"",requestId=request.headers.get("x-request-id")??"",dataId=new URL(request.url).searchParams.get("data.id")??(rec(payload.data)?String(payload.data.id??""):"");const parts=Object.fromEntries(signature.split(",").map(x=>{const [k,...v]=x.split("=");return[k,v.join("=")]}));const timestamp=String(parts.ts??""),v1=String(parts.v1??"");if(!timestamp||!v1||Math.abs(Date.now()-Number(timestamp)*1000)>300000)return json({error:"invalid_or_stale_signature"},401);const template=`id:${dataId};request-id:${requestId};ts:${timestamp};`;const expected=await hmac(secret,template);valid=safe(expected,v1.toLowerCase());
}else{return json({error:"unsupported_webhook_provider"},422)}
if(!valid)return json({error:"invalid_signature"},401);const eventId=request.headers.get("x-provider-event-id")??String(payload.id??payload.event_id??payload.eventId??"");if(!eventId||eventId.length>300)return json({error:"provider_event_id_required"},400);const ingested=await admin.rpc("ingest_gateway_webhook_v2",{p_gateway_id:gatewayId,p_provider:provider,p_provider_event_id:eventId,p_signature_timestamp:new Date().toISOString(),p_payload:{...payload,_althea_gateway_id:gatewayId}});if(ingested.error)return json({error:"webhook_ingestion_failed",detail:ingested.error.message},500);const row=Array.isArray(ingested.data)?ingested.data[0]:ingested.data;if(row?.duplicate)return json({ok:true,duplicate:true,event_id:eventId});return json({ok:true,accepted:true,event_id:eventId,webhook_id:row?.webhook_id??null},202);});
