-- Financial operations foundation. No card data belongs here.
create table if not exists public.idempotency_keys (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, scope text not null, idempotency_key text not null, status text not null default 'processing' check (status in ('processing','completed','failed')), response_code integer, response_payload jsonb, resource_type text, resource_id text, expires_at timestamptz not null default (now()+interval '24 hours'), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(user_id,scope,idempotency_key));
create table if not exists public.settlements (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, gateway_id text not null, external_settlement_id text, period_start timestamptz, period_end timestamptz, gross_total numeric not null default 0, fees_total numeric not null default 0, net_total numeric not null default 0, currency text not null default 'BRL', status text not null default 'pending', reconciled_at timestamptz, discrepancy_amount numeric, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.disputes (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, transaction_id uuid references public.gateway_transactions(id) on delete set null, gateway_id text, external_dispute_id text, status text not null default 'open', reason text, amount numeric, currency text default 'BRL', evidence jsonb not null default '[]'::jsonb, timeline jsonb not null default '[]'::jsonb, due_at timestamptz, submitted_at timestamptz, resolved_at timestamptz, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
alter table public.idempotency_keys enable row level security;
alter table public.settlements enable row level security;
alter table public.disputes enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='idempotency_keys' and policyname='idempotency_keys_owner_read') then create policy idempotency_keys_owner_read on public.idempotency_keys for select to authenticated using(user_id=auth.uid()); end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='settlements' and policyname='settlements_owner_read') then create policy settlements_owner_read on public.settlements for select to authenticated using(user_id=auth.uid()); end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='disputes' and policyname='disputes_owner_read') then create policy disputes_owner_read on public.disputes for select to authenticated using(user_id=auth.uid()); end if;
end $$;
create index if not exists idempotency_keys_expiry_idx on public.idempotency_keys(expires_at);
create index if not exists settlements_user_gateway_time_idx on public.settlements(user_id,gateway_id,created_at desc);
create unique index if not exists settlements_gateway_external_unique on public.settlements(user_id,gateway_id,external_settlement_id) where external_settlement_id is not null;
create index if not exists disputes_user_status_due_idx on public.disputes(user_id,status,due_at);
create unique index if not exists disputes_gateway_external_unique on public.disputes(user_id,gateway_id,external_dispute_id) where external_dispute_id is not null;
