create table if not exists public.funnel_connections (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, funnel_id text references public.funnels(id) on delete cascade, connection_type text not null default 'script', status text not null default 'active', config jsonb not null default '{}'::jsonb, last_event_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index if not exists funnel_connections_user_id_idx on public.funnel_connections(user_id);
create index if not exists funnel_connections_funnel_id_idx on public.funnel_connections(funnel_id);
create table if not exists public.integration_events (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, funnel_id text, event_type text not null, external_id text, status text not null default 'received', payload jsonb not null default '{}'::jsonb, occurred_at timestamptz not null default now(), created_at timestamptz not null default now());
create index if not exists integration_events_user_id_idx on public.integration_events(user_id);
create index if not exists integration_events_funnel_id_idx on public.integration_events(funnel_id);
create index if not exists integration_events_created_at_idx on public.integration_events(created_at desc);
create table if not exists public.automation_rules (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, name text not null, status text not null default 'draft', trigger_config jsonb not null default '{}'::jsonb, action_config jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index if not exists automation_rules_user_id_idx on public.automation_rules(user_id);
create table if not exists public.platform_settings (user_id uuid primary key references auth.users(id) on delete cascade, data jsonb not null default '{}'::jsonb, updated_at timestamptz not null default now());
alter table public.funnel_connections enable row level security;
alter table public.integration_events enable row level security;
alter table public.automation_rules enable row level security;
alter table public.platform_settings enable row level security;
drop policy if exists funnel_connections_owner on public.funnel_connections;
create policy funnel_connections_owner on public.funnel_connections for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists integration_events_owner on public.integration_events;
create policy integration_events_owner on public.integration_events for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists automation_rules_owner on public.automation_rules;
create policy automation_rules_owner on public.automation_rules for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists platform_settings_owner on public.platform_settings;
create policy platform_settings_owner on public.platform_settings for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
