revoke all on table public.feb_consumed_tickets from anon, authenticated;
revoke all on table public.gateway_payment_link_execution_commands from anon, authenticated;
revoke all on table public.iara_execution_idempotency from anon, authenticated;
revoke all on table public.iara_financial_confirmations from anon, authenticated;
revoke all on table public.platform_health_checks from anon, authenticated;
revoke all on table public.production_readiness_gates from anon, authenticated;
alter table public.feb_consumed_tickets force row level security;
alter table public.gateway_payment_link_execution_commands force row level security;
alter table public.iara_execution_idempotency force row level security;
alter table public.iara_financial_confirmations force row level security;
alter table public.platform_health_checks force row level security;
alter table public.production_readiness_gates force row level security;