create or replace function public.crm_predictive_scores(p_conversation_id uuid)
returns jsonb language sql stable security invoker set search_path=public as $$
with c as (select * from public.crm_conversations where id=p_conversation_id and user_id=auth.uid()),
inbound as (select count(*)::int n,max(created_at) last_at from public.crm_messages where conversation_id=p_conversation_id and direction='inbound'),
sales_agg as (select count(*)::int n,coalesce(sum(case when lower(coalesce(s.status,'')) in ('paid','approved','completed','succeeded') then coalesce(s.amount,0) else 0 end),0)::numeric revenue,count(*) filter(where lower(coalesce(s.status,'')) in ('paid','approved','completed','succeeded'))::int approved from public.sales s join c on s.user_id=c.user_id where (c.customer_id is not null and s.data->>'customer_id'=c.customer_id) or (c.buyer_email is not null and lower(coalesce(s.data->>'email',''))=lower(c.buyer_email)) or (c.transaction_id is not null and c.transaction_id~*'^[0-9a-f-]{36}$' and s.transaction_id=c.transaction_id::uuid)),
pending as (select count(*)::int n from public.crm_webhook_events e join c on e.user_id=c.user_id where c.buyer_email is not null and lower(coalesce(e.payload->>'email',''))=lower(c.buyer_email) and lower(coalesce(e.status,'')) in ('pending','received','retrying')),
base as (select greatest(0,least(100,25+least(25,inbound.n*8)+least(25,sales_agg.approved*15)+least(15,sales_agg.revenue/100)+least(10,pending.n*5)))::numeric conversion,greatest(0,least(100,15+least(30,inbound.n*10)+least(20,pending.n*12)+case when inbound.last_at>=now()-interval '24 hours' then 25 else 0 end+least(10,sales_agg.revenue/200)))::numeric recovery,greatest(0,least(100,20+least(25,sales_agg.approved*12)+least(25,sales_agg.revenue/250)+least(20,inbound.n*5)+case when inbound.last_at>=now()-interval '7 days' then 10 else 0 end))::numeric ltv from inbound,sales_agg,pending),
scored as(select *,round((conversion*0.45+recovery*0.30+ltv*0.25),2) overall from base)
select jsonb_build_object('conversation_id',p_conversation_id,'conversion_probability',round(conversion,2),'recovery_probability',round(recovery,2),'ltv_propensity',round(ltv,2),'overall_score',overall,'confidence',case when overall>=70 then 'high' when overall>=45 then 'medium' else 'low' end,'method','deterministic_behavioral_v1','explainability',jsonb_build_object('inputs','real CRM messages, related sales, pending webhook events','note','Not ML; transparent behavioral heuristics.'),'generated_at',now()) from scored;
$$;
revoke all on function public.crm_predictive_scores(uuid) from public,anon;
grant execute on function public.crm_predictive_scores(uuid) to authenticated;
