create table if not exists public.gateway_checkout_telemetry (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id), funnel_id text null references public.funnels(id), checkout_id uuid null references public.checkout_sessions(id), transaction_id uuid null references public.gateway_transactions(id), event_type text not null, payment_method text null, field_name text null, payload jsonb not null default '{}'::jsonb, occurred_at timestamptz not null default now(), created_at timestamptz not null default now(), unique(user_id, checkout_id, event_type, occurred_at));
create index if not exists gateway_checkout_telemetry_user_time_idx on public.gateway_checkout_telemetry(user_id, occurred_at desc);
create index if not exists gateway_checkout_telemetry_checkout_time_idx on public.gateway_checkout_telemetry(checkout_id, occurred_at desc);

create table if not exists public.gateway_decline_details (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id), transaction_id uuid null references public.gateway_transactions(id), attempt_id uuid null references public.gateway_payment_attempts(id), gateway_id text null references public.gateways(id), provider text not null, provider_code text null, provider_subcode text null, category text not null check(category in ('declined','fraud','technical','timeout','unavailable','pending','unknown')), safe_message text not null, raw_error jsonb not null default '{}'::jsonb, provider_request_id text null, created_at timestamptz not null default now());
create index if not exists gateway_decline_details_tx_idx on public.gateway_decline_details(user_id, transaction_id, created_at desc);

create table if not exists public.gateway_routing_overrides (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id), funnel_id text not null references public.funnels(id), forced_gateway_id text not null references public.gateways(id), reason text not null, active boolean not null default true, starts_at timestamptz not null default now(), expires_at timestamptz not null, created_by uuid not null references auth.users(id), created_at timestamptz not null default now(), constraint gateway_routing_override_expiry_chk check(expires_at > starts_at));
create unique index if not exists gateway_routing_override_active_idx on public.gateway_routing_overrides(user_id,funnel_id) where active=true;

create table if not exists public.gateway_routing_split_policies (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id), funnel_id text not null references public.funnels(id), name text not null, allocations jsonb not null, version bigint not null default 1, active boolean not null default true, created_by uuid not null references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), constraint gateway_routing_split_allocations_object_chk check(jsonb_typeof(allocations)='array'));
create unique index if not exists gateway_routing_split_active_idx on public.gateway_routing_split_policies(user_id,funnel_id) where active=true;

create table if not exists public.gateway_checkout_mutations (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id), checkout_id uuid not null references public.checkout_sessions(id), transaction_id uuid null references public.gateway_transactions(id), mutation_type text not null check(mutation_type in ('repricing','coupon','discount')), previous_amount numeric not null check(previous_amount>=0), new_amount numeric not null check(new_amount>0), currency text not null check(currency ~ '^[A-Z]{3}$'), reason text not null, idempotency_key text not null, actor_id uuid not null references auth.users(id), created_at timestamptz not null default now(), unique(user_id,idempotency_key));

create table if not exists public.gateway_payment_links (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id), funnel_id text null references public.funnels(id), checkout_id uuid null references public.checkout_sessions(id), transaction_id uuid null references public.gateway_transactions(id), gateway_id text null references public.gateways(id), provider text null, link_type text not null check(link_type in ('pix','card','payment_link')), status text not null default 'pending' check(status in ('pending','active','expired','paid','failed','canceled')), amount numeric not null check(amount>0), currency text not null check(currency ~ '^[A-Z]{3}$'), external_id text null, payment_url text null, pix_copy_paste text null, qr_code_base64 text null, expires_at timestamptz null, metadata jsonb not null default '{}'::jsonb, idempotency_key text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(user_id,idempotency_key));

create table if not exists public.gateway_operator_events (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id), funnel_id text null references public.funnels(id), checkout_id uuid null references public.checkout_sessions(id), transaction_id uuid null references public.gateway_transactions(id), event_type text not null, status text not null default 'queued' check(status in ('queued','delivered','failed')), idempotency_key text not null, payload jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), delivered_at timestamptz null, unique(user_id,idempotency_key));
create index if not exists gateway_operator_events_pending_idx on public.gateway_operator_events(user_id,status,created_at);

alter table public.gateway_checkout_telemetry enable row level security;
alter table public.gateway_decline_details enable row level security;
alter table public.gateway_routing_overrides enable row level security;
alter table public.gateway_routing_split_policies enable row level security;
alter table public.gateway_checkout_mutations enable row level security;
alter table public.gateway_payment_links enable row level security;
alter table public.gateway_operator_events enable row level security;

create policy gateway_checkout_telemetry_owner on public.gateway_checkout_telemetry for select using(user_id=auth.uid());
create policy gateway_decline_details_owner on public.gateway_decline_details for select using(user_id=auth.uid());
create policy gateway_override_owner on public.gateway_routing_overrides for select using(user_id=auth.uid());
create policy gateway_split_owner on public.gateway_routing_split_policies for select using(user_id=auth.uid());
create policy gateway_mutation_owner on public.gateway_checkout_mutations for select using(user_id=auth.uid());
create policy gateway_payment_links_owner on public.gateway_payment_links for select using(user_id=auth.uid());
create policy gateway_operator_events_owner on public.gateway_operator_events for select using(user_id=auth.uid());

create or replace function public.record_gateway_checkout_telemetry(p_funnel_id text,p_checkout_id uuid,p_transaction_id uuid,p_event_type text,p_payment_method text default null,p_field_name text default null,p_payload jsonb default '{}'::jsonb)
returns uuid language plpgsql security invoker set search_path=public,pg_catalog as $$ declare v_id uuid; begin if auth.uid() is null then raise exception 'unauthorized'; end if; if p_event_type not in ('checkout_viewed','payment_method_selected','payment_started','payment_field_focused','payment_field_changed','payment_submitted') then raise exception 'invalid_telemetry_event'; end if; insert into public.gateway_checkout_telemetry(user_id,funnel_id,checkout_id,transaction_id,event_type,payment_method,field_name,payload) values(auth.uid(),p_funnel_id,p_checkout_id,p_transaction_id,p_event_type,nullif(trim(p_payment_method),''),nullif(trim(p_field_name),''),coalesce(p_payload,'{}'::jsonb)) returning id into v_id; insert into public.gateway_operator_events(user_id,funnel_id,checkout_id,transaction_id,event_type,idempotency_key,payload) values(auth.uid(),p_funnel_id,p_checkout_id,p_transaction_id,'checkout.'||p_event_type, 'checkout-telemetry:'||v_id::text, jsonb_build_object('telemetry_id',v_id,'event_type',p_event_type,'payment_method',p_payment_method,'field_name',p_field_name,'payload',coalesce(p_payload,'{}'::jsonb))) on conflict do nothing; return v_id; end $$;
revoke all on function public.record_gateway_checkout_telemetry(text,uuid,uuid,text,text,text,jsonb) from public;
grant execute on function public.record_gateway_checkout_telemetry(text,uuid,uuid,text,text,text,jsonb) to authenticated;

create or replace function public.record_gateway_decline_detail(p_transaction_id uuid,p_attempt_id uuid,p_gateway_id text,p_provider text,p_provider_code text,p_provider_subcode text,p_category text,p_safe_message text,p_raw_error jsonb default '{}'::jsonb,p_provider_request_id text default null)
returns uuid language plpgsql security definer set search_path=public,pg_catalog as $$ declare v_user uuid; v_id uuid; begin if coalesce(auth.role(),'') <> 'service_role' then raise exception 'forbidden'; end if; select user_id into v_user from public.gateway_transactions where id=p_transaction_id; if v_user is null then raise exception 'transaction_not_found'; end if; insert into public.gateway_decline_details(user_id,transaction_id,attempt_id,gateway_id,provider,provider_code,provider_subcode,category,safe_message,raw_error,provider_request_id) values(v_user,p_transaction_id,p_attempt_id,p_gateway_id,p_provider,p_provider_code,p_provider_subcode,p_category,p_safe_message,coalesce(p_raw_error,'{}'::jsonb),p_provider_request_id) returning id into v_id; insert into public.gateway_operator_events(user_id,transaction_id,event_type,idempotency_key,payload) values(v_user,p_transaction_id,'payment.declined','decline:'||v_id::text,jsonb_build_object('decline_id',v_id,'provider',p_provider,'code',p_provider_code,'subcode',p_provider_subcode,'category',p_category,'safe_message',p_safe_message,'provider_request_id',p_provider_request_id)) on conflict do nothing; return v_id; end $$;
revoke all on function public.record_gateway_decline_detail(uuid,uuid,text,text,text,text,text,text,jsonb,text) from public,anon,authenticated;
grant execute on function public.record_gateway_decline_detail(uuid,uuid,text,text,text,text,text,text,jsonb,text) to service_role;

create or replace function public.set_gateway_routing_override(p_funnel_id text,p_forced_gateway_id text,p_reason text,p_expires_at timestamptz)
returns uuid language plpgsql security definer set search_path=public,pg_catalog as $$ declare v_id uuid; begin if auth.uid() is null then raise exception 'unauthorized'; end if; if p_expires_at <= now() or p_expires_at > now()+interval '24 hours' then raise exception 'invalid_override_expiry'; end if; if not exists(select 1 from public.gateways where id=p_forced_gateway_id and user_id=auth.uid() and status in ('connected','degraded')) then raise exception 'gateway_not_eligible'; end if; update public.gateway_routing_overrides set active=false where user_id=auth.uid() and funnel_id=p_funnel_id and active=true; insert into public.gateway_routing_overrides(user_id,funnel_id,forced_gateway_id,reason,expires_at,created_by) values(auth.uid(),p_funnel_id,p_forced_gateway_id,trim(p_reason),p_expires_at,auth.uid()) returning id into v_id; insert into public.gateway_operator_events(user_id,funnel_id,event_type,idempotency_key,payload) values(auth.uid(),p_funnel_id,'routing.force_route_changed','force-route:'||v_id::text,jsonb_build_object('override_id',v_id,'gateway_id',p_forced_gateway_id,'expires_at',p_expires_at,'reason',p_reason)); return v_id; end $$;
revoke all on function public.set_gateway_routing_override(text,text,text,timestamptz) from public;
grant execute on function public.set_gateway_routing_override(text,text,text,timestamptz) to authenticated;

create or replace function public.clear_gateway_routing_override(p_funnel_id text)
returns boolean language plpgsql security invoker set search_path=public,pg_catalog as $$ begin if auth.uid() is null then raise exception 'unauthorized'; end if; update public.gateway_routing_overrides set active=false where user_id=auth.uid() and funnel_id=p_funnel_id and active=true; return found; end $$;
revoke all on function public.clear_gateway_routing_override(text) from public;
grant execute on function public.clear_gateway_routing_override(text) to authenticated;

create or replace function public.set_gateway_routing_split_policy(p_funnel_id text,p_name text,p_allocations jsonb)
returns uuid language plpgsql security definer set search_path=public,pg_catalog as $$ declare v_id uuid; v_total numeric; v_count integer; begin if auth.uid() is null then raise exception 'unauthorized'; end if; if jsonb_typeof(p_allocations)<>'array' then raise exception 'allocations_must_be_array'; end if; select count(*),coalesce(sum((x->>'weight')::numeric),0) into v_count,v_total from jsonb_array_elements(p_allocations) x where jsonb_typeof(x)='object'; if v_count<1 or v_total<>100 then raise exception 'split_weights_must_total_100'; end if; if exists(select 1 from jsonb_array_elements(p_allocations) x where not exists(select 1 from public.gateways g where g.id=coalesce(x->>'gateway_id',x->>'gatewayId') and g.user_id=auth.uid() and g.status in ('connected','degraded'))) then raise exception 'split_contains_ineligible_gateway'; end if; update public.gateway_routing_split_policies set active=false where user_id=auth.uid() and funnel_id=p_funnel_id and active=true; insert into public.gateway_routing_split_policies(user_id,funnel_id,name,allocations,created_by) values(auth.uid(),p_funnel_id,trim(p_name),p_allocations,auth.uid()) returning id into v_id; insert into public.gateway_operator_events(user_id,funnel_id,event_type,idempotency_key,payload) values(auth.uid(),p_funnel_id,'routing.split_policy_changed','split-policy:'||v_id::text,jsonb_build_object('policy_id',v_id,'allocations',p_allocations)); return v_id; end $$;
revoke all on function public.set_gateway_routing_split_policy(text,text,jsonb) from public;
grant execute on function public.set_gateway_routing_split_policy(text,text,jsonb) to authenticated;

create or replace function public.mutate_gateway_checkout_price(p_checkout_id uuid,p_transaction_id uuid,p_new_amount numeric,p_currency text,p_reason text,p_idempotency_key text)
returns jsonb language plpgsql security definer set search_path=public,pg_catalog as $$ declare v_user uuid:=auth.uid(); v_old numeric; v_status text; v_version bigint; v_currency text; begin if v_user is null then raise exception 'unauthorized'; end if; if p_new_amount<=0 or p_currency !~ '^[A-Z]{3}$' then raise exception 'invalid_price'; end if; select user_id,amount,currency,status,version into v_user,v_old,v_currency,v_status,v_version from public.gateway_transactions where id=p_transaction_id and user_id=auth.uid() for update; if v_status is null then raise exception 'transaction_not_found'; end if; if v_status not in ('created','pending') then raise exception 'transaction_not_mutable'; end if; if v_currency<>p_currency then raise exception 'currency_mismatch'; end if; update public.checkout_sessions set amount=p_new_amount,currency=p_currency,updated_at=now() where id=p_checkout_id and user_id=auth.uid() and status not in ('completed','canceled'); if not found then raise exception 'checkout_not_mutable'; end if; update public.gateway_transactions set amount=p_new_amount,metadata=jsonb_set(coalesce(metadata,'{}'::jsonb),'{commercial,repriced_at}',to_jsonb(now()),true),version=version+1,updated_at=now() where id=p_transaction_id and user_id=auth.uid() and version=v_version and status in ('created','pending'); if not found then raise exception 'transaction_concurrency_conflict'; end if; insert into public.gateway_checkout_mutations(user_id,checkout_id,transaction_id,mutation_type,previous_amount,new_amount,currency,reason,idempotency_key,actor_id) values(auth.uid(),p_checkout_id,p_transaction_id,'repricing',v_old,p_new_amount,p_currency,trim(p_reason),p_idempotency_key,auth.uid()) on conflict do nothing; insert into public.gateway_operator_events(user_id,checkout_id,transaction_id,event_type,idempotency_key,payload) values(auth.uid(),p_checkout_id,p_transaction_id,'checkout.price_changed','price-change:'||p_idempotency_key,jsonb_build_object('previous_amount',v_old,'new_amount',p_new_amount,'currency',p_currency,'reason',p_reason)); return jsonb_build_object('checkout_id',p_checkout_id,'transaction_id',p_transaction_id,'amount',p_new_amount,'currency',p_currency); end $$;
revoke all on function public.mutate_gateway_checkout_price(uuid,uuid,numeric,text,text,text) from public;
grant execute on function public.mutate_gateway_checkout_price(uuid,uuid,numeric,text,text,text) to authenticated;

create or replace function public.resolve_gateway_operator_events(p_limit integer default 100)
returns setof public.gateway_operator_events language plpgsql security invoker set search_path=public,pg_catalog as $$ begin if auth.uid() is null then raise exception 'unauthorized'; end if; return query select * from public.gateway_operator_events where user_id=auth.uid() and status='queued' order by created_at asc limit greatest(1,least(p_limit,500)); end $$;
revoke all on function public.resolve_gateway_operator_events(integer) from public;
grant execute on function public.resolve_gateway_operator_events(integer) to authenticated;
