create unique index if not exists crm_conversations_active_customer_per_funnel_uq on public.crm_conversations(user_id,funnel_id,customer_id) where customer_id is not null and status in ('open','pending');

create or replace function public.sync_checkout_chat_state_from_event()
returns trigger language plpgsql security definer set search_path=public as $function$
declare p jsonb:=coalesce(new.payload,'{}'::jsonb); c jsonb:=coalesce(p->'customer','{}'::jsonb); v_email text:=nullif(trim(coalesce(c->>'email',p->>'email','')),''); v_phone text:=nullif(trim(coalesce(c->>'whatsapp',c->>'phone',p->>'whatsapp',p->>'phone','')),''); v_customer_id text:=nullif(trim(coalesce(c->>'customer_id',p->>'customer_id','')),''); v_conversation uuid; v_status public.lead_checkout_status; v_gateway_error text:=nullif(trim(coalesce(p->>'gateway_error',p->>'error_message',p->>'decline_message','')),'');
begin
 if new.event_type not in ('page_view','quiz_started','quiz_answered','checkout_started','checkout_abandoned','payment_created','payment_failed','payment_approved','chat_started','chat_message') then return new; end if;
 v_status:=case new.event_type when 'page_view' then 'respondendo_quiz'::public.lead_checkout_status when 'quiz_started' then 'respondendo_quiz'::public.lead_checkout_status when 'quiz_answered' then 'respondendo_quiz'::public.lead_checkout_status when 'checkout_started' then 'no_checkout'::public.lead_checkout_status when 'checkout_abandoned' then 'parado_no_caixa'::public.lead_checkout_status when 'payment_failed' then 'cartao_recusado'::public.lead_checkout_status when 'payment_approved' then 'pago'::public.lead_checkout_status else null end;
 if new.event_type in ('chat_started','chat_message') then
   select id into v_conversation from public.crm_conversations where user_id=new.user_id and ((nullif(p->>'conversation_token','') is not null and public_token=p->>'conversation_token') or (v_customer_id is not null and customer_id=v_customer_id and funnel_id=new.funnel_id and status<>'closed') or (v_email is not null and lower(buyer_email)=lower(v_email) and funnel_id=new.funnel_id and status<>'closed') or (v_phone is not null and regexp_replace(coalesce(customer_whatsapp,''),'[^0-9]+','','g')=regexp_replace(v_phone,'[^0-9]+','','g') and funnel_id=new.funnel_id and status<>'closed')) order by updated_at desc limit 1;
   if v_conversation is null then return new; end if;
 else
   select id into v_conversation from public.crm_conversations where user_id=new.user_id and (funnel_id=new.funnel_id or (funnel_id is null and new.funnel_id is null)) and status<>'closed' and ((v_email is not null and lower(coalesce(buyer_email,''))=lower(v_email)) or (v_phone is not null and regexp_replace(coalesce(customer_whatsapp,''),'[^0-9]+','','g')=regexp_replace(v_phone,'[^0-9]+','','g')) or (v_customer_id is not null and customer_id=v_customer_id)) order by updated_at desc limit 1;
   if v_conversation is null then insert into public.crm_conversations(user_id,funnel_id,transaction_id,buyer_name,buyer_email,customer_whatsapp,status,metadata,checkout_status,quiz_answers,gateway_error_log,last_activity_at) values(new.user_id,new.funnel_id,nullif(p->>'transaction_id',''),nullif(trim(coalesce(c->>'name',p->>'name','')),''),v_email,v_phone,'open',p,coalesce(v_status,'respondendo_quiz'::public.lead_checkout_status),case when jsonb_typeof(p->'answers')='object' then p->'answers' else '{}'::jsonb end,v_gateway_error,coalesce(new.occurred_at,now())) returning id into v_conversation; end if;
 end if;
 update public.crm_conversations set buyer_name=coalesce(nullif(trim(coalesce(c->>'name',p->>'name','')),''),buyer_name),buyer_email=coalesce(v_email,buyer_email),customer_whatsapp=coalesce(v_phone,customer_whatsapp),customer_id=coalesce(customer_id,v_customer_id),transaction_id=coalesce(nullif(p->>'transaction_id',''),transaction_id),metadata=case when jsonb_typeof(p)='object' then metadata||p else metadata end,quiz_answers=case when jsonb_typeof(p->'answers')='object' then quiz_answers||p->'answers' else quiz_answers end,checkout_status=coalesce(v_status,checkout_status),gateway_error_log=coalesce(v_gateway_error,gateway_error_log),last_activity_at=greatest(last_activity_at,coalesce(new.occurred_at,now())),updated_at=now() where id=v_conversation and user_id=new.user_id;
 return new;
end;$function$;

create or replace function public.crm_ingest_channel_message(p_user_id uuid,p_channel text,p_channel_account_id uuid,p_external_user_id text,p_body text,p_external_message_id text,p_phone_e164 text default null,p_email text default null,p_display_name text default null,p_metadata jsonb default '{}'::jsonb)
returns jsonb language plpgsql security definer set search_path=public as $function$
declare v_identity public.crm_channel_identities%rowtype; v_conversation public.crm_conversations%rowtype; v_message public.crm_messages%rowtype; v_channel text:=lower(trim(p_channel)); v_provider text:=coalesce(nullif(trim(p_metadata->>'provider'),''),v_channel); v_email text:=lower(nullif(trim(p_email),'')); v_customer_id text;
begin
 if p_user_id is null or nullif(v_channel,'') is null or nullif(trim(p_external_user_id),'') is null or nullif(trim(p_body),'') is null then raise exception 'invalid_channel_message'; end if;
 if p_external_message_id is not null then select * into v_message from public.crm_messages where user_id=p_user_id and provider=v_provider and external_message_id=p_external_message_id limit 1; if found then select * into v_conversation from public.crm_conversations where id=v_message.conversation_id and user_id=p_user_id; return jsonb_build_object('conversation_id',v_conversation.id,'message_id',v_message.id,'identity_id',null,'deduplicated',true); end if; end if;
 select cl.id into v_customer_id from public.clients cl where cl.user_id=p_user_id and v_email is not null and lower(coalesce(cl.data->>'email',cl.data->>'buyer_email',cl.data->>'customer_email',''))=v_email order by cl.created_at desc limit 1;
 insert into public.crm_channel_identities(user_id,customer_id,channel,external_user_id,phone_e164,email,display_name,metadata,updated_at) values(p_user_id,v_customer_id,v_channel,trim(p_external_user_id),p_phone_e164,v_email,nullif(trim(p_display_name),''),coalesce(p_metadata,'{}'::jsonb),now()) on conflict(user_id,channel,external_user_id) do update set customer_id=coalesce(crm_channel_identities.customer_id,excluded.customer_id),phone_e164=coalesce(excluded.phone_e164,crm_channel_identities.phone_e164),email=coalesce(excluded.email,crm_channel_identities.email),display_name=coalesce(excluded.display_name,crm_channel_identities.display_name),metadata=crm_channel_identities.metadata||excluded.metadata,updated_at=now() returning * into v_identity;
 if v_identity.conversation_id is not null then select * into v_conversation from public.crm_conversations where id=v_identity.conversation_id and user_id=p_user_id; end if;
 if v_conversation.id is null and v_identity.customer_id is not null then select * into v_conversation from public.crm_conversations c where c.user_id=p_user_id and c.primary_channel=v_channel and c.channel_account_id=p_channel_account_id::text and c.customer_id=v_identity.customer_id and c.status in ('open','pending') order by c.updated_at desc limit 1; end if;
 if v_conversation.id is null then select * into v_conversation from public.crm_conversations c where c.user_id=p_user_id and c.primary_channel=v_channel and c.channel_account_id=p_channel_account_id::text and ((v_identity.email is not null and lower(c.buyer_email)=v_identity.email) or (v_identity.phone_e164 is not null and regexp_replace(coalesce(c.customer_whatsapp,''),'[^0-9]+','','g')=regexp_replace(v_identity.phone_e164,'[^0-9]+','','g'))) and c.status in ('open','pending') order by c.updated_at desc limit 1; end if;
 if v_conversation.id is null then insert into public.crm_conversations(user_id,status,priority,primary_channel,channel_account_id,buyer_name,buyer_email,customer_whatsapp,customer_id,metadata) values(p_user_id,'open','normal',v_channel,p_channel_account_id::text,v_identity.display_name,v_identity.email,v_identity.phone_e164,v_identity.customer_id,coalesce(p_metadata,'{}'::jsonb)) returning * into v_conversation; else update public.crm_conversations set buyer_name=coalesce(buyer_name,v_identity.display_name),buyer_email=coalesce(buyer_email,v_identity.email),customer_whatsapp=coalesce(customer_whatsapp,v_identity.phone_e164),customer_id=coalesce(customer_id,v_identity.customer_id),updated_at=now() where id=v_conversation.id and user_id=p_user_id returning * into v_conversation; end if;
 update public.crm_channel_identities set conversation_id=v_conversation.id,customer_id=coalesce(customer_id,v_identity.customer_id),updated_at=now() where id=v_identity.id;
 insert into public.crm_messages(conversation_id,user_id,direction,channel,body,metadata,client_message_id,provider,external_message_id,channel_account_id) values(v_conversation.id,p_user_id,'inbound',v_channel,p_body,coalesce(p_metadata,'{}'::jsonb),p_external_message_id,v_provider,p_external_message_id,p_channel_account_id::text) returning * into v_message;
 return jsonb_build_object('conversation_id',v_conversation.id,'message_id',v_message.id,'identity_id',v_identity.id,'deduplicated',false);
end;$function$;

create or replace function public.crm_sync_webhook_event() returns trigger language plpgsql security definer set search_path=public as $function$
declare v_event_type text:=lower(coalesce(new.payload->>'event_type','')); v_funnel_id text:=coalesce(new.payload->>'funnel_id',new.payload->>'funnelId'); v_product_id text:=coalesce(new.payload->>'product_id',new.payload->>'productId'); v_conversation_id uuid; v_token text;
begin
 if v_event_type in ('chat_started','chat_message') then new.processed_at:=timezone('utc',now()); return new; end if;
 if new.transaction_id is null and new.buyer_email is null then return new; end if;
 select id into v_conversation_id from public.crm_conversations where user_id=new.user_id and ((new.transaction_id is not null and transaction_id=new.transaction_id) or (new.buyer_email is not null and lower(buyer_email)=lower(new.buyer_email))) order by updated_at desc limit 1;
 if v_conversation_id is null then v_token:=encode(gen_random_bytes(24),'hex'); insert into public.crm_conversations(user_id,buyer_email,buyer_name,transaction_id,funnel_id,product_id,status,metadata,public_token,last_message_at) values(new.user_id,new.buyer_email,new.buyer_name,new.transaction_id,v_funnel_id,v_product_id,'open',jsonb_build_object('created_from','webhook','webhook_event_id',new.id),v_token,new.received_at) returning id into v_conversation_id; else update public.crm_conversations set buyer_email=coalesce(new.buyer_email,buyer_email),buyer_name=coalesce(new.buyer_name,buyer_name),transaction_id=coalesce(new.transaction_id,transaction_id),funnel_id=coalesce(v_funnel_id,funnel_id),product_id=coalesce(v_product_id,product_id),updated_at=timezone('utc',now()),metadata=metadata||jsonb_build_object('last_webhook_event_id',new.id) where id=v_conversation_id; end if;
 insert into public.crm_messages(conversation_id,user_id,direction,channel,body,metadata,created_at,provider) values(v_conversation_id,new.user_id,'inbound','internal',concat('Evento recebido: ',new.status,case when new.error_reason is not null then concat(' — ',new.error_reason) else '' end),jsonb_build_object('webhook_event_id',new.id,'transaction_id',new.transaction_id,'status',new.status,'source','crm_webhook_event'),new.received_at,'internal');
 new.processed_at:=timezone('utc',now()); return new;
end;$function$;

drop trigger if exists crm_messages_touch_conversation on public.crm_messages;

alter table public.crm_channel_identities drop constraint if exists crm_channel_identities_customer_identity_fkey;
alter table public.crm_channel_identities add constraint crm_channel_identities_customer_identity_fkey foreign key (user_id,customer_id) references public.clients(user_id,id);

revoke execute on function public.crm_replay_channel_outbox(uuid,text,text) from anon,authenticated;
grant execute on function public.crm_replay_channel_outbox(uuid,text,text) to authenticated;
