ALTER POLICY api_keys_insert_own ON public.api_keys WITH CHECK (user_id = (select auth.uid()));
ALTER POLICY api_keys_select_own ON public.api_keys USING (user_id = (select auth.uid()));
ALTER POLICY api_keys_update_own ON public.api_keys USING (user_id = (select auth.uid())) WITH CHECK (user_id = (select auth.uid()));
ALTER POLICY api_request_logs_select_own ON public.api_request_logs USING (user_id = (select auth.uid()));
ALTER POLICY attribution_sessions_owner ON public.attribution_sessions USING ((select auth.uid()) = user_id) WITH CHECK ((select auth.uid()) = user_id);
ALTER POLICY audit_logs_owner_read ON public.audit_logs USING (user_id = (select auth.uid()));
ALTER POLICY automation_executions_select_own ON public.automation_executions USING (user_id = (select auth.uid()));
ALTER POLICY automation_rules_owner ON public.automation_rules USING ((select auth.uid()) = user_id) WITH CHECK ((select auth.uid()) = user_id);
ALTER POLICY brand_identity_delete_own ON public.brand_identity_settings USING ((select auth.uid()) = user_id);
ALTER POLICY brand_identity_insert_own ON public.brand_identity_settings WITH CHECK ((select auth.uid()) = user_id);
ALTER POLICY brand_identity_select_own ON public.brand_identity_settings USING ((select auth.uid()) = user_id);
ALTER POLICY brand_identity_update_own ON public.brand_identity_settings USING ((select auth.uid()) = user_id) WITH CHECK ((select auth.uid()) = user_id);
ALTER POLICY checkout_events_owner ON public.checkout_events USING ((select auth.uid()) = user_id) WITH CHECK ((select auth.uid()) = user_id);
ALTER POLICY checkout_items_owner ON public.checkout_items USING ((select auth.uid()) = user_id) WITH CHECK ((select auth.uid()) = user_id);
ALTER POLICY checkout_offers_owner ON public.checkout_offers USING ((select auth.uid()) = user_id) WITH CHECK ((select auth.uid()) = user_id);
ALTER POLICY checkout_sessions_owner ON public.checkout_sessions USING ((select auth.uid()) = user_id) WITH CHECK ((select auth.uid()) = user_id);
ALTER POLICY compliance_events_owner_read ON public.compliance_events USING (user_id = (select auth.uid()));
ALTER POLICY dispute_evidence_owner_read ON public.dispute_evidence USING (user_id = (select auth.uid()));
ALTER POLICY disputes_owner_read ON public.disputes USING (user_id = (select auth.uid()));
ALTER POLICY funnel_connections_owner ON public.funnel_connections USING ((select auth.uid()) = user_id) WITH CHECK ((select auth.uid()) = user_id);
ALTER POLICY funnel_ingestion_tokens_owner_insert ON public.funnel_ingestion_tokens WITH CHECK (user_id = (select auth.uid()));
ALTER POLICY funnel_ingestion_tokens_owner_select ON public.funnel_ingestion_tokens USING (user_id = (select auth.uid()));
ALTER POLICY funnel_ingestion_tokens_owner_update ON public.funnel_ingestion_tokens USING (user_id = (select auth.uid())) WITH CHECK (user_id = (select auth.uid()));
ALTER POLICY funnel_trash_insert_own ON public.funnel_trash WITH CHECK (user_id = (select auth.uid()));
ALTER POLICY funnel_trash_select_own ON public.funnel_trash USING (user_id = (select auth.uid()));
ALTER POLICY funnel_trash_update_own ON public.funnel_trash USING (user_id = (select auth.uid())) WITH CHECK (user_id = (select auth.uid()));
ALTER POLICY gateway_operation_logs_owner ON public.gateway_operation_logs USING (user_id = (select auth.uid())) WITH CHECK (user_id = (select auth.uid()));
ALTER POLICY gateway_routes_owner ON public.gateway_routes USING (user_id = (select auth.uid())) WITH CHECK (user_id = (select auth.uid()));
ALTER POLICY gateway_transactions_owner ON public.gateway_transactions USING (user_id = (select auth.uid())) WITH CHECK (user_id = (select auth.uid()));
ALTER POLICY idempotency_keys_owner_read ON public.idempotency_keys USING (user_id = (select auth.uid()));
ALTER POLICY integration_events_owner ON public.integration_events USING ((select auth.uid()) = user_id) WITH CHECK ((select auth.uid()) = user_id);
ALTER POLICY merchant_risk_owner_read ON public.merchant_risk USING (user_id = (select auth.uid()));
ALTER POLICY platform_settings_owner ON public.platform_settings USING ((select auth.uid()) = user_id) WITH CHECK ((select auth.uid()) = user_id);
ALTER POLICY recovery_events_insert_own ON public.recovery_events WITH CHECK (user_id = (select auth.uid()));
ALTER POLICY recovery_events_select_own ON public.recovery_events USING (user_id = (select auth.uid()));
ALTER POLICY recovery_events_update_own ON public.recovery_events USING (user_id = (select auth.uid())) WITH CHECK (user_id = (select auth.uid()));
ALTER POLICY settlements_owner_read ON public.settlements USING (user_id = (select auth.uid()));
ALTER POLICY team_funnel_access_delete_own ON public.team_funnel_access USING (user_id = (select auth.uid()));
ALTER POLICY team_funnel_access_insert_own ON public.team_funnel_access WITH CHECK (user_id = (select auth.uid()));
ALTER POLICY team_funnel_access_select_own ON public.team_funnel_access USING (user_id = (select auth.uid()));
ALTER POLICY team_funnel_access_update_own ON public.team_funnel_access USING (user_id = (select auth.uid())) WITH CHECK (user_id = (select auth.uid()));
ALTER POLICY verification_status_owner_read ON public.verification_status USING (user_id = (select auth.uid()));
ALTER POLICY webhook_deliveries_insert_own ON public.webhook_deliveries WITH CHECK (user_id = (select auth.uid()));
ALTER POLICY webhook_deliveries_select_own ON public.webhook_deliveries USING (user_id = (select auth.uid()));
ALTER POLICY webhook_deliveries_update_own ON public.webhook_deliveries USING (user_id = (select auth.uid())) WITH CHECK (user_id = (select auth.uid()));
ALTER POLICY webhook_integrations_insert_own ON public.webhook_integrations WITH CHECK (user_id = (select auth.uid()));
ALTER POLICY webhook_integrations_select_own ON public.webhook_integrations USING (user_id = (select auth.uid()));
ALTER POLICY webhook_integrations_update_own ON public.webhook_integrations USING (user_id = (select auth.uid())) WITH CHECK (user_id = (select auth.uid()));