begin;
drop function if exists public.transition_gateway_transaction_status(uuid, uuid, text, text, text);
alter table public.reconciliation_runs add column if not exists organization_id uuid;
alter table public.reconciliation_items add column if not exists organization_id uuid;
update public.reconciliation_runs r set organization_id=m.organization_id from public.organization_members m where r.organization_id is null and m.user_id=r.user_id;
update public.reconciliation_items i set organization_id=coalesce((select t.organization_id from public.gateway_transactions t where t.id=i.transaction_id),(select r.organization_id from public.reconciliation_runs r where r.id=i.run_id),(select m.organization_id from public.organization_members m where m.user_id=i.user_id)) where i.organization_id is null;
alter table public.reconciliation_runs alter column organization_id set not null;
alter table public.reconciliation_items alter column organization_id set not null;
alter table public.reconciliation_runs add constraint reconciliation_runs_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete restrict;
alter table public.reconciliation_items add constraint reconciliation_items_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete restrict;
alter table public.reconciliation_runs add constraint reconciliation_runs_id_organization_key unique (id,organization_id);
alter table public.reconciliation_items add constraint reconciliation_items_run_tenant_fk foreign key (run_id,organization_id) references public.reconciliation_runs(id,organization_id);
create index if not exists reconciliation_runs_org_created_idx on public.reconciliation_runs (organization_id,created_at desc);
create index if not exists reconciliation_items_org_created_idx on public.reconciliation_items (organization_id,created_at desc);
create index if not exists reconciliation_items_org_transaction_idx on public.reconciliation_items (organization_id,transaction_id) where transaction_id is not null;
drop index if exists public.idx_gateway_transactions_tenant_idempotency;
drop index if exists public.gateway_payment_attempts_tx_key_idx;
commit;