create or replace function public.crm_ingest_channel_message(
  p_user_id uuid,p_channel text,p_channel_account_id uuid,p_external_user_id text,p_body text,p_external_message_id text,p_phone_e164 text default null,p_email text default null,p_display_name text default null,p_metadata jsonb default '{}'::jsonb
) returns jsonb language plpgsql security definer set search_path=public as $$
declare v_identity public.crm_channel_identities%rowtype; v_conversation public.crm_conversations%rowtype; v_message public.crm_messages%rowtype; v_existing boolean:=false; v_channel text:=lower(trim(p_channel));
begin
 if p_user_id is null or nullif(v_channel,'') is null or nullif(trim(p_external_user_id),'') is null or nullif(trim(p_body),'') is null then raise exception 'invalid_channel_message'; end if;
 insert into public.crm_channel_identities(user_id,channel,external_user_id,phone_e164,email,display_name,metadata,updated_at) values(p_user_id,v_channel,trim(p_external_user_id),p_phone_e164,lower(nullif(trim(p_email),'')),nullif(trim(p_display_name),''),coalesce(p_metadata,'{}'::jsonb),now()) on conflict(user_id,channel,external_user_id) do update set phone_e164=coalesce(excluded.phone_e164,crm_channel_identities.phone_e164),email=coalesce(excluded.email,crm_channel_identities.email),display_name=coalesce(excluded.display_name,crm_channel_identities.display_name),metadata=crm_channel_identities.metadata||excluded.metadata,updated_at=now() returning * into v_identity;
 if v_identity.conversation_id is not null then select * into v_conversation from public.crm_conversations where id=v_identity.conversation_id and user_id=p_user_id; end if;
 if v_conversation.id is null then select * into v_conversation from public.crm_conversations c where c.user_id=p_user_id and c.primary_channel=v_channel and c.channel_account_id=p_channel_account_id::text and ((v_identity.email is not null and lower(c.buyer_email)=lower(v_identity.email)) or (v_identity.phone_e164 is not null and c.metadata->>'phone_e164'=v_identity.phone_e164)) order by c.updated_at desc limit 1; end if;
 if v_conversation.id is null then insert into public.crm_conversations(user_id,status,priority,primary_channel,channel_account_id,buyer_name,buyer_email,metadata,last_message_at,last_message_direction,last_inbound_at,unread_count,queue_entered_at) values(p_user_id,'open','normal',v_channel,p_channel_account_id::text,v_identity.display_name,v_identity.email,coalesce(p_metadata,'{}'::jsonb),now(),'inbound',now(),1,now()) returning * into v_conversation; else update public.crm_conversations set buyer_name=coalesce(buyer_name,v_identity.display_name),buyer_email=coalesce(buyer_email,v_identity.email),last_message_at=now(),last_message_direction='inbound',last_inbound_at=now(),unread_count=unread_count+1,updated_at=now() where id=v_conversation.id returning * into v_conversation; end if;
 update public.crm_channel_identities set conversation_id=v_conversation.id,updated_at=now() where id=v_identity.id;
 if p_external_message_id is not null then select * into v_message from public.crm_messages where user_id=p_user_id and client_message_id=p_external_message_id limit 1; if v_message.id is not null then v_existing:=true; end if; end if;
 if v_message.id is null then insert into public.crm_messages(conversation_id,user_id,direction,channel,body,metadata,client_message_id,provider,external_message_id,channel_account_id) values(v_conversation.id,p_user_id,'inbound',v_channel,p_body,coalesce(p_metadata,'{}'::jsonb),p_external_message_id,coalesce(p_metadata->>'provider',v_channel),p_external_message_id,p_channel_account_id::text) returning * into v_message; end if;
 return jsonb_build_object('conversation_id',v_conversation.id,'message_id',v_message.id,'identity_id',v_identity.id,'deduplicated',v_existing);
end; $$;
revoke all on function public.crm_ingest_channel_message(uuid,text,uuid,text,text,text,text,text,text,jsonb) from public,anon,authenticated;
grant execute on function public.crm_ingest_channel_message(uuid,text,uuid,text,text,text,text,text,text,jsonb) to service_role;
