import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

type JsonObject = Record<string, unknown>;
type Failure = "technical" | "timeout" | "unavailable" | "declined" | "fraud" | "pending" | "unknown";
type Gateway = { id:string; user_id:string; provider:string; display_name:string; environment:string; status:string; capabilities:JsonObject; circuit_id:string; credential_id:string|null };
type Candidate = { gateway:Gateway; routeId:string|null; fallbackEnabled:boolean };
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization,x-client-info,apikey,content-type,x-idempotency-key,idempotency-key","Access-Control-Allow-Methods":"POST,OPTIONS","Content-Type":"application/json"};
const TIMEOUT=2800, BUDGET=7200, SAFETY=250, MAX_GATEWAYS=8;
const object=(v:unknown):v is JsonObject=>typeof v==="object"&&v!==null&&!Array.isArray(v);
const json=(v:unknown,s=200)=>new Response(JSON.stringify(v),{status:s,headers:cors});
const str=(v:unknown)=>typeof v==="string"?v.trim():"";
const retryable=(f:Failure|null)=>f==="technical"||f==="timeout"||f==="unavailable";
const numberValue=(v:unknown)=>{const n=typeof v==="number"?v:Number(v);return Number.isFinite(n)?n:null;};
const statusOf=(p:JsonObject)=>{const s=String(p.status??p.payment_status??"").toLowerCase();if(p.approved===true||["approved","succeeded","success","paid","received","confirmed","authorized","captured"].includes(s))return "approved";if(["pending","processing","in_process","in_review"].includes(s))return "pending";if(["declined","failed","rejected","canceled","cancelled"].includes(s))return "declined";return "error";};
const classify=(code:number,p:unknown):Failure=>{const x=object(p)?String(p.failure_class??p.failure_code??p.error_code??p.error??"").toLowerCase():"";if(x.includes("fraud")||x.includes("risk"))return "fraud";if(x.includes("pending")||x.includes("processing"))return "pending";if(x.includes("declin")||x.includes("insufficient")||x.includes("invalid_card"))return "declined";if(code===408||code===504)return "timeout";if(code===429||code>=500)return "unavailable";if(code>=400)return "declined";return "technical";};
async function authUser(req:Request,url:string,key:string){const a=req.headers.get("Authorization");if(!a)return null;const c=createClient(url,key,{global:{headers:{Authorization:a}}});const r=await c.auth.getUser();return r.error?null:r.data.user;}
async function hash(v:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return Array.from(new Uint8Array(d),b=>b.toString(16).padStart(2,"0")).join("");}
function gatewayRefs(node:unknown,out:Set<string>,depth=0):void{if(depth>16||!object(node))return;const id=str(node.gateway_id??node.gatewayId);if(id)out.add(id);for(const key of ["children","gateways","targets"]){const a=node[key];if(Array.isArray(a))for(const x of a)gatewayRefs(x,out,depth+1);}for(const key of ["if_true","then","true","yes","on_true","if_false","else","false","no","on_false"]){if(object(node[key]))gatewayRefs(node[key],out,depth+1);}if(object(node.node))gatewayRefs(node.node,out,depth+1);if(object(node.child))gatewayRefs(node.child,out,depth+1);}
async function credential(db:ReturnType<typeof createClient>,gatewayId:string){const r=await db.rpc("resolve_gateway_credential_for_gateway",{p_gateway_id:gatewayId});if(r.error)throw new Error(`credential_resolution_failed:${r.error.message}`);return object(r.data)?r.data:null;}
async function circuit(db:ReturnType<typeof createClient>,userId:string,g:Gateway){const r=await db.rpc("acquire_gateway_circuit",{p_user_id:userId,p_gateway_id:g.circuit_id,p_gateway_name:g.provider,p_failure_threshold:5,p_cooldown_seconds:60,p_probe_lease_seconds:10});if(r.error)throw new Error(`circuit_acquire_failed:${r.error.message}`);const x=Array.isArray(r.data)?r.data[0]:r.data;return object(x)?x:{allowed:false,circuit_state:"unknown"};}
async function circuitResult(db:ReturnType<typeof createClient>,userId:string,g:Gateway,f:Failure|null){if(retryable(f)){await db.rpc("record_gateway_circuit_failure",{p_user_id:userId,p_gateway_id:g.circuit_id,p_gateway_name:g.provider,p_failure_class:f,p_failure_threshold:5});}else{await db.rpc("record_gateway_circuit_success",{p_user_id:userId,p_gateway_id:g.circuit_id,p_gateway_name:g.provider});}}
async function health(db:ReturnType<typeof createClient>,g:Gateway,success:boolean,latency:number){await db.rpc("record_gateway_health",{p_gateway_id:g.circuit_id,p_gateway_name:g.provider,p_success:success,p_latency_ms:Math.max(0,Math.round(latency))});}
async function adapter(g:Gateway,payload:JsonObject,key:string,cred:JsonObject,internal:string,timeoutMs:number):Promise<{ok:boolean;failure:Failure|null;reason:string;payload:JsonObject;latencyMs:number}>{const started=Date.now(),controller=new AbortController(),timer=setTimeout(()=>controller.abort(),Math.max(250,timeoutMs));try{const url=`${Deno.env.get("SUPABASE_URL")}/functions/v1/gateway-provider-adapter`;const r=await fetch(url,{method:"POST",signal:controller.signal,headers:{"Content-Type":"application/json","X-Althea-Internal-Secret":internal,"X-Althea-Gateway-Id":g.id,"X-Althea-Idempotency-Key":key},body:JSON.stringify({...payload,provider:g.provider,environment:g.environment,gateway_id:g.id,idempotency_key:key,credential:cred})});const raw=await r.json().catch(()=>({}));const body=object(raw)?raw:{};const latencyMs=Date.now()-started;if(!r.ok)return{ok:false,failure:classify(r.status,body),reason:String(body.error??`adapter_http_${r.status}`),payload:body,latencyMs};const s=statusOf(body);if(s==="approved")return{ok:true,failure:null,reason:"approved",payload:body,latencyMs};if(s==="pending")return{ok:false,failure:"pending",reason:"gateway_pending",payload:body,latencyMs};if(s==="declined")return{ok:false,failure:"declined",reason:String(body.error??"gateway_declined"),payload:body,latencyMs};return{ok:false,failure:classify(r.status,body),reason:String(body.error??"gateway_error"),payload:body,latencyMs};}catch(e){return{ok:false,failure:e instanceof DOMException&&e.name==="AbortError"?"timeout":"technical",reason:e instanceof DOMException&&e.name==="AbortError"?"adapter_timeout":e instanceof Error?e.message:"adapter_request_failed",payload:{},latencyMs:Date.now()-started};}finally{clearTimeout(timer);}}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return json({ok:false,error:"method_not_allowed"},405);const url=Deno.env.get("SUPABASE_URL"),anon=Deno.env.get("SUPABASE_ANON_KEY")??Deno.env.get("SUPABASE_PUBLISHABLE_KEY"),service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"),internal=Deno.env.get("ALTHEA_INTERNAL_SECRET");if(!url||!anon||!service||!internal)return json({ok:false,error:"server_configuration_error"},500);const user=await authUser(req,url,anon);if(!user)return json({ok:false,error:"unauthorized"},401);const db=createClient(url,service,{auth:{persistSession:false}});let b:JsonObject;try{const x:unknown=await req.json();if(!object(x))return json({ok:false,error:"invalid_json"},400);b=x;}catch{return json({ok:false,error:"invalid_json"},400)}
const funnelId=str(b.funnel_id),amount=numberValue(b.amount),currency=str(b.currency??"BRL").toUpperCase(),key=str(b.idempotency_key??req.headers.get("x-idempotency-key")??req.headers.get("idempotency-key")),productId=b.product_id?String(b.product_id):null,metadata=object(b.metadata)?b.metadata:{},customer=object(b.customer)?b.customer:{},environment=str(b.environment??metadata.environment??"production").toLowerCase()==="sandbox"?"sandbox":"production";
if(!funnelId||amount===null||amount<=0||!/^[A-Z]{3}$/.test(currency)||!key)return json({ok:false,error:"funnel_id_amount_currency_and_idempotency_key_required"},400);if(key.length>200)return json({ok:false,error:"idempotency_key_too_long"},400);if(["pan","card_number","cardNumber","cvv","cvc","card_data"].some(k=>b[k]!==undefined))return json({ok:false,error:"raw_card_data_forbidden"},400);
const digest=await hash(JSON.stringify({funnelId,amount,currency,key,productId,metadata,customer,environment}));const reservation=await db.rpc("reserve_idempotency_key",{p_user_id:user.id,p_scope:`gateway-orchestrator:${funnelId}`,p_idempotency_key:key,p_request_digest:digest,p_ttl:"24 hours"});if(reservation.error)return json({ok:false,error:"idempotency_reservation_failed"},500);const lease=Array.isArray(reservation.data)?reservation.data[0]:reservation.data;if(!object(lease))return json({ok:false,error:"idempotency_invalid_response"},500);if(lease.acquired!==true){if(lease.response_payload)return json(lease.response_payload,Number(lease.response_code??200));return json({ok:false,error:"request_in_progress"},409);}const leaseId=String(lease.id??""),leaseToken=lease.lease_token?String(lease.lease_token):null;let completed=false;const finish=async(code:number,payload:unknown,status="completed",resourceType:string|null=null,resourceId:string|null=null)=>{if(!completed){await db.rpc("complete_idempotency_key",{p_id:leaseId,p_status:status,p_response_code:code,p_response_payload:payload,p_resource_type:resourceType,p_resource_id:resourceId,p_lease_token:leaseToken});completed=true;}return json(payload,code);};
try{
 const funnel=await db.from("funnels").select("id").eq("id",funnelId).eq("user_id",user.id).is("deleted_at",null).maybeSingle();if(funnel.error||!funnel.data)return finish(404,{ok:false,error:"funnel_not_found"},"failed");
 const routes=await db.from("gateway_routes").select("id,gateway_id,fallback_enabled,enabled,priority").eq("user_id",user.id).eq("funnel_id",funnelId).eq("enabled",true).order("priority",{ascending:true});if(routes.error)return finish(500,{ok:false,error:"route_lookup_failed"},"failed");
 const policyResult=await db.rpc("get_active_gateway_routing_policy",{p_user_id:user.id,p_funnel_id:funnelId});if(policyResult.error)return finish(500,{ok:false,error:"routing_policy_lookup_failed"},"failed");const policy=Array.isArray(policyResult.data)?policyResult.data[0]:policyResult.data;const policyIds=new Set<string>();if(object(policy)&&object(policy.routing_graph))gatewayRefs(policy.routing_graph,policyIds);const legacyIds=(routes.data??[]).map(r=>String(r.gateway_id));const allowedIds=policyIds.size?[...policyIds]:legacyIds;if(!allowedIds.length)return finish(409,{ok:false,error:"no_active_gateway_route"},"failed");
 const ranked=await db.rpc("rank_gateway_candidates",{p_user_id:user.id,p_gateway_ids:allowedIds,p_amount:amount,p_currency:currency,p_environment:environment,p_card_brand:metadata.card_brand?String(metadata.card_brand):null});if(ranked.error)return finish(500,{ok:false,error:"gateway_ranking_failed"},"failed");const rows=(Array.isArray(ranked.data)?ranked.data:[]).slice(0,MAX_GATEWAYS) as Array<JsonObject>;if(!rows.length)return finish(409,{ok:false,error:"no_eligible_gateway"},"failed");
 const gateways=await db.from("gateways").select("id,user_id,provider,display_name,environment,status,capabilities,circuit_id,credential_id").eq("user_id",user.id).in("id",rows.map(r=>String(r.gateway_id)));if(gateways.error)return finish(500,{ok:false,error:"gateway_lookup_failed"},"failed");const gm=new Map((gateways.data??[]).map(g=>[String(g.id),g as Gateway]));const routeMap=new Map((routes.data??[]).map(r=>[String(r.gateway_id),r]));const candidates:Candidate[]=rows.map(r=>{const g=gm.get(String(r.gateway_id));if(!g||g.status==="disabled"||g.environment!==environment)return null;const route=routeMap.get(g.id);return{gateway:g,routeId:route?String(route.id):null,fallbackEnabled:route?route.fallback_enabled!==false:true};}).filter((x):x is Candidate=>x!==null);if(!candidates.length)return finish(409,{ok:false,error:"no_eligible_gateway"},"failed");
 const txInsert=await db.from("gateway_transactions").insert({user_id:user.id,funnel_id:funnelId,product_id:productId,gateway_id:candidates[0].gateway.id,external_id:null,idempotency_key:key,amount,currency,status:"created",customer,metadata,routing_metadata:{environment,candidate_gateway_ids:candidates.map(c=>c.gateway.id),policy_id:object(policy)?String(policy.policy_id??""):null,policy_version:object(policy)?Number(policy.policy_version??0):null}}).select().single();if(txInsert.error||!txInsert.data)return finish(500,{ok:false,error:"transaction_create_failed"},"failed");const tx=txInsert.data as JsonObject;const txId=String(tx.id);let version=Number(tx.version);const attempts:JsonObject[]=[];let lastFailure:Failure="unknown";
 for(const candidate of candidates){if(Date.now()+SAFETY>=Date.now()+BUDGET){lastFailure="timeout";break;}const g=candidate.gateway;const c=await circuit(db,user.id,g);if(c.allowed!==true){attempts.push({gateway_id:g.id,outcome:"circuit_blocked",circuit_state:c.circuit_state??"unknown"});lastFailure="unavailable";continue;}const cred=await credential(db,g.id);if(!cred){attempts.push({gateway_id:g.id,outcome:"credential_missing"});lastFailure="unavailable";continue;}const allocated=await db.rpc("allocate_and_insert_gateway_payment_attempt",{p_user_id:user.id,p_transaction_id:txId,p_gateway_id:g.id,p_gateway_name:g.provider,p_idempotency_key:`${key}:${g.id}`,p_status:"pending",p_routing_rule_id:candidate.routeId,p_routing_policy_id:object(policy)?String(policy.policy_id??"")||null:null,p_routing_policy_version:object(policy)?Number(policy.policy_version??0)||null:null,p_decision_reason:`ranked_gateway:${g.id}`,p_product_id:productId});if(allocated.error||!allocated.data)return finish(500,{ok:false,error:"attempt_allocation_failed"},"failed","gateway_transaction",txId);const result=await adapter(g,{operation:"create_payment",amount,currency,product_id:productId,funnel_id:funnelId,customer,payment_token:b.payment_token??b.vault_token??null,metadata},`${key}:${g.id}`,cred,internal,Math.min(TIMEOUT,BUDGET));const external=result.payload.id?String(result.payload.id):result.payload.transaction_id?String(result.payload.transaction_id):null;const attemptStatus=result.ok?"approved":result.failure==="pending"?"pending":result.failure==="declined"?"declined":"error";await db.from("gateway_payment_attempts").update({status:attemptStatus,failure_class:result.failure,external_transaction_id:external,error_message:result.ok?null:result.reason,duration_ms:result.latencyMs,completed_at:result.ok||result.failure==="declined"?new Date().toISOString():null}).eq("id",String((allocated.data as JsonObject).id)).eq("user_id",user.id);await health(db,g,result.ok||result.failure==="declined"||result.failure==="pending",result.latencyMs);await circuitResult(db,user.id,g,result.failure);attempts.push({gateway_id:g.id,provider:g.provider,attempt_id:String((allocated.data as JsonObject).id),status:attemptStatus,failure_class:result.failure,reason:result.reason,external_transaction_id:external});
 if(result.ok||result.failure==="pending"){const next=result.ok?"approved":"pending";const transitioned=await db.rpc("transition_gateway_transaction_status",{p_transaction_id:txId,p_user_id:user.id,p_next_status:next,p_failure_code:result.failure,p_external_id:external,p_expected_version:version});if(transitioned.error)return finish(500,{ok:false,error:"transaction_transition_failed",detail:transitioned.error.message},"failed","gateway_transaction",txId);const row=Array.isArray(transitioned.data)?transitioned.data[0]:transitioned.data;if(!object(row))return finish(500,{ok:false,error:"transaction_transition_invalid"},"failed","gateway_transaction",txId);version=Number(row.version);return finish(result.ok?200:202,{ok:true,transaction:row,attempts,fallback_used:attempts.length>1,routing_policy:object(policy)?{id:policy.policy_id,version:policy.policy_version}:null},"completed","gateway_transaction",txId);}
 lastFailure=result.failure??"unknown";if(result.failure==="declined"&&candidate.fallbackEnabled===false)break;if(!retryable(result.failure)&&result.failure!=="declined")break; }
 if(lastFailure==="timeout"||lastFailure==="technical"||lastFailure==="unavailable"||lastFailure==="unknown")return finish(202,{ok:false,status:"pending_recovery",transaction_id:txId,attempts},"completed","gateway_transaction",txId);const final=await db.rpc("transition_gateway_transaction_status",{p_transaction_id:txId,p_user_id:user.id,p_next_status:"failed",p_failure_code:lastFailure,p_external_id:null,p_expected_version:version});if(final.error)return finish(500,{ok:false,error:"final_transaction_transition_failed"},"failed","gateway_transaction",txId);const row=Array.isArray(final.data)?final.data[0]:final.data;return finish(402,{ok:false,error:"payment_declined",transaction:row,attempts},"failed","gateway_transaction",txId);
}catch(e){return finish(500,{ok:false,error:"orchestrator_unhandled_error",detail:e instanceof Error?e.message:"unknown_error"},"failed");}
});
