'use client'

import { useEffect, useState } from 'react'
import { ArrowLeft, BrainCircuit, RefreshCw, Target } from 'lucide-react'
import { Button } from '@/components/ui/button'

type Action = { action_type: string; priority: number; score: number; rationale: string; evidence: Record<string, unknown> }
const labels: Record<string,string> = { respond: 'Responder agora', recover: 'Recuperar receita', upsell: 'Avaliar upsell', queue_review: 'Revisar fila' }

export default function CRMNextBestActionsPage() {
  const [conversation, setConversation] = useState(''); const [actions, setActions] = useState<Action[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  async function load(id?: string) { setLoading(true); setError(''); try { const qs = id ? `?conversation=${encodeURIComponent(id)}` : ''; const r = await fetch(`/api/crm/next-best-actions${qs}`, { cache: 'no-store' }); const body = await r.json(); if (!r.ok) throw new Error(body.error || 'Não foi possível calcular as ações.'); setActions(body.actions ?? []) } catch (e) { setError(e instanceof Error ? e.message : 'Falha ao carregar.') } finally { setLoading(false) } }
  useEffect(() => { const id = new URLSearchParams(window.location.search).get('conversation')?.trim() || ''; setConversation(id); void load(id || undefined) }, [])
  return <div className="w-full space-y-5 text-white"><a href="/dashboard/crm" className="mb-6 inline-flex min-h-10 items-center gap-2 rounded-xl px-3 text-xs font-bold text-[var(--althea-muted)] transition hover:bg-white/[.04] hover:text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1DB854]/50"> <ArrowLeft size={15}/> Voltar ao Multi-CRM</a><div className="mb-6 rounded-3xl border border-white/[.055] bg-[var(--althea-surface)] p-6"><div className="flex items-start justify-between gap-4"><div><div className="mb-2 flex items-center gap-2 text-[10px] font-black uppercase tracking-[.2em] text-[var(--althea-brand)]"><BrainCircuit size={14}/> Revenue OS</div><h1 className="text-3xl font-black">Next Best Action</h1><p className="mt-2 max-w-2xl text-sm text-[var(--althea-muted)]">Prioriza ações a partir de sinais reais da conversa, eventos financeiros e receita observada. Não usa dados fictícios.</p></div><Button type="button" variant="ghost" size="icon" onClick={()=>void load(conversation || undefined)} aria-label="Recalcular" title="Recalcular"><RefreshCw size={17} className={loading?'animate-spin':''}/></Button></div></div>{error&&<div className="mb-4 rounded-2xl border border-rose-500/20 bg-rose-500/10 p-4 text-sm text-rose-200">{error}</div>}<section className="grid gap-3 md:grid-cols-2">{!loading&&actions.length===0&&<div className="rounded-2xl border border-white/[.055] bg-[var(--althea-surface)] p-8 text-sm text-[var(--althea-muted)]">Nenhuma ação recomendada para os sinais atuais.</div>}{actions.map((a,i)=><article key={`${a.action_type}-${i}`} className="rounded-2xl border border-white/[.055] bg-[var(--althea-surface)] p-5"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2 text-sm font-black"><Target size={16} className="text-[var(--althea-brand)]"/>{labels[a.action_type]??a.action_type}</div><span className="rounded-full bg-white/[.05] px-2 py-1 text-[10px] font-black">{Math.round(Number(a.score))}/100</span></div><p className="mt-4 text-sm leading-6 text-slate-300">{a.rationale}</p><div className="mt-4 border-t border-white/[.06] pt-3 text-[10px] text-[var(--althea-muted)]">Prioridade: {a.priority}</div></article>)}</section></div>
}
