import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
const db=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);
const xml=(s:string)=>new Response(`<?xml version="1.0" encoding="UTF-8"?><Response>${s}</Response>`,{status:200,headers:{"content-type":"application/xml"}});
const json=(x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{"content-type":"application/json"}});
function b64(bytes:ArrayBuffer){let s="";for(const b of new Uint8Array(bytes))s+=String.fromCharCode(b);return btoa(s)}
async function sign(secret:string,value:string){const k=await crypto.subtle.importKey("raw",new TextEncoder().encode(secret),{name:"HMAC",hash:"SHA-1"},false,["sign"]);return b64(await crypto.subtle.sign("HMAC",k,new TextEncoder().encode(value)))}
function eq(a:string,b:string){if(a.length!==b.length)return false;let n=0;for(let i=0;i<a.length;i++)n|=a.charCodeAt(i)^b.charCodeAt(i);return n===0}
Deno.serve(async req=>{if(req.method!=="POST")return json({error:"method_not_allowed"},405);try{const raw=await req.text(),p=new URLSearchParams(raw),to=p.get("To")||"",from=p.get("From")||"",body=p.get("Body")||"",sid=p.get("MessageSid")||p.get("SmsSid")||"";if(!to||!from||!sid)return json({error:"invalid_twilio_event"},400);const q=await db.from("crm_channel_accounts").select("id,user_id,channel,provider,external_account_id,status,credentials_ref,metadata").eq("channel","sms").eq("status","active").limit(100);if(q.error)throw q.error;const a:any=(q.data||[]).find((x:any)=>String(x.external_account_id||"")===to||String(x.metadata?.from_number||"")===to);if(!a)return json({error:"channel_account_not_found"},404);const rawCred=a.credentials_ref?Deno.env.get(a.credentials_ref):undefined;let c:any={};if(rawCred){try{c=JSON.parse(rawCred)}catch{c={auth_token:rawCred}}}const token=String(c.auth_token||c.token||"");if(!token)return json({error:"twilio_auth_token_missing"},500);const signature=req.headers.get("x-twilio-signature")||"",pairs=[...p.entries()].sort((x,y)=>x[0].localeCompare(y[0])),base=new URL(req.url).toString()+pairs.map(([k,v])=>k+v).join("");if(!signature||!eq(signature,await sign(token,base)))return json({error:"invalid_signature"},401);const r=await db.rpc("crm_ingest_channel_message",{p_user_id:a.user_id,p_channel:"sms",p_channel_account_id:a.id,p_external_user_id:from,p_body:body,p_external_message_id:sid,p_phone_e164:from,p_email:null,p_display_name:null,p_metadata:{provider:"twilio",provider_event:Object.fromEntries(p.entries()),to}});if(r.error)throw r.error;return xml("")}catch(e){return json({ok:false,error:e instanceof Error?e.message:String(e)},500)}});
